"""Service for generating investigation reports from playbook executions."""

import json
import logging
from datetime import datetime
from typing import Optional

from sqlalchemy.orm import Session

from ixion.engine.renderer import TemplateRenderer
from ixion.models.playbook import PlaybookExecution
from ixion.storage.document_repository import DocumentRepository
from ixion.storage.collection_repository import CollectionRepository

logger = logging.getLogger(__name__)

REPORT_COLLECTION_NAME = "Playbook Reports"

OUTCOME_LABELS = {
    "true_positive": "True Positive",
    "false_positive": "False Positive",
    "benign_true_positive": "Benign True Positive",
    "risk_accepted": "Risk Accepted",
    "inconclusive": "Inconclusive",
    "escalated": "Escalated",
}

REPORT_TEMPLATE = """\
# Investigation Report: {{ playbook_name }}

| Field | Value |
|-------|-------|
| **Execution ID** | {{ execution_id }} |
| **Playbook** | {{ playbook_name }} |
| **Alert ID** | {{ alert_id }} |
{% if case_number %}| **Case** | {{ case_number }} — {{ case_title }} |
{% endif %}| **Analyst** | {{ analyst }} |
| **Started** | {{ started_at }} |
| **Completed** | {{ completed_at }} |
| **Outcome** | {{ outcome_label }} |

{% if outcome_notes %}
## Outcome Notes

{{ outcome_notes }}
{% endif %}

## Steps

| # | Step | Status | Action Taken | Findings | Evidence | Risk | Completed | Notes |
|---|------|--------|-------------|----------|----------|------|-----------|-------|
{% for step in steps %}| {{ step.order }} | {{ step.title }} | {{ step.status }} | {{ step.action_taken }} | {{ step.findings }} | {{ step.evidence }} | {{ step.risk }} | {{ step.completed_at }} | {{ step.notes }} |
{% endfor %}

## Timeline

{% for event in timeline %}
- **{{ event.time }}** — {{ event.description }}
{% endfor %}

---
*Auto-generated by IXION Playbook Engine on {{ generated_at }}*
"""


class ExecutionReportService:
    """Generates investigation reports from completed playbook executions."""

    def __init__(self, session: Session):
        self.session = session
        self.document_repo = DocumentRepository(session)
        self.collection_repo = CollectionRepository(session)
        self.renderer = TemplateRenderer()

    def generate_report(
        self,
        execution: PlaybookExecution,
        analyst_username: str | None = None,
    ):
        """Generate a report document for a completed execution.

        Returns the created Document.
        """
        report_data = self._build_report_data(execution, analyst_username)
        rendered = self.renderer.render(REPORT_TEMPLATE, report_data)

        doc_name = (
            f"Report — {execution.playbook.name} — "
            f"Exec #{execution.id} — "
            f"{datetime.utcnow().strftime('%Y-%m-%d %H:%M')}"
        )

        document = self.document_repo.create(
            name=doc_name,
            rendered_content=rendered,
            output_format="markdown",
            input_data=json.dumps(report_data, default=str),
        )

        # Place in collection
        collection = self._get_or_create_collection()
        self.collection_repo.add_document(collection, document)

        # Link back to execution
        execution.report_document_id = document.id
        self.session.flush()

        logger.info(
            "Generated report document %d for execution %d",
            document.id,
            execution.id,
        )
        return document

    def regenerate_report(
        self,
        execution: PlaybookExecution,
        analyst_username: str | None = None,
    ):
        """Regenerate a report — amends existing document or creates new one.

        Returns the Document.
        """
        report_data = self._build_report_data(execution, analyst_username)
        rendered = self.renderer.render(REPORT_TEMPLATE, report_data)

        if execution.report_document_id:
            document = self.document_repo.get_by_id(execution.report_document_id)
            if document:
                document = self.document_repo.amend(
                    document=document,
                    rendered_content=rendered,
                    input_data=json.dumps(report_data, default=str),
                    amendment_reason="Report regenerated",
                    amended_by=analyst_username,
                )
                logger.info(
                    "Regenerated report document %d (v%d) for execution %d",
                    document.id,
                    document.current_version,
                    execution.id,
                )
                return document

        # No existing report — create new
        return self.generate_report(execution, analyst_username)

    def _get_or_create_collection(self):
        """Find or create the 'Playbook Reports' collection."""
        collection = self.collection_repo.get_by_name(REPORT_COLLECTION_NAME)
        if not collection:
            collection = self.collection_repo.create(
                name=REPORT_COLLECTION_NAME,
                description="Auto-generated investigation reports from playbook executions",
                icon="file-text",
            )
            logger.info("Created collection: %s", REPORT_COLLECTION_NAME)
        return collection

    def _build_report_data(
        self,
        execution: PlaybookExecution,
        analyst_username: str | None = None,
    ) -> dict:
        """Extract all execution data into a template-friendly dict."""
        playbook = execution.playbook
        steps_data = []
        timeline = []

        if playbook and playbook.steps:
            for step in sorted(playbook.steps, key=lambda s: s.step_order):
                step_status = execution.get_step_status(step.id) or {}
                ad = step_status.get("action_data") or {}

                steps_data.append({
                    "order": step.step_order,
                    "title": step.title or "",
                    "status": step_status.get("status", "pending"),
                    "action_taken": ad.get("action_taken", ""),
                    "findings": ad.get("findings", ""),
                    "evidence": ad.get("evidence_collected", ""),
                    "risk": ad.get("risk_assessment", ""),
                    "completed_at": step_status.get("completed_at", ""),
                    "notes": step_status.get("notes", ""),
                })

                if step_status.get("completed_at"):
                    who = step_status.get("completed_by_username", "system")
                    timeline.append({
                        "time": step_status["completed_at"],
                        "description": f"Step {step.step_order} \"{step.title}\" — "
                                       f"{step_status.get('status', 'completed')} by {who}",
                    })

        # Sort timeline chronologically
        timeline.sort(key=lambda e: e["time"])

        analyst = analyst_username or (
            execution.executed_by.username if execution.executed_by else "Unknown"
        )

        return {
            "execution_id": execution.id,
            "playbook_name": playbook.name if playbook else "Unknown",
            "alert_id": execution.es_alert_id,
            "case_number": execution.case.case_number if execution.case else "",
            "case_title": execution.case.title if execution.case else "",
            "analyst": analyst,
            "started_at": execution.started_at.isoformat() if execution.started_at else "",
            "completed_at": execution.completed_at.isoformat() if execution.completed_at else "",
            "outcome_label": OUTCOME_LABELS.get(execution.outcome or "", execution.outcome or "N/A"),
            "outcome_notes": execution.outcome_notes or "",
            "steps": steps_data,
            "timeline": timeline,
            "generated_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        }
