"""SOC Documentation Templates & Framework Alignment.

Pre-built Jinja2 templates for common SOC operational documents,
aligned with NIST 800-61, NIST CSF 2.0, ISO 27035, SANS IR, SOC-CMM, MITRE ATT&CK.
"""

import logging
from typing import Optional

logger = logging.getLogger(__name__)

# =============================================================================
# Constants
# =============================================================================

DOCUMENT_TYPES = {
    "SOP": "Standard Operating Procedure",
    "SOI": "Standard Operating Instruction",
    "WI": "Work Instruction",
    "KB": "Knowledge Base",
    "RUNBOOK": "Runbook",
    "IRP": "Incident Response Plan",
    "AAR": "After-Action Report",
    "THREAT_ADVISORY": "Threat Advisory",
    "DETECTION_RULE": "Detection Rule Documentation",
}

# =============================================================================
# Collection definitions
# =============================================================================

COLLECTION_DEFS = [
    {"name": "Standard Operating Procedures", "description": "Formalized operational procedures for SOC activities", "icon": None},
    {"name": "Standard Operating Instructions", "description": "Tactical task-specific instructions", "icon": None},
    {"name": "Work Instructions", "description": "Granular step-by-step task guidance", "icon": None},
    {"name": "Knowledge Base", "description": "Self-service reference documentation", "icon": None},
    {"name": "Runbooks", "description": "Operational procedure guides for routine tasks", "icon": None},
    {"name": "Incident Response Plans", "description": "Strategic incident handling plans", "icon": None},
    {"name": "After-Action Reports", "description": "Post-incident retrospective analysis", "icon": None},
    {"name": "Threat Intelligence", "description": "Threat advisories and actor profiles", "icon": None},
    {"name": "Detection Engineering", "description": "Detection rule documentation", "icon": None},
]

# =============================================================================
# Template definitions — 19 templates
# =============================================================================

TEMPLATE_DEFS = [
    # =========================================================================
    # SOPs (4)
    # =========================================================================
    {
        "name": "SOC Monitoring & Triage SOP",
        "document_type": "SOP",
        "collection": "Standard Operating Procedures",
        "description": "Standard operating procedure for SOC monitoring, alert triage, and initial response activities.",
        "tags": ["NIST-CSF-2.0", "SOC-CMM"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "SOP-MON-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "classification", "var_type": "string", "required": False, "default_value": "INTERNAL", "description": "Document classification level"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "department", "var_type": "string", "required": False, "default_value": "Security Operations Center", "description": "Owning department"},
            {"name": "review_date", "var_type": "string", "required": False, "default_value": "", "description": "Next review date"},
            {"name": "approved_by", "var_type": "string", "required": False, "default_value": "", "description": "Approval authority"},
            {"name": "siem_tool", "var_type": "string", "required": False, "default_value": "Elastic SIEM", "description": "Primary SIEM platform"},
            {"name": "escalation_contacts", "var_type": "string", "required": False, "default_value": "", "description": "Escalation contact list"},
            {"name": "shift_schedule", "var_type": "string", "required": False, "default_value": "", "description": "Shift schedule description"},
        ],
        "content": """# {{ doc_id }} - SOC Monitoring & Triage SOP

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Classification** | {{ classification }} |
| **Author** | {{ author }} |
| **Department** | {{ department }} |
| **Review Date** | {{ review_date }} |
| **Approved By** | {{ approved_by }} |

---

## 1. Purpose

This Standard Operating Procedure defines the processes and responsibilities for continuous security monitoring, alert triage, and initial incident response within the {{ department }}.

## 2. Scope

This SOP applies to all SOC analysts responsible for monitoring security events and alerts generated by {{ siem_tool }} and associated security tools.

## 3. Roles & Responsibilities

| Role | Responsibility |
|------|---------------|
| **L1 Analyst** | Monitor dashboards, perform initial triage, classify alerts |
| **L2 Analyst** | Deep-dive investigation, correlation analysis, escalation decisions |
| **L3 Analyst / IR Lead** | Advanced threat hunting, incident response coordination |
| **SOC Manager** | Oversight, quality assurance, metrics review |

## 4. Monitoring Procedures

### 4.1 Dashboard Monitoring
- Review {{ siem_tool }} dashboards at the start of each shift
- Monitor real-time alert feed continuously
- Check health status of all log sources and data pipelines
- Review any overnight alerts flagged for follow-up

### 4.2 Alert Queue Management
- Process alerts in priority order (Critical > High > Medium > Low)
- Acknowledge alerts within SLA timeframes
- Document all triage decisions with rationale

## 5. Severity Classification

| Severity | Description | Response SLA | Examples |
|----------|-------------|-------------|----------|
| **Critical** | Active compromise, data exfiltration | 15 minutes | Ransomware execution, active C2 |
| **High** | Likely malicious, immediate risk | 30 minutes | Malware detection, brute force success |
| **Medium** | Potentially malicious, needs investigation | 2 hours | Suspicious process, policy violation |
| **Low** | Informational, low risk | 8 hours | Failed login attempts, scan activity |

## 6. Initial Triage Steps

1. **Verify Alert Legitimacy** - Confirm the alert is not a known false positive
2. **Gather Context** - Review source/destination, user, host, and process details
3. **Check Threat Intelligence** - Query IOCs against threat intelligence feeds
4. **Assess Impact** - Determine affected systems, users, and data
5. **Classify Severity** - Assign severity based on classification table above
6. **Document Findings** - Record all observations in the case management system
7. **Decide Action** - Close as false positive, escalate, or initiate response

## 7. Escalation Criteria

Escalate to the next tier when:
- Alert severity is Critical or High and confirmed malicious
- Multiple correlated alerts suggest an active campaign
- Analyst is unable to determine alert legitimacy within SLA
- Alert involves sensitive systems, executive accounts, or regulated data

**Escalation Contacts:**
{{ escalation_contacts }}

## 8. Metrics & KPIs

| Metric | Target | Measurement |
|--------|--------|-------------|
| Mean Time to Acknowledge (MTTA) | < 15 min (Critical) | Time from alert to first analyst action |
| Mean Time to Triage (MTTT) | < 30 min (Critical) | Time from alert to classification |
| False Positive Rate | < 30% | Alerts closed as FP / Total alerts |
| Escalation Rate | 10-20% | Escalated alerts / Total alerts |

## 9. Shift Schedule

{{ shift_schedule }}

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
    {
        "name": "Incident Escalation SOP",
        "document_type": "SOP",
        "collection": "Standard Operating Procedures",
        "description": "Standard operating procedure for incident escalation, notification, and communication management.",
        "tags": ["NIST-800-61", "SANS-IR"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "SOP-ESC-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "classification", "var_type": "string", "required": False, "default_value": "INTERNAL", "description": "Document classification level"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "escalation_matrix", "var_type": "text", "required": False, "default_value": "", "description": "Escalation matrix details"},
            {"name": "notification_templates", "var_type": "text", "required": False, "default_value": "", "description": "Notification message templates"},
            {"name": "severity_definitions", "var_type": "text", "required": False, "default_value": "", "description": "Severity level definitions"},
        ],
        "content": """# {{ doc_id }} - Incident Escalation SOP

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Classification** | {{ classification }} |
| **Author** | {{ author }} |

---

## 1. Purpose

This SOP defines the escalation procedures for security incidents, including severity classification, escalation paths, notification requirements, and communication protocols aligned with NIST SP 800-61 and the SANS Incident Response framework.

## 2. Scope

Applies to all SOC personnel, incident responders, and management involved in security incident handling.

## 3. Severity Levels

| Level | Name | Description | Response Time | Escalation Path |
|-------|------|-------------|---------------|-----------------|
| **P1** | Critical | Active breach, data exfiltration, ransomware | Immediate | SOC Lead > CISO > Executive Team |
| **P2** | High | Confirmed malware, compromised account | 30 minutes | SOC Lead > IR Manager |
| **P3** | Medium | Suspicious activity, policy violation | 2 hours | L2 Analyst > SOC Lead |
| **P4** | Low | Informational, minor policy deviation | 8 hours | Documented, no escalation required |

{{ severity_definitions }}

## 4. Escalation Matrix

| Trigger | Escalate To | Method | Timeline |
|---------|------------|--------|----------|
| P1 confirmed | CISO + IR Team | Phone + Email | Immediate |
| P2 confirmed | IR Manager | Email + Chat | Within 30 min |
| P3 unresolved after 4h | SOC Lead | Chat | Within 4 hours |
| Multiple correlated P3+ | SOC Lead | Email | Within 1 hour |
| Regulatory data involved | Legal + DPO | Email | Within 1 hour |

{{ escalation_matrix }}

## 5. Notification Procedures

### 5.1 Internal Notifications
1. Create incident ticket in case management system
2. Notify on-call personnel via designated communication channel
3. Update incident status board / dashboard
4. Schedule bridge call for P1/P2 incidents

### 5.2 External Notifications
- **Law Enforcement**: Only with CISO/Legal approval
- **Regulators**: Per regulatory requirements (coordinate with Legal)
- **Customers**: Per contractual obligations (coordinate with Communications)
- **Third Parties**: Only if directly involved in incident

### 5.3 Communication Templates

{{ notification_templates }}

## 6. Timeline Requirements

| Action | P1 | P2 | P3 | P4 |
|--------|----|----|----|----|
| Initial notification | 15 min | 30 min | 2 hours | 8 hours |
| Status update | Every 30 min | Every 2 hours | Every 4 hours | Daily |
| Post-incident report | 24 hours | 72 hours | 1 week | N/A |

## 7. De-escalation Criteria

An incident may be de-escalated when:
- Threat has been contained and eradicated
- No further malicious activity detected for 24+ hours
- All affected systems restored to normal operation
- Stakeholders have been notified of resolution

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
    {
        "name": "Evidence Handling & Chain of Custody SOP",
        "document_type": "SOP",
        "collection": "Standard Operating Procedures",
        "description": "Standard operating procedure for digital evidence collection, chain of custody, and forensic preservation.",
        "tags": ["ISO-27035", "NIST-800-61"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "SOP-EVD-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "classification", "var_type": "string", "required": False, "default_value": "CONFIDENTIAL", "description": "Document classification level"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "evidence_storage_location", "var_type": "string", "required": False, "default_value": "", "description": "Secure evidence storage location"},
            {"name": "forensic_tools", "var_type": "string", "required": False, "default_value": "", "description": "Approved forensic tools list"},
            {"name": "legal_contact", "var_type": "string", "required": False, "default_value": "", "description": "Legal department contact"},
        ],
        "content": """# {{ doc_id }} - Evidence Handling & Chain of Custody SOP

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Classification** | {{ classification }} |
| **Author** | {{ author }} |
| **Legal Contact** | {{ legal_contact }} |

---

## 1. Purpose

This SOP establishes procedures for the collection, handling, storage, and transfer of digital evidence during security investigations, ensuring chain of custody integrity for potential legal proceedings.

## 2. Scope

Applies to all personnel involved in evidence collection during incident response, forensic investigations, and internal investigations.

## 3. Evidence Types

| Type | Examples | Collection Method |
|------|----------|------------------|
| **Volatile** | Memory dumps, running processes, network connections | Live acquisition tools |
| **Non-volatile** | Disk images, log files, registry exports | Forensic imaging |
| **Network** | Packet captures, flow data, proxy logs | Network taps, PCAP |
| **Cloud** | API logs, storage snapshots, IAM audit trails | Provider console/API |

## 4. Collection Procedures

### 4.1 Pre-Collection
1. Obtain authorization from incident commander or management
2. Document the scene (screenshots, photographs if physical)
3. Note date, time, timezone, and personnel present
4. Prepare write-blocking hardware/software

### 4.2 Collection Order (Volatility)
1. CPU registers and cache
2. Memory (RAM) contents
3. Network connections and state
4. Running processes
5. Disk contents
6. Remote logging data
7. Physical configuration and network topology
8. Archival media and backups

### 4.3 Forensic Tools
{{ forensic_tools }}

## 5. Chain of Custody Form

For each evidence item, record:

| Field | Description |
|-------|-------------|
| Evidence ID | Unique identifier (e.g., EVD-YYYY-NNNN) |
| Description | Brief description of the evidence item |
| Source | System/device from which evidence was collected |
| Collected By | Name and title of collector |
| Collection Date/Time | Timestamp with timezone |
| Hash (SHA-256) | Cryptographic hash at time of collection |
| Storage Location | Where evidence is stored |

### Transfer Log

| Date/Time | Released By | Received By | Purpose | Signature |
|-----------|-------------|-------------|---------|-----------|
| | | | | |

## 6. Storage Requirements

- **Location**: {{ evidence_storage_location }}
- Evidence must be stored in a secure, access-controlled environment
- Digital evidence stored on encrypted, write-protected media
- Physical evidence in tamper-evident containers
- Access log maintained for all evidence storage areas
- Temperature and humidity controlled (for physical media)

## 7. Transfer Procedures

1. Complete transfer log entry before physical handoff
2. Both parties verify evidence integrity (hash verification)
3. Update chain of custody documentation
4. Notify case manager of transfer

## 8. Retention Policy

| Category | Retention Period | Disposition |
|----------|-----------------|-------------|
| Active investigation | Duration of case + 1 year | Review for archival |
| Legal hold | Until hold released by Legal | Secure destruction |
| Regulatory requirement | Per applicable regulation | Secure destruction |
| Standard | 3 years post-incident | Secure destruction |

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
    {
        "name": "Shift Handover SOP",
        "document_type": "SOP",
        "collection": "Standard Operating Procedures",
        "description": "Standard operating procedure for SOC shift handover including checklist and status reporting.",
        "tags": ["SOC-CMM"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "SOP-SHO-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "classification", "var_type": "string", "required": False, "default_value": "INTERNAL", "description": "Document classification level"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "shift_times", "var_type": "string", "required": False, "default_value": "Day: 07:00-15:00 | Swing: 15:00-23:00 | Night: 23:00-07:00", "description": "Shift schedule times"},
            {"name": "handover_checklist_items", "var_type": "text", "required": False, "default_value": "", "description": "Additional handover checklist items"},
        ],
        "content": """# {{ doc_id }} - Shift Handover SOP

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Classification** | {{ classification }} |
| **Author** | {{ author }} |

---

## 1. Purpose

This SOP ensures consistent and complete shift handovers between SOC analyst teams, minimizing information loss and ensuring continuity of security monitoring operations.

## 2. Scope

Applies to all SOC analysts performing shift rotations.

**Shift Schedule**: {{ shift_times }}

## 3. Handover Procedure

### 3.1 Outgoing Shift (15 min before shift end)
1. Complete all in-progress triage documentation
2. Update status of all open investigations
3. Prepare handover briefing document
4. Ensure all critical alerts are documented

### 3.2 Handover Meeting (At shift change)
1. Face-to-face or video briefing (10-15 minutes)
2. Walk through open incidents and investigations
3. Highlight any pending escalations or follow-ups
4. Transfer ownership of active tickets
5. Confirm incoming team has access to all necessary tools

### 3.3 Incoming Shift (First 15 min)
1. Review handover documentation
2. Verify dashboard and monitoring tool access
3. Check alert queue for any new items
4. Acknowledge receipt of handover

## 4. Handover Checklist

- [ ] All open incidents documented with current status
- [ ] Pending escalations identified and transferred
- [ ] Alert queue reviewed - no unacknowledged critical alerts
- [ ] SIEM and monitoring tools operational
- [ ] Log source health verified - no gaps in data collection
- [ ] Communication channels tested
- [ ] On-call contact information confirmed
- [ ] Any scheduled maintenance or changes noted
{{ handover_checklist_items }}

## 5. Open Investigations

| Ticket ID | Severity | Summary | Status | Next Action | Owner |
|-----------|----------|---------|--------|-------------|-------|
| | | | | | |

## 6. Pending Actions

| Action | Priority | Deadline | Assigned To | Notes |
|--------|----------|----------|-------------|-------|
| | | | | |

## 7. Environment Status

| System | Status | Notes |
|--------|--------|-------|
| SIEM Platform | | |
| EDR Console | | |
| Firewall Management | | |
| Email Gateway | | |
| Threat Intel Feeds | | |
| Case Management | | |

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },

    # =========================================================================
    # SOIs (3)
    # =========================================================================
    {
        "name": "Alert Triage SOI",
        "document_type": "SOI",
        "collection": "Standard Operating Instructions",
        "description": "Standard operating instruction for triaging security alerts with decision tree and escalation paths.",
        "tags": ["NIST-CSF-2.0", "SOC-CMM"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "SOI-TRI-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "alert_source", "var_type": "string", "required": False, "default_value": "Elastic SIEM", "description": "Alert source system"},
            {"name": "triage_steps", "var_type": "text", "required": False, "default_value": "", "description": "Additional triage steps"},
            {"name": "classification_criteria", "var_type": "text", "required": False, "default_value": "", "description": "Alert classification criteria"},
        ],
        "content": """# {{ doc_id }} - Alert Triage SOI

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |
| **Alert Source** | {{ alert_source }} |

---

## Objective

Provide step-by-step instructions for triaging security alerts from {{ alert_source }}, enabling consistent classification and appropriate response.

## Prerequisites

- Access to {{ alert_source }} console
- Access to threat intelligence platform
- Access to case management system
- Understanding of network topology and asset inventory

## Triage Workflow

### Step 1: Alert Review
1. Open the alert in {{ alert_source }}
2. Note the alert rule name, severity, and timestamp
3. Identify source IP, destination IP, user, and host

### Step 2: Context Gathering
1. Check if source/destination are known internal assets
2. Review user account activity for anomalies
3. Check for related alerts within the last 24 hours
4. Query threat intelligence for any IOCs

### Step 3: Decision Tree

```
Alert Received
    |
    v
Known False Positive? --YES--> Document & Close
    |
    NO
    v
Matches Known IOC? --YES--> Escalate (P2+)
    |
    NO
    v
Suspicious Behavior? --YES--> Investigate Further
    |                              |
    NO                             v
    v                         Confirmed Malicious? --YES--> Escalate
    |                              |
Close as Benign                    NO
                                   v
                              Close with Notes
```

{{ classification_criteria }}

### Step 4: Classification

| Classification | Action | Documentation |
|---------------|--------|---------------|
| **True Positive** | Escalate per SOP | Full investigation notes |
| **Benign True Positive** | Close, document context | Brief note explaining legitimacy |
| **False Positive** | Close, request tuning | Tuning recommendation |
| **Inconclusive** | Escalate to L2 | All gathered evidence |

{{ triage_steps }}

## Escalation Path

1. **L1 > L2**: Alert requires deeper investigation or correlation
2. **L2 > L3/IR**: Confirmed incident requiring response actions
3. **Any > SOC Lead**: Multiple correlated alerts or uncertainty

## Expected Outputs

- Alert classified and documented in case management
- Escalation initiated if required
- False positive tuning request submitted if applicable
- Metrics updated (triage time, classification)

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
    {
        "name": "Phishing Response SOI",
        "document_type": "SOI",
        "collection": "Standard Operating Instructions",
        "description": "Standard operating instruction for analyzing and responding to reported phishing emails.",
        "tags": ["SANS-IR", "NIST-800-61"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "SOI-PHI-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "email_gateway_tool", "var_type": "string", "required": False, "default_value": "", "description": "Email security gateway tool"},
            {"name": "sandbox_url", "var_type": "string", "required": False, "default_value": "", "description": "Malware sandbox URL"},
            {"name": "blocklist_tool", "var_type": "string", "required": False, "default_value": "", "description": "URL/domain blocklist tool"},
        ],
        "content": """# {{ doc_id }} - Phishing Response SOI

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |

---

## Objective

Provide step-by-step instructions for analyzing reported phishing emails, containing the threat, and extracting indicators of compromise.

## Prerequisites

- Access to email gateway: {{ email_gateway_tool }}
- Access to sandbox: {{ sandbox_url }}
- Access to blocklist tool: {{ blocklist_tool }}
- Email header analysis capability

## Analysis Steps

### Step 1: Email Header Analysis
1. Extract full email headers from the reported message
2. Verify sender address and SPF/DKIM/DMARC results
3. Identify the originating IP address and mail servers
4. Check for header anomalies (spoofed From, mismatched Reply-To)

### Step 2: Content Analysis
1. Review email body for social engineering indicators
2. Identify all URLs (hover, do not click)
3. Check for attachments - note file names, types, and sizes
4. Look for urgency language, impersonation, or brand spoofing

### Step 3: URL/Attachment Analysis
1. Submit URLs to sandbox for analysis: {{ sandbox_url }}
2. Submit attachments to sandbox for detonation
3. Check URLs against threat intelligence and reputation services
4. Verify if landing pages are credential harvesting forms

### Step 4: Scope Assessment
1. Search email gateway for similar messages to other recipients
2. Determine total number of recipients who received the email
3. Identify any users who clicked links or opened attachments
4. Check for any credential submissions on phishing pages

## Containment Actions

1. **Block sender** in email gateway: {{ email_gateway_tool }}
2. **Block URLs/domains** in web proxy: {{ blocklist_tool }}
3. **Quarantine** all copies of the phishing email
4. **Reset credentials** for any users who submitted credentials
5. **Block IOCs** (IPs, domains, hashes) at perimeter

## User Notification

- Notify affected users who received the email
- Provide guidance on what to do if they interacted with it
- Remind about phishing reporting procedures
- Send organization-wide advisory if campaign is widespread

## IOC Extraction

Document all indicators:
- Sender email address(es)
- Sender IP address(es)
- Malicious URLs
- Malicious domains
- Attachment hashes (MD5, SHA-256)
- Subject line patterns

## Reporting

1. Document all findings in case management system
2. Update IOC database with extracted indicators
3. Submit phishing kit/infrastructure to threat intel sharing platforms
4. Generate metrics (time to detect, scope, user interaction rate)

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
    {
        "name": "Malware Analysis SOI",
        "document_type": "SOI",
        "collection": "Standard Operating Instructions",
        "description": "Standard operating instruction for static and dynamic malware analysis with MITRE ATT&CK mapping.",
        "tags": ["MITRE-ATT&CK", "NIST-800-61"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "SOI-MAL-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "sandbox_environment", "var_type": "string", "required": False, "default_value": "", "description": "Sandbox environment details"},
            {"name": "analysis_tools", "var_type": "string", "required": False, "default_value": "", "description": "Available analysis tools"},
            {"name": "submission_portal", "var_type": "string", "required": False, "default_value": "", "description": "Sample submission portal URL"},
        ],
        "content": """# {{ doc_id }} - Malware Analysis SOI

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |

---

## Objective

Provide instructions for performing static and dynamic analysis of suspected malware samples, extracting IOCs, and mapping behaviors to the MITRE ATT&CK framework.

## Prerequisites

- Isolated analysis environment: {{ sandbox_environment }}
- Analysis tools: {{ analysis_tools }}
- Sample submission portal: {{ submission_portal }}
- MITRE ATT&CK Navigator access

## Static Analysis

### Step 1: Initial Triage
1. Calculate file hashes (MD5, SHA-1, SHA-256)
2. Check hashes against VirusTotal and other reputation services
3. Identify file type using magic bytes (not extension)
4. Note file size, compilation timestamp, and packer detection

### Step 2: String Analysis
1. Extract ASCII and Unicode strings
2. Look for URLs, IP addresses, domains, email addresses
3. Identify API function names (especially suspicious ones)
4. Note registry keys, file paths, and mutex names

### Step 3: PE Analysis (if applicable)
1. Review import table for suspicious API calls
2. Check section names and entropy (packed sections > 7.0)
3. Review resources for embedded payloads
4. Verify digital signature validity

## Dynamic Analysis

### Step 4: Sandbox Execution
1. Configure sandbox environment: {{ sandbox_environment }}
2. Take pre-execution snapshot
3. Execute sample and monitor for 5-10 minutes minimum
4. Capture all network traffic during execution

### Step 5: Behavioral Analysis
1. Document process creation tree
2. Record file system modifications (created, modified, deleted)
3. Note registry modifications
4. Identify network connections (DNS queries, HTTP/HTTPS, C2)
5. Check for persistence mechanisms
6. Monitor for privilege escalation attempts

## IOC Extraction

| IOC Type | Value | Context |
|----------|-------|---------|
| File Hash (SHA-256) | | |
| Mutex | | |
| C2 Domain | | |
| C2 IP | | |
| Dropped File | | |
| Registry Key | | |

## MITRE ATT&CK Mapping

| Tactic | Technique | Technique ID | Evidence |
|--------|-----------|-------------|----------|
| Initial Access | | | |
| Execution | | | |
| Persistence | | | |
| Defense Evasion | | | |
| Command & Control | | | |

## Report

Document findings including:
- Executive summary of malware capabilities
- Detailed technical analysis
- Complete IOC list
- MITRE ATT&CK mapping
- Recommended detection signatures
- Containment recommendations

## Containment Recommendations

1. Block all identified IOCs at perimeter
2. Deploy detection signatures to EDR/SIEM
3. Scan environment for indicators of compromise
4. Isolate any confirmed infected systems

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },

    # =========================================================================
    # WIs (3)
    # =========================================================================
    {
        "name": "IOC Blocking Work Instruction",
        "document_type": "WI",
        "collection": "Work Instructions",
        "description": "Work instruction for blocking indicators of compromise across security tools.",
        "tags": ["MITRE-ATT&CK"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "WI-IOC-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "firewall_tool", "var_type": "string", "required": False, "default_value": "", "description": "Firewall management tool"},
            {"name": "edr_tool", "var_type": "string", "required": False, "default_value": "", "description": "EDR platform"},
            {"name": "dns_filter_tool", "var_type": "string", "required": False, "default_value": "", "description": "DNS filtering tool"},
            {"name": "change_management_required", "var_type": "string", "required": False, "default_value": "Yes - for production firewall changes", "description": "Change management requirements"},
        ],
        "content": """# {{ doc_id }} - IOC Blocking Work Instruction

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |
| **Change Management** | {{ change_management_required }} |

---

## Objective

Step-by-step instructions for blocking malicious indicators of compromise (IOCs) across firewall, EDR, and DNS filtering tools.

## Scope

Covers blocking of IP addresses, domains, URLs, and file hashes across the security stack.

## Prerequisites

- Verified IOCs from investigation (confirmed malicious)
- Appropriate access to security tools
- Change management ticket (if required): {{ change_management_required }}

## IP Address Blocking

### Firewall: {{ firewall_tool }}
1. Log into {{ firewall_tool }} management console
2. Navigate to security policy / blocklist section
3. Add IP address(es) to the block list
4. Set rule action to "Block" with logging enabled
5. Apply changes and verify rule is active
6. Document: IP, ticket number, expiration date

### EDR: {{ edr_tool }}
1. Open {{ edr_tool }} console
2. Navigate to network isolation / IOC management
3. Add IP to blocklist with description and case reference
4. Verify block is deployed to all endpoints

## Domain/URL Blocking

### DNS Filter: {{ dns_filter_tool }}
1. Access {{ dns_filter_tool }} administration
2. Add domain(s) to blocklist category
3. Set action to block with custom block page
4. Verify resolution returns block page

### Web Proxy
1. Add URL/domain to proxy block category
2. Enable SSL inspection if HTTPS domain
3. Verify block is effective from test workstation

## File Hash Blocking

### EDR: {{ edr_tool }}
1. Navigate to hash blocklist / prevention policies
2. Add SHA-256 hash(es) with description
3. Set action to "Block and Quarantine"
4. Deploy policy update to all endpoint groups
5. Verify hash is blocked on test endpoint

## Verification

After implementing blocks, verify:
- [ ] Firewall rules active and logging
- [ ] DNS queries for blocked domains return expected response
- [ ] Web proxy blocks access to URLs
- [ ] EDR blocks execution of hashed files
- [ ] No business impact from blocks (check for false positives)

## Rollback

If a block causes business impact:
1. Immediately remove the block from the affected tool
2. Notify the investigation team
3. Document the false positive
4. Update IOC quality rating in threat intel platform

## Documentation

Record in case management:
- IOC value and type
- Where blocked (which tools)
- Date/time of block implementation
- Expiration/review date
- Associated case/ticket number

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
    {
        "name": "Log Source Onboarding Work Instruction",
        "document_type": "WI",
        "collection": "Work Instructions",
        "description": "Work instruction for onboarding new log sources into the SIEM platform.",
        "tags": ["NIST-CSF-2.0", "SOC-CMM"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "WI-LOG-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "siem_platform", "var_type": "string", "required": False, "default_value": "Elastic SIEM", "description": "Target SIEM platform"},
            {"name": "log_formats", "var_type": "string", "required": False, "default_value": "Syslog, JSON, CEF, Windows Event Log", "description": "Supported log formats"},
            {"name": "retention_days", "var_type": "string", "required": False, "default_value": "90", "description": "Default log retention in days"},
        ],
        "content": """# {{ doc_id }} - Log Source Onboarding Work Instruction

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |
| **SIEM Platform** | {{ siem_platform }} |

---

## Objective

Step-by-step instructions for onboarding new log sources into {{ siem_platform }}, including collection, parsing, validation, and alert rule setup.

## Log Source Identification

Before onboarding, document:
- Log source name and type
- Log format: {{ log_formats }}
- Expected event volume (EPS)
- Data classification level
- Retention requirement: {{ retention_days }} days
- Business owner and technical contact

## Collection Method

| Method | Use Case | Configuration |
|--------|----------|---------------|
| Agent (Elastic Agent/Beats) | Endpoint logs, application logs | Deploy agent, configure integration |
| Syslog | Network devices, firewalls | Configure syslog forwarding to collector |
| API | Cloud services, SaaS applications | Configure API polling integration |
| File | Legacy systems, batch processing | Configure filebeat/logstash input |

## Parser Configuration

1. Identify log format and structure
2. Create or configure ingest pipeline / parser
3. Map fields to ECS (Elastic Common Schema) where applicable
4. Test parser with sample log events
5. Validate field extraction accuracy

## Validation

- [ ] Logs are arriving in {{ siem_platform }}
- [ ] Parsing is correct (fields extracted properly)
- [ ] Timestamp is accurate and in correct timezone
- [ ] No data loss or truncation
- [ ] Volume matches expected EPS
- [ ] Retention policy applied

## Alert Rules Setup

1. Review available detection rules for the log source type
2. Enable relevant pre-built rules
3. Tune thresholds based on baseline activity
4. Create custom rules for organization-specific use cases
5. Test alert generation with known-good triggers

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
    {
        "name": "SIEM Query & Investigation Work Instruction",
        "document_type": "WI",
        "collection": "Work Instructions",
        "description": "Work instruction for SIEM query techniques and investigation workflows.",
        "tags": ["SOC-CMM"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "WI-QRY-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "siem_platform", "var_type": "string", "required": False, "default_value": "Elastic SIEM", "description": "SIEM platform"},
            {"name": "query_examples", "var_type": "text", "required": False, "default_value": "", "description": "Additional query examples"},
        ],
        "content": """# {{ doc_id }} - SIEM Query & Investigation Work Instruction

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |
| **SIEM Platform** | {{ siem_platform }} |

---

## Objective

Provide query syntax reference, common investigation queries, and correlation techniques for {{ siem_platform }}.

## Query Syntax Reference

### KQL (Kibana Query Language)
```
# Field matching
event.action: "login" AND event.outcome: "failure"

# Wildcard
source.ip: 192.168.1.*

# Range
@timestamp >= "2024-01-01" AND @timestamp < "2024-02-01"

# Boolean
(event.category: "authentication") AND NOT (source.ip: "10.0.0.0/8")
```

### Lucene
```
# Phrase search
message: "failed password"

# Proximity
message: "password reset"~5

# Fuzzy
user.name: admin~2
```

## Common Investigation Queries

### Authentication Anomalies
```
event.category: "authentication" AND event.outcome: "failure"
| stats count by source.ip, user.name
| where count > 10
```

### Suspicious Process Execution
```
event.category: "process" AND process.name: ("powershell.exe" OR "cmd.exe" OR "wscript.exe")
AND process.command_line: ("*-enc*" OR "*downloadstring*" OR "*invoke-expression*")
```

### Network Connections to Rare Destinations
```
event.category: "network" AND NOT destination.ip: ("10.0.0.0/8" OR "172.16.0.0/12" OR "192.168.0.0/16")
| stats count by destination.ip, destination.port
| where count < 5
```

### Lateral Movement Indicators
```
event.category: "authentication" AND event.type: "start"
AND source.ip: "10.0.0.0/8" AND destination.ip: "10.0.0.0/8"
AND NOT source.ip: destination.ip
```

{{ query_examples }}

## Correlation Techniques

1. **Time-based**: Group events within a time window from the same source
2. **Entity-based**: Correlate by user, host, or IP across event types
3. **Kill chain**: Map events to ATT&CK stages for attack reconstruction
4. **Statistical**: Identify outliers in normally distributed activity

## Performance Tips

- Always specify a time range to limit search scope
- Use specific field queries instead of full-text search
- Filter on indexed fields first, then apply text searches
- Use aggregations for summary views rather than raw events
- Save commonly used queries as saved searches

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },

    # =========================================================================
    # KB Articles (3)
    # =========================================================================
    {
        "name": "Common Alert Types KB",
        "document_type": "KB",
        "collection": "Knowledge Base",
        "description": "Knowledge base article documenting common security alert types, their meaning, and response guidance.",
        "tags": ["MITRE-ATT&CK"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "KB-ALT-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "alert_categories", "var_type": "text", "required": False, "default_value": "", "description": "Additional alert category details"},
        ],
        "content": """# {{ doc_id }} - Common Alert Types Knowledge Base

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |

---

## Overview

This knowledge base article provides reference information on common security alert types encountered in SOC operations, including descriptions, typical causes, and recommended response actions.

## Alert Categories

| Category | MITRE Tactic | Typical Severity | FP Rate |
|----------|-------------|-----------------|---------|
| Authentication Anomalies | Credential Access | Medium-High | Medium |
| Malware Detection | Execution | High-Critical | Low |
| Network Anomalies | Command & Control | Medium | High |
| Policy Violations | N/A | Low-Medium | Medium |
| Data Exfiltration | Exfiltration | High-Critical | Low |
| Privilege Escalation | Privilege Escalation | High | Low |
| Lateral Movement | Lateral Movement | High | Medium |

### Authentication Anomalies
- **Brute Force**: Multiple failed login attempts from a single source
- **Credential Stuffing**: Failed logins across multiple accounts from distributed sources
- **Impossible Travel**: Successful logins from geographically impossible locations
- **Off-hours Login**: Authentication outside normal business hours

### Malware Detection
- **Known Malware**: Signature-based detection of known malicious files
- **Behavioral Detection**: Suspicious process behavior matching malware patterns
- **Fileless Malware**: Script-based attacks using legitimate tools (LOLBins)
- **Ransomware**: File encryption behavior, ransom note creation

### Network Anomalies
- **Beaconing**: Regular periodic connections to external hosts
- **DNS Tunneling**: Unusually long or frequent DNS queries
- **Port Scanning**: Connection attempts to multiple ports on a target
- **C2 Communication**: Traffic matching known command-and-control patterns

{{ alert_categories }}

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
    {
        "name": "Threat Actor Profile KB",
        "document_type": "KB",
        "collection": "Knowledge Base",
        "description": "Knowledge base template for documenting threat actor profiles including TTPs, campaigns, and IOCs.",
        "tags": ["MITRE-ATT&CK"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "KB-TA-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "actor_name", "var_type": "string", "required": True, "default_value": "", "description": "Threat actor name"},
            {"name": "aliases", "var_type": "string", "required": False, "default_value": "", "description": "Known aliases"},
            {"name": "motivation", "var_type": "string", "required": False, "default_value": "", "description": "Actor motivation (espionage, financial, etc.)"},
            {"name": "target_sectors", "var_type": "string", "required": False, "default_value": "", "description": "Target industry sectors"},
            {"name": "ttps", "var_type": "text", "required": False, "default_value": "", "description": "Tactics, techniques, and procedures"},
            {"name": "iocs", "var_type": "text", "required": False, "default_value": "", "description": "Known indicators of compromise"},
            {"name": "campaigns", "var_type": "text", "required": False, "default_value": "", "description": "Known campaigns"},
        ],
        "content": """# {{ doc_id }} - Threat Actor Profile: {{ actor_name }}

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |

---

## Actor Overview

| Attribute | Detail |
|-----------|--------|
| **Name** | {{ actor_name }} |
| **Aliases** | {{ aliases }} |
| **Motivation** | {{ motivation }} |
| **Target Sectors** | {{ target_sectors }} |
| **Confidence** | |
| **First Seen** | |
| **Last Active** | |

## TTPs (MITRE ATT&CK)

| Tactic | Technique | ID | Description |
|--------|-----------|-----|-------------|
| | | | |

{{ ttps }}

## Known Campaigns

{{ campaigns }}

## IOC Summary

| IOC Type | Value | First Seen | Last Seen | Confidence |
|----------|-------|------------|-----------|------------|
| | | | | |

{{ iocs }}

## Detection Recommendations

1. Deploy detection rules covering known TTPs
2. Monitor for IOCs listed above
3. Review alerts matching actor's target profile
4. Enable enhanced logging for targeted systems

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
    {
        "name": "Tool Configuration Guide KB",
        "document_type": "KB",
        "collection": "Knowledge Base",
        "description": "Knowledge base template for documenting security tool configuration, integration, and troubleshooting.",
        "tags": ["SOC-CMM"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "KB-TOOL-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "tool_name", "var_type": "string", "required": True, "default_value": "", "description": "Tool name"},
            {"name": "tool_version", "var_type": "string", "required": False, "default_value": "", "description": "Tool version"},
            {"name": "purpose", "var_type": "string", "required": False, "default_value": "", "description": "Tool purpose"},
            {"name": "configuration_steps", "var_type": "text", "required": False, "default_value": "", "description": "Configuration steps"},
            {"name": "troubleshooting_items", "var_type": "text", "required": False, "default_value": "", "description": "Troubleshooting guide"},
        ],
        "content": """# {{ doc_id }} - Tool Configuration Guide: {{ tool_name }}

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |
| **Tool** | {{ tool_name }} |
| **Tool Version** | {{ tool_version }} |
| **Purpose** | {{ purpose }} |

---

## Overview

Configuration and administration guide for {{ tool_name }} ({{ tool_version }}).

**Purpose**: {{ purpose }}

## Prerequisites

- Administrative access to {{ tool_name }}
- Network connectivity to required services
- Valid license/subscription

## Configuration

{{ configuration_steps }}

## Integration

| Integration | Purpose | Protocol | Status |
|------------|---------|----------|--------|
| SIEM | Log forwarding | Syslog/API | |
| SOAR | Automated response | REST API | |
| Ticketing | Case creation | API | |

## Troubleshooting

{{ troubleshooting_items }}

| Issue | Possible Cause | Resolution |
|-------|---------------|------------|
| Service not starting | Configuration error | Check logs, validate config |
| No data received | Network connectivity | Verify firewall rules, test connectivity |
| High resource usage | Volume spike | Check EPS, tune retention |

## Maintenance

- **Backup**: Schedule regular configuration backups
- **Updates**: Follow vendor update schedule
- **Health Checks**: Monitor service health daily
- **License**: Track license expiration and usage

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },

    # =========================================================================
    # IRPs (2)
    # =========================================================================
    {
        "name": "Ransomware Incident Response Plan",
        "document_type": "IRP",
        "collection": "Incident Response Plans",
        "description": "Incident response plan for ransomware attacks following NIST 800-61 and SANS IR phases.",
        "tags": ["NIST-800-61", "SANS-IR"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "IRP-RAN-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "classification", "var_type": "string", "required": False, "default_value": "CONFIDENTIAL", "description": "Document classification level"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "approved_by", "var_type": "string", "required": False, "default_value": "", "description": "Approval authority"},
            {"name": "ir_team_contacts", "var_type": "text", "required": False, "default_value": "", "description": "IR team contact list"},
            {"name": "backup_contacts", "var_type": "text", "required": False, "default_value": "", "description": "Backup/recovery team contacts"},
            {"name": "legal_contacts", "var_type": "text", "required": False, "default_value": "", "description": "Legal team contacts"},
        ],
        "content": """# {{ doc_id }} - Ransomware Incident Response Plan

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Classification** | {{ classification }} |
| **Author** | {{ author }} |
| **Approved By** | {{ approved_by }} |

---

## 1. Purpose

This plan provides structured response procedures for ransomware incidents, following NIST SP 800-61 and SANS Incident Response methodology.

## 2. Roles & Responsibilities

| Role | Responsibility | Contact |
|------|---------------|---------|
| Incident Commander | Overall response coordination | |
| IR Lead | Technical investigation and containment | |
| SOC Analysts | Detection, monitoring, evidence collection | |
| IT Operations | System isolation, recovery | |
| Legal | Regulatory obligations, law enforcement | |
| Communications | Internal/external messaging | |

{{ ir_team_contacts }}

## 3. Detection Indicators

- File encryption activity across multiple files/directories
- Ransom notes appearing on systems
- Unusual file extension changes (.encrypted, .locked, etc.)
- Volume Shadow Copy deletion attempts
- Mass file modification events in short timeframes
- Known ransomware process names or hashes
- C2 beacon activity to known ransomware infrastructure

## 4. Response Phases (SANS)

### Phase 1: Identification
1. Confirm ransomware infection (verify it's not a false alarm)
2. Identify the ransomware variant (ransom note, file extensions, behavior)
3. Determine initial infection vector
4. Assess scope of encryption
5. Identify patient zero and timeline

### Phase 2: Containment
1. **Immediate**: Isolate affected systems from network
2. Disable shared drives and network shares
3. Block known C2 domains/IPs at perimeter
4. Disable compromised accounts
5. Preserve evidence before any recovery actions
6. **Do NOT** power off systems (preserves volatile evidence)
7. **Do NOT** pay ransom without executive and legal approval

### Phase 3: Eradication
1. Identify and remove ransomware from all affected systems
2. Remove persistence mechanisms
3. Patch vulnerability used for initial access
4. Reset all potentially compromised credentials
5. Scan environment for additional compromise indicators

### Phase 4: Recovery
1. Restore systems from clean backups (verify backup integrity first)
2. Rebuild systems that cannot be restored
3. Restore data in priority order (critical business functions first)
4. Monitor recovered systems for re-infection
5. Gradually restore network connectivity

**Backup Contacts**: {{ backup_contacts }}

## 5. Communication Plan

| Audience | When | Channel | Responsible |
|----------|------|---------|-------------|
| Executive leadership | Immediately on confirmation | Phone/meeting | Incident Commander |
| All employees | Within 4 hours | Email/intranet | Communications |
| Customers (if affected) | Per contractual/regulatory | Email/portal | Communications + Legal |
| Law enforcement | If warranted | In-person/phone | Legal |
| Regulators | Per requirements | Formal notification | Legal |

## 6. Evidence Preservation

- Memory dumps of affected systems
- Ransom notes (all variants found)
- Encrypted file samples
- Ransomware binary/payload
- Network traffic captures
- System and security logs
- Email/phishing artifacts (if applicable)

## 7. Post-Incident Review

Conduct within 1 week of incident closure:
- Timeline reconstruction
- Root cause analysis
- Lessons learned
- Action items with owners and deadlines
- Update this plan based on findings

**Legal Contacts**: {{ legal_contacts }}

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
    {
        "name": "Data Breach Response Plan",
        "document_type": "IRP",
        "collection": "Incident Response Plans",
        "description": "Incident response plan for data breaches including regulatory notification requirements.",
        "tags": ["ISO-27035", "NIST-800-61"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "IRP-DBR-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "classification", "var_type": "string", "required": False, "default_value": "CONFIDENTIAL", "description": "Document classification level"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "approved_by", "var_type": "string", "required": False, "default_value": "", "description": "Approval authority"},
            {"name": "dpo_contact", "var_type": "string", "required": False, "default_value": "", "description": "Data Protection Officer contact"},
            {"name": "legal_contacts", "var_type": "text", "required": False, "default_value": "", "description": "Legal team contacts"},
            {"name": "notification_requirements", "var_type": "text", "required": False, "default_value": "", "description": "Regulatory notification requirements"},
        ],
        "content": """# {{ doc_id }} - Data Breach Response Plan

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Classification** | {{ classification }} |
| **Author** | {{ author }} |
| **Approved By** | {{ approved_by }} |
| **DPO Contact** | {{ dpo_contact }} |

---

## 1. Purpose

This plan provides structured response procedures for data breach incidents, including assessment, containment, notification requirements, and forensic investigation aligned with ISO 27035 and NIST SP 800-61.

## 2. Breach Classification

| Level | Description | Examples | Notification Required |
|-------|-------------|----------|----------------------|
| **Level 1** | Minor - limited data, low sensitivity | Employee contact info | Internal only |
| **Level 2** | Moderate - personal data affected | Customer PII, email addresses | DPO assessment required |
| **Level 3** | Severe - sensitive/regulated data | Financial data, health records | Regulatory notification likely |
| **Level 4** | Critical - mass breach, high sensitivity | Payment cards, SSN, credentials | Mandatory regulatory notification |

## 3. Roles & Responsibilities

| Role | Responsibility |
|------|---------------|
| Incident Commander | Overall coordination, executive briefing |
| DPO | Data impact assessment, regulatory guidance |
| Legal | Notification obligations, liability assessment |
| IR Team | Technical investigation and containment |
| Communications | Public statements, customer notifications |
| IT Operations | System remediation, access controls |

## 4. Detection & Assessment

1. Confirm data breach has occurred
2. Identify type and sensitivity of data exposed
3. Determine number of affected records/individuals
4. Identify breach vector and root cause
5. Assess ongoing risk (is breach still active?)
6. Document all findings for regulatory reporting

## 5. Containment

1. Stop the breach - close the vulnerability, revoke access
2. Preserve evidence before remediation
3. Reset compromised credentials
4. Isolate affected systems
5. Implement additional monitoring for further exposure

## 6. Notification Requirements

{{ notification_requirements }}

| Regulation | Timeline | Authority | Threshold |
|-----------|----------|-----------|-----------|
| GDPR | 72 hours | Supervisory Authority | Risk to individuals |
| CCPA | Without unreasonable delay | California AG | 500+ residents |
| HIPAA | 60 days | HHS OCR | Unsecured PHI |
| PCI DSS | Immediately | Card brands | Cardholder data |

## 7. Communication Templates

### Regulatory Notification
Include: nature of breach, categories of data, approximate number of individuals, likely consequences, measures taken/proposed, DPO contact information.

### Individual Notification
Include: plain language description, type of data involved, what we're doing about it, what they can do, contact for questions.

## 8. Forensic Investigation

1. Engage forensic team (internal or external)
2. Preserve all relevant logs and evidence
3. Determine full scope of data access
4. Identify all affected data records
5. Document chain of custody for all evidence
6. Prepare forensic report for legal and regulatory purposes

## 9. Regulatory Reporting

Coordinate with Legal and DPO:
{{ legal_contacts }}

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },

    # =========================================================================
    # AAR (1)
    # =========================================================================
    {
        "name": "Post-Incident After-Action Report",
        "document_type": "AAR",
        "collection": "After-Action Reports",
        "description": "After-action report template for post-incident review, lessons learned, and improvement recommendations.",
        "tags": ["NIST-800-61", "SANS-IR", "ISO-27035"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "AAR-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "classification", "var_type": "string", "required": False, "default_value": "CONFIDENTIAL", "description": "Document classification level"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "incident_id", "var_type": "string", "required": True, "default_value": "", "description": "Related incident ID"},
            {"name": "incident_title", "var_type": "string", "required": True, "default_value": "", "description": "Incident title"},
            {"name": "incident_date", "var_type": "string", "required": True, "default_value": "", "description": "Incident date"},
            {"name": "resolution_date", "var_type": "string", "required": False, "default_value": "", "description": "Resolution date"},
            {"name": "severity", "var_type": "string", "required": False, "default_value": "", "description": "Incident severity"},
            {"name": "lead_analyst", "var_type": "string", "required": False, "default_value": "", "description": "Lead analyst name"},
            {"name": "participants", "var_type": "text", "required": False, "default_value": "", "description": "AAR meeting participants"},
            {"name": "executive_summary", "var_type": "text", "required": False, "default_value": "", "description": "Executive summary"},
            {"name": "timeline_events", "var_type": "text", "required": False, "default_value": "", "description": "Timeline of events"},
            {"name": "findings", "var_type": "text", "required": False, "default_value": "", "description": "Key findings"},
            {"name": "recommendations", "var_type": "text", "required": False, "default_value": "", "description": "Improvement recommendations"},
        ],
        "content": """# {{ doc_id }} - After-Action Report: {{ incident_title }}

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Classification** | {{ classification }} |
| **Author** | {{ author }} |
| **Incident ID** | {{ incident_id }} |
| **Incident Date** | {{ incident_date }} |
| **Resolution Date** | {{ resolution_date }} |
| **Severity** | {{ severity }} |
| **Lead Analyst** | {{ lead_analyst }} |

**Participants**: {{ participants }}

---

## 1. Executive Summary

{{ executive_summary }}

## 2. Incident Overview

| Attribute | Detail |
|-----------|--------|
| Incident ID | {{ incident_id }} |
| Title | {{ incident_title }} |
| Date Detected | {{ incident_date }} |
| Date Resolved | {{ resolution_date }} |
| Severity | {{ severity }} |
| Category | |
| Attack Vector | |
| Systems Affected | |
| Data Impact | |

## 3. Timeline

| Date/Time | Event | Actor | Notes |
|-----------|-------|-------|-------|
| | | | |

{{ timeline_events }}

## 4. What Went Well

-
-
-

## 5. Areas for Improvement

-
-
-

## 6. Findings

{{ findings }}

## 7. Recommendations

| # | Recommendation | Priority | Owner | Deadline | Status |
|---|---------------|----------|-------|----------|--------|
| 1 | | | | | |
| 2 | | | | | |
| 3 | | | | | |

{{ recommendations }}

## 8. Action Items

| # | Action | Owner | Due Date | Status |
|---|--------|-------|----------|--------|
| 1 | | | | Pending |
| 2 | | | | Pending |
| 3 | | | | Pending |

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },

    # =========================================================================
    # Threat Advisory (1)
    # =========================================================================
    {
        "name": "Threat Advisory",
        "document_type": "THREAT_ADVISORY",
        "collection": "Threat Intelligence",
        "description": "Threat advisory template for communicating emerging threats, IOCs, and recommended mitigations.",
        "tags": ["MITRE-ATT&CK"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "TA-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "classification", "var_type": "string", "required": False, "default_value": "TLP:AMBER", "description": "Document classification / TLP level"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "advisory_title", "var_type": "string", "required": True, "default_value": "", "description": "Advisory title"},
            {"name": "severity", "var_type": "string", "required": False, "default_value": "HIGH", "description": "Advisory severity"},
            {"name": "date_issued", "var_type": "string", "required": False, "default_value": "", "description": "Date issued"},
            {"name": "tlp_level", "var_type": "string", "required": False, "default_value": "TLP:AMBER", "description": "Traffic Light Protocol level"},
            {"name": "affected_systems", "var_type": "text", "required": False, "default_value": "", "description": "Affected systems and versions"},
            {"name": "threat_description", "var_type": "text", "required": False, "default_value": "", "description": "Detailed threat description"},
            {"name": "iocs", "var_type": "text", "required": False, "default_value": "", "description": "Indicators of compromise"},
            {"name": "mitre_techniques", "var_type": "text", "required": False, "default_value": "", "description": "MITRE ATT&CK techniques"},
            {"name": "mitigations", "var_type": "text", "required": False, "default_value": "", "description": "Recommended mitigations"},
        ],
        "content": """# {{ doc_id }} - Threat Advisory: {{ advisory_title }}

| Field | Value |
|-------|-------|
| **Advisory ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Classification** | {{ classification }} |
| **TLP** | {{ tlp_level }} |
| **Severity** | {{ severity }} |
| **Date Issued** | {{ date_issued }} |
| **Author** | {{ author }} |

---

## Threat Overview

{{ threat_description }}

## Affected Systems

{{ affected_systems }}

## Technical Analysis

### Attack Flow

1. **Initial Access**:
2. **Execution**:
3. **Persistence**:
4. **Impact**:

## Indicators of Compromise

| IOC Type | Value | Context |
|----------|-------|---------|
| | | |

{{ iocs }}

## MITRE ATT&CK Mapping

| Tactic | Technique | ID | Description |
|--------|-----------|-----|-------------|
| | | | |

{{ mitre_techniques }}

## Mitigations

{{ mitigations }}

### Immediate Actions
1.
2.
3.

### Long-term Recommendations
1.
2.
3.

## Detection Signatures

```
# Add SIEM/IDS detection rules here
```

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },

    # =========================================================================
    # Detection Rule Documentation (1)
    # =========================================================================
    {
        "name": "Detection Rule Documentation",
        "document_type": "DETECTION_RULE",
        "collection": "Detection Engineering",
        "description": "Documentation template for detection rules including MITRE mapping, data requirements, and test cases.",
        "tags": ["MITRE-ATT&CK"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "DET-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "rule_name", "var_type": "string", "required": True, "default_value": "", "description": "Detection rule name"},
            {"name": "rule_id", "var_type": "string", "required": False, "default_value": "", "description": "Rule ID in SIEM"},
            {"name": "severity", "var_type": "string", "required": False, "default_value": "medium", "description": "Rule severity"},
            {"name": "mitre_technique", "var_type": "string", "required": False, "default_value": "", "description": "MITRE ATT&CK technique ID"},
            {"name": "mitre_tactic", "var_type": "string", "required": False, "default_value": "", "description": "MITRE ATT&CK tactic"},
            {"name": "data_sources", "var_type": "string", "required": False, "default_value": "", "description": "Required data sources"},
            {"name": "detection_logic", "var_type": "text", "required": False, "default_value": "", "description": "Detection logic description"},
            {"name": "query", "var_type": "text", "required": False, "default_value": "", "description": "Detection query/rule"},
            {"name": "false_positive_rate", "var_type": "string", "required": False, "default_value": "Medium", "description": "Expected false positive rate"},
            {"name": "test_cases", "var_type": "text", "required": False, "default_value": "", "description": "Test cases for validation"},
        ],
        "content": """# {{ doc_id }} - Detection Rule: {{ rule_name }}

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |
| **Rule ID** | {{ rule_id }} |
| **Severity** | {{ severity }} |
| **False Positive Rate** | {{ false_positive_rate }} |

---

## Rule Metadata

| Attribute | Value |
|-----------|-------|
| Name | {{ rule_name }} |
| Rule ID | {{ rule_id }} |
| Severity | {{ severity }} |
| Status | Active |
| Created | |
| Last Updated | |

## Description

{{ detection_logic }}

## MITRE ATT&CK Mapping

| Attribute | Value |
|-----------|-------|
| **Tactic** | {{ mitre_tactic }} |
| **Technique** | {{ mitre_technique }} |
| **Sub-technique** | |

## Data Requirements

**Required Data Sources**: {{ data_sources }}

| Data Source | Fields Required | Index Pattern |
|-------------|----------------|---------------|
| | | |

## Detection Logic

{{ detection_logic }}

## Query / Sigma Rule

```
{{ query }}
```

## Test Cases

{{ test_cases }}

| # | Test Description | Expected Result | Status |
|---|-----------------|-----------------|--------|
| 1 | True positive trigger | Alert generated | |
| 2 | Benign activity | No alert | |
| 3 | Edge case | | |

## False Positive Guidance

**Expected FP Rate**: {{ false_positive_rate }}

Common false positive scenarios:
-
-

Tuning recommendations:
-
-

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },

    # =========================================================================
    # Runbook (1)
    # =========================================================================
    {
        "name": "Operational Runbook",
        "document_type": "RUNBOOK",
        "collection": "Runbooks",
        "description": "Operational runbook template for routine SOC tasks with trigger conditions, procedures, and rollback steps.",
        "tags": ["SOC-CMM", "NIST-CSF-2.0"],
        "variables": [
            {"name": "doc_id", "var_type": "string", "required": True, "default_value": "RB-001", "description": "Document identifier"},
            {"name": "version", "var_type": "string", "required": True, "default_value": "1.0", "description": "Document version"},
            {"name": "author", "var_type": "string", "required": True, "default_value": "", "description": "Document author"},
            {"name": "runbook_title", "var_type": "string", "required": True, "default_value": "", "description": "Runbook title"},
            {"name": "trigger_conditions", "var_type": "text", "required": False, "default_value": "", "description": "Conditions that trigger this runbook"},
            {"name": "prerequisites", "var_type": "text", "required": False, "default_value": "", "description": "Prerequisites and requirements"},
            {"name": "procedure_steps", "var_type": "text", "required": False, "default_value": "", "description": "Detailed procedure steps"},
            {"name": "rollback_steps", "var_type": "text", "required": False, "default_value": "", "description": "Rollback procedure"},
            {"name": "escalation_contacts", "var_type": "text", "required": False, "default_value": "", "description": "Escalation contact list"},
            {"name": "success_criteria", "var_type": "text", "required": False, "default_value": "", "description": "Success/completion criteria"},
        ],
        "content": """# {{ doc_id }} - Runbook: {{ runbook_title }}

| Field | Value |
|-------|-------|
| **Document ID** | {{ doc_id }} |
| **Version** | {{ version }} |
| **Author** | {{ author }} |

---

## Overview

{{ runbook_title }}

## Trigger Conditions

This runbook should be executed when:

{{ trigger_conditions }}

## Prerequisites

{{ prerequisites }}

- [ ] Required access verified
- [ ] Required tools available
- [ ] Change management ticket created (if applicable)

## Procedure

{{ procedure_steps }}

| Step | Action | Expected Result | Verification |
|------|--------|----------------|--------------|
| 1 | | | |
| 2 | | | |
| 3 | | | |
| 4 | | | |
| 5 | | | |

## Verification

### Success Criteria

{{ success_criteria }}

- [ ] Primary objective achieved
- [ ] No adverse impact on services
- [ ] Results documented

## Rollback

If the procedure fails or causes adverse impact:

{{ rollback_steps }}

1.
2.
3.

## Escalation Path

{{ escalation_contacts }}

| Condition | Escalate To | Method |
|-----------|------------|--------|
| Procedure fails | | |
| Unexpected results | | |
| Service impact | | |

---

## Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {{ version }} | | {{ author }} | Initial version |
""",
    },
]


# =============================================================================
# Seeding function
# =============================================================================

def seed_soc_templates() -> None:
    """Seed SOC documentation templates, collections, and framework tags.

    Idempotent - checks by name before creating.
    """
    from ixion.storage.database import get_engine, get_session_factory
    from ixion.storage.template_repository import TemplateRepository
    from ixion.storage.version_repository import VersionRepository
    from ixion.storage.collection_repository import CollectionRepository
    from ixion.models.template import Collection

    engine = get_engine()
    factory = get_session_factory(engine)
    session = factory()

    try:
        template_repo = TemplateRepository(session)
        version_repo = VersionRepository(session)
        collection_repo = CollectionRepository(session)

        # --- Create collections (idempotent by name) ---
        collection_map: dict[str, int] = {}
        for cdef in COLLECTION_DEFS:
            existing = collection_repo.get_by_name(cdef["name"])
            if existing:
                collection_map[cdef["name"]] = existing.id
            else:
                col = collection_repo.create(
                    name=cdef["name"],
                    description=cdef["description"],
                    icon=cdef.get("icon"),
                )
                session.flush()
                collection_map[cdef["name"]] = col.id
                logger.info("Created SOC collection: %s", cdef["name"])

        # --- Create templates (idempotent by name) ---
        created_count = 0
        for tdef in TEMPLATE_DEFS:
            existing = template_repo.get_by_name(tdef["name"])
            if existing:
                continue

            # Create the template
            template = template_repo.create(
                name=tdef["name"],
                content=tdef["content"],
                format="markdown",
                description=tdef["description"],
            )

            # Set document type
            template.document_type = tdef["document_type"]

            # Assign to collection
            col_name = tdef.get("collection")
            if col_name and col_name in collection_map:
                template.collection_id = collection_map[col_name]

            session.flush()

            # Add framework tags
            for tag_name in tdef.get("tags", []):
                template_repo.add_tag(template, tag_name)

            # Create initial version
            version_repo.create(
                template_id=template.id,
                version_number=1,
                content=tdef["content"],
                message="Initial SOC template version",
                author="IXION System",
            )

            # Register variables
            for var_def in tdef.get("variables", []):
                template_repo.add_variable(
                    template=template,
                    name=var_def["name"],
                    var_type=var_def.get("var_type", "string"),
                    required=var_def.get("required", True),
                    default_value=var_def.get("default_value"),
                    description=var_def.get("description"),
                )

            created_count += 1
            logger.info("Created SOC template: %s (%s)", tdef["name"], tdef["document_type"])

        session.commit()

        if created_count > 0:
            logger.info("Seeded %d SOC templates across %d collections", created_count, len(COLLECTION_DEFS))
        else:
            logger.debug("SOC templates already seeded, no changes needed")

    except Exception as e:
        session.rollback()
        logger.error("Failed to seed SOC templates: %s", e)
        raise
    finally:
        session.close()
