"""Emit CSV companions for ION's table-shaped docs.

These CSVs are intended as **editable working copies** for reviewers
(customer, DA chair, DPO, QA) to mark up in Excel. The maintainer-
authored .md remains the source-of-truth; the CSV is a snapshot.

Re-running this script overwrites the CSV — by design — so customer
edits should be saved to a separate file (e.g.
`_mod_compliance_mapping.signed.csv`) when handed back.

Usage:
    python tools/pdf_build/build_csv.py

Output:
    docs/USER_REQUIREMENTS.csv
    docs/TRACEABILITY.csv
    docs/TRACEABILITY_SR.csv
    docs/USE_CASES.csv
    _mod_compliance_mapping.csv
    _mod_exception_register.csv
    _mod_wcag_findings.csv
    _mod_dpia_risks.csv
    _mod_design_passport_risks.csv
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent


def write_csv(path: Path, header: list[str], rows: list[list[str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # UTF-8 BOM for Excel autodetect on Windows.
    with path.open("w", encoding="utf-8-sig", newline="") as fh:
        writer = csv.writer(fh, quoting=csv.QUOTE_MINIMAL, lineterminator="\r\n")
        writer.writerow(header)
        writer.writerows(rows)
    print(f"[csv] {path.relative_to(ROOT)}  ({len(rows)} rows)")


# ─────────────────────────────────────────────────────────────────────
# 1. USER_REQUIREMENTS.csv  —  51 URs
# ─────────────────────────────────────────────────────────────────────
URD_HEADER = ["UR ID", "Persona", "Priority", "Status", "Statement", "Source", "Acceptance"]
URD_ROWS = [
    ["UR-L1-001", "L1 Analyst", "M", "Met",
     "The L1 analyst sees a single ordered queue of alerts pending triage, sorted by severity x age, so they can attack the queue in priority order.",
     "SOC operations parity; analyst feedback",
     "The /alerts queue page displays alerts in severity DESC, age ASC order by default."],
    ["UR-L1-002", "L1 Analyst", "M", "Met",
     "For each alert, the L1 analyst sees enough context (rule name, MITRE technique, source, timestamp, affected entity) without opening a separate page.",
     "Reduce-tab-fatigue analyst feedback",
     "The alert row in /alerts shows: severity, age, rule, technique, hostname/user, timestamp, status."],
    ["UR-L1-003", "L1 Analyst", "M", "Met",
     "For each alert, the L1 analyst sees an AI-provided verdict suggestion with a confidence band, so they can triage common cases quickly.",
     "AI parity with leading SOC platforms",
     "When Bob has a matching template, the alert row shows a verdict suggestion + confidence band. When no template matches, the suggestion is suppressed."],
    ["UR-L1-004", "L1 Analyst", "M", "Met",
     "The L1 analyst is shown a visible signal when the AI's confidence is low, so they know to investigate manually rather than rely on the suggestion.",
     "AI safety: avoid over-trust",
     "Low-confidence verdicts display a circuit-breaker badge that suppresses the verdict text."],
    ["UR-L1-005", "L1 Analyst", "S", "Met",
     "The L1 analyst can select multiple alerts and close them as a batch when they share a closure reason.",
     "Throughput",
     "/alerts has a bulk-ops toolbar; >=2 alerts + Close applies the same CaseClosureReason to all."],
    ["UR-L1-006", "L1 Analyst", "M", "Met",
     "The L1 analyst can promote one or more alerts to a case with a single action.",
     "Operations parity",
     "Create Case action exists on single-selected alert and as a bulk-ops action on multi-selected alerts."],
    ["UR-L1-007", "L1 Analyst", "M", "Met",
     "The L1 analyst hands over to the next shift with structured, pre-populated context.",
     "Reduce shift-handover variance",
     "/shift-handover pre-populates with cases changed, alert volume, P1/P2 incidents, outstanding tunings; persists for next shift /briefing."],
    ["UR-L2-001", "L2 Analyst", "M", "Met",
     "The L2 analyst opens a case and sees: linked alerts, observables, similar past cases, entity timelines, the Workbench, and an attack story if applicable, without further navigation.",
     "Reduce decision time per case",
     "/cases/{id} renders all six surfaces on initial load."],
    ["UR-L2-002", "L2 Analyst", "M", "Met",
     "The L2 analyst pins relevant artefacts (alerts, observables, queries, notes, files) to a case for clarity at hand-off and audit-time.",
     "Audit-readiness; analyst feedback",
     "Workbench pin operation works for each pin type; every pin creates a CaseEvidencePin + CaseEvidenceLedger row."],
    ["UR-L2-003", "L2 Analyst", "M", "Met",
     "The L2 analyst's pinned evidence forms a tamper-evident audit chain that can be verified by audit / compliance.",
     "Regulatory / audit requirement",
     "CaseEvidenceLedger rows form a sha256 chain; verification walks the chain and surfaces tampering with row-level granularity."],
    ["UR-L2-004", "L2 Analyst", "S", "Met",
     "The L2 analyst sees a list of similar past cases (top-5 by similarity), with their closure reasons, as context for the current decision.",
     "Institutional-knowledge capture",
     "A sidebar on the case detail page shows top-5 similar cases (pgvector + HNSW + Ollama embedding)."],
    ["UR-L2-005", "L2 Analyst", "M", "Met",
     "The L2 analyst views a unified timeline for a host / user / IP across all ION data sources to spot kill-chain progression.",
     "Hunt-and-pivot pattern",
     "/entity-timeline/{type}/{id} returns a unified, sorted timeline; case-detail drawer surfaces it."],
    ["UR-L2-006", "L2 Analyst", "M", "Met",
     "The L2 analyst sees PCAP-derived findings on a case automatically, without pivoting out to Arkime, when network capture exists.",
     "Reduce per-case decision time",
     "Cases auto-trigger PCAP analysis on create; findings (12 heuristic detectors) post to case Workbench as pinned comment. v0.29.1 IP-fallback added."],
    ["UR-L2-007", "L2 Analyst", "M", "Met",
     "The SOC team views cases on a kanban board to manage the team's queue.",
     "Parity with ticketing tools",
     "/cases offers a kanban view by status; columns reflect case statuses; drag-to-update works."],
    ["UR-L3-001", "L3 Analyst", "M", "Met",
     "The L3 analyst has a forensic-case workflow that is structurally parallel to AlertCase but specialised for evidence-heavy DFIR.",
     "DFIR maturity; chain-of-custody requirement",
     "ForensicCase is a first-class entity; /forensics/{id} mirrors AlertCase capabilities; Workbench parity (v0.20.1)."],
    ["UR-L3-002", "L3 Analyst", "M", "Met",
     "Each evidence item attached to a ForensicCase has a chain of custody: who uploaded it, when, what happened to it.",
     "Forensic admissibility",
     "EvidenceItem + CustodyLogEntry rows record every state change; queryable by evidence id."],
    ["UR-L3-003", "L3 Analyst", "S", "Met",
     "The L3 analyst tests a threat hypothesis with ION's data without leaving the product.",
     "Threat-hunt parity",
     "Threat intel pages link technique to coverage; analyst can build a saved search and run it from the hunt context."],
    ["UR-L3-004", "L3 Analyst", "S", "Met",
     "The L3 analyst correlates multiple alerts into a kill-chain narrative attached to a case.",
     "Communication with leadership; reporting",
     "case_grouper_service auto-orders alerts onto a kill-chain; analyst annotates each step; narrative attaches to the case."],
    ["UR-DE-001", "Detection Engineer", "M", "Met",
     "The detection engineer sees per-rule false-positive rate, dwell time, and closure-reason distribution.",
     "Tuning by data",
     "/engineering/analytics ranks rules by FP rate x volume; drill-in shows example alerts and Bob-vs-analyst divergences."],
    ["UR-DE-002", "Detection Engineer", "M", "Met",
     "The detection engineer files a tuning proposal, gets review, and pushes the change to TIDE.",
     "Auditable rule changes",
     "/tuning-proposals supports the full lifecycle (file -> review -> sync to TIDE -> mark closed)."],
    ["UR-DE-003", "Detection Engineer", "M", "Met",
     "The detection engineer sees a live MITRE ATT&CK heatmap showing the customer's detection coverage.",
     "Coverage-conversation parity",
     "/cyab/attack-heatmap renders bundled ATT&CK v15.1 with overlay of TIDE rules; drill-in surfaces gaps."],
    ["UR-DE-004", "Detection Engineer", "S", "Met",
     "The detection engineer maps detection rules to one or more compliance frameworks (NIST CSF, ISO 27001, ACSC E8, DefStan).",
     "Audit-pack assembly",
     "/compliance shows framework x rule matrix and exports a coverage report."],
    ["UR-DE-005", "Detection Engineer", "M", "Met",
     "The detection engineer creates, edits, and tunes Bob's prompt templates (matching, content, confidence threshold).",
     "Bob calibration",
     "/alert-prompts supports CRUD + matching-rule editing + confidence_threshold_override per template."],
    ["UR-DE-006", "Detection Engineer", "M", "Met",
     "The detection engineer scores a Bob template's precision / recall / F1 against historical alerts before deploying it live.",
     "AI safety, calibration",
     "/bob-eval runs an offline replay against historical alerts; P/R/F1 reported; hard-blocks if a live investigation loop is active."],
    ["UR-SM-001", "SOC Manager", "M", "Met",
     "The SOC manager runs a daily standup with pre-populated last-24h posture data.",
     "Daily-cadence operations",
     "/briefing aggregates P1/P2 incidents, alert volume, noisy rules, SLA breaches, tuning queue, action items."],
    ["UR-SM-002", "SOC Manager", "S", "Met",
     "The SOC manager sees fair, data-driven analyst efficiency without invasive surveillance.",
     "Performance reviews",
     "/analyst-efficiency shows per-analyst cases closed, dwell time, closure-reason distribution, Bob-agreement rate."],
    ["UR-SM-003", "SOC Manager", "S", "Met",
     "The SOC manager generates an executive briefing covering top threats, rules tuned, incidents resolved, coverage delta, recommended actions.",
     "Communication-with-leadership",
     "/threat-landscape -> Generate Briefing produces an editable, exportable exec brief (v0.27.0)."],
    ["UR-SM-004", "SOC Manager", "M", "Met",
     "The SOC manager sees per-case SLA status and is alerted on imminent breach.",
     "Operations rigour",
     "SLA policies are configurable; breach log records each breach with attribution."],
    ["UR-SM-005", "SOC Manager", "C", "Met",
     "The SOC manager sees a 5-dimension SOC-CMM-style maturity scorecard.",
     "Maturity-conversation parity",
     "/maturity surfaces an A-F grade across detection / operations / team / knowledge / integrations."],
    ["UR-AD-001", "Admin", "M", "Met",
     "The admin configures (URL, credentials) each enabled integration without restarting ION.",
     "Operations",
     "/integrations supports CRUD per integration with a smoke Test action."],
    ["UR-AD-002", "Admin", "M", "Met",
     "The admin manages users (invite, suspend), roles (assign), and permissions (grant/revoke).",
     "RBAC governance",
     "/users, /roles, /permissions surfaces support the full lifecycle."],
    ["UR-AD-003", "Admin", "M", "Met",
     "The admin enables OIDC SSO (Keycloak) for the analyst team.",
     "Customer identity-management policy",
     "OIDC RS256 flow works end-to-end; HS256 explicitly refused; JWKS auto-refreshes."],
    ["UR-AD-004", "Admin", "S", "Met",
     "The admin tunes runtime settings (pool sizes, slow-query threshold, Bob confidence threshold) without redeploying.",
     "Operations",
     "/settings (admin) edits the Settings table; changes take effect within the request handler."],
    ["UR-AD-005", "Admin / Compliance", "M", "Met",
     "The admin / compliance reviews and exports the audit log.",
     "Compliance / audit",
     "/audit-log supports filter by user / action / target / date and CSV export."],
    ["UR-AD-006", "Admin / Compliance", "M", "Met",
     "The admin / compliance verifies the integrity of the Workbench ledger.",
     "Compliance / audit",
     "/workbench-audit (or CLI) recomputes each sha256 hash and flags any broken link."],
    ["UR-LR-001", "Learner", "M", "Partial",
     "The learner self-paces through L1/L2/L3 curriculum (modules -> lessons -> quizzes -> labs).",
     "New-analyst onboarding",
     "/training shows the assigned learning path; lessons render; quizzes work; labs run (lab-fixture system has 4 known bugs queued for v0.30.0)."],
    ["UR-LR-002", "SOC Manager (trainer)", "S", "Met",
     "The SOC manager assigns a learning path to a team member and tracks their progress.",
     "Coaching workflow",
     "/courses supports assignment + progress dashboard."],
    ["UR-CO-001", "DPO / Admin", "M", "Met",
     "The DPO retrieves all data referencing a named subject in response to a UK GDPR Article 15 request.",
     "UK GDPR / DPA 2018",
     "/admin/sar (or DPIA Appendix A SQL) returns every row referencing the subject."],
    ["UR-CO-002", "DPO / Admin", "M", "Met",
     "The DPO processes a UK GDPR Article 17 erasure request: anonymises personal identifiers while retaining operational artefacts.",
     "UK GDPR / DPA 2018",
     "/admin/erasure (or DPIA Appendix B SQL) anonymises affected rows; audit_log captures the action."],
    ["UR-CO-003", "Compliance", "M", "Met",
     "The compliance team verifies that the case-evidence audit trail has not been tampered with.",
     "Audit / regulatory",
     "Workbench ledger verification report runs read-only; identifies broken links to row granularity."],
    ["UR-CO-004", "Any user / Compliance", "M", "Partial",
     "Public-sector users have ION analyst surfaces conformant to WCAG 2.2 Level AA.",
     "UK Public Sector Bodies Accessibility Regulations 2018",
     "Tier-1 + Tier-2 analyst surfaces conformant; Tier-3 + Tier-4 remediation plans tracked for v0.30.0 / v0.31.0."],
    ["UR-NFR-001", "Operator", "M", "Met",
     "The deployed instance operates with no live external internet connectivity.",
     "Defence + critical-infra customers",
     "All bundled data (ATT&CK, KEV) ships in Docker image; Bob runs against local Ollama; no runtime external calls."],
    ["UR-NFR-002", "Any analyst", "S", "Partial",
     "Analyst-facing pages render within 1.5 seconds at p95.",
     "Productivity",
     "Empirical p95 < 1500ms on detail pages; < 700ms on list pages. Formal load-test pending."],
    ["UR-NFR-003", "Compliance", "M", "Met",
     "Every state-mutating request creates an audit_log row.",
     "Audit / regulatory",
     "Every 2xx mutating response has a corresponding audit_log row with user, ip, action, target, outcome."],
    ["UR-NFR-004", "SIEM team", "M", "Met",
     "Audit logs are emitted in a format the customer SIEM can ingest without parsing custom regex.",
     "Operations rigour",
     "Logs are ECS-compliant JSON-lines on stdout."],
    ["UR-NFR-005", "Operator", "M", "Met",
     "The deployed instance can be restored from a backup within the customer's RTO/RPO targets.",
     "Business continuity",
     "RTO <= 1 hour; RPO <= 24 hours; backup + restore procedure documented in _mod_iteap.md S5."],
    ["UR-NFR-006", "Any analyst", "M", "Met",
     "If an external integration is unavailable, the analyst can still do core work.",
     "Operations rigour",
     "Each adapter raises IntegrationUnavailable on exhaustion; surfaces display a banner; core pages remain functional."],
    ["UR-NFR-007", "Customer security", "M", "Met",
     "The customer sees the full dependency list (SBOM) for an ION release.",
     "SBOM mandate",
     "SPDX-JSON SBOM ships in the image at /app/sbom.spdx.json."],
    ["UR-NFR-008", "Customer security", "S", "Met",
     "The customer sees the severity trend across recent releases.",
     "Maintainer-supplied evidence",
     "SECURITY_ASSESSMENT.md carries the running severity-trend table for every release."],
    ["UR-NFR-009", "Any user", "C", "Planned",
     "All user-facing strings can be localised without code changes.",
     "International deployment readiness",
     "Templates use a translation function or equivalent indirection. Not yet implemented."],
    ["UR-NFR-010", "Operator / Customer security", "M", "Met",
     "A tagged ION release image is immutable - re-pulling the same tag yields the same content.",
     "Trust + reproducibility",
     "Docker Hub tags are digest-pinned; image not republished under the same tag."],
    # ── v1.1 additions ───────────────────────────────────────────────
    ["UR-L2-008", "L2 Analyst", "S", "Met",
     "The L2 analyst's in-progress working notes per case (queries tried, hypotheses, dead ends) are persisted alongside the case so a hand-off doesn't lose the investigation trail.",
     "Reduce hand-off rework",
     "Investigation memory persists per case; survives sessions; rendered on case detail page; editable."],
    ["UR-L2-009", "L2 Analyst", "S", "Met",
     "The L2 analyst asks Bob ad-hoc questions in the context of the current case without leaving the case detail page.",
     "Cognitive ergonomics",
     "Case detail page has an AI Chat panel scoped to the case; queries reach Ollama; responses advisory."],
    ["UR-L3-005", "L3 Analyst / Threat Hunter", "S", "Met",
     "The L3 analyst navigates a knowledge graph of relationships between actors, techniques, IOCs, and cases to pivot during a hunt.",
     "Hunt-pivot workflow",
     "Knowledge graph surface in /threat-intel renders entities + relations; click-to-pivot."],
    ["UR-DE-007", "Detection Engineer", "S", "Met",
     "The detection engineer maps detection rules to MITRE D3FEND defensive techniques to articulate defensive coverage in defender-language.",
     "Defender-language parity",
     "/d3fend shows D3FEND techniques mapped to TIDE rules; drill-in surfaces gaps."],
    ["UR-DE-008", "Detection Engineer", "S", "Met",
     "The detection engineer exports the customer's current MITRE ATT&CK coverage as a Navigator layer JSON for sharing.",
     "Cross-org standardised sharing",
     "Single-click export from ATT&CK heatmap produces a valid Navigator layer JSON."],
    ["UR-SM-006", "Any analyst; SOC Manager", "C", "Met",
     "Each user can arrange their own dashboard surface (widget choice + order + size) to suit their role and shift cadence.",
     "Productivity, role-fit",
     "Dashboard layout is per-user; persists across sessions; drag-to-rearrange + add/remove widgets."],
    ["UR-AD-007", "Admin / Operator", "M", "Met",
     "The customer's monitoring system polls a stable health endpoint to alarm on ION outage.",
     "ITSM / monitoring integration",
     "GET /health returns 200 with stable JSON shape documented in docs/RUNBOOK.md; non-2xx on degraded states."],
    ["UR-NFR-011", "Customer security", "M", "Met",
     "The application enforces a strict Content-Security-Policy to defang XSS attempts.",
     "XSS hardening; OWASP A03",
     "CSP middleware emits a strict policy; inline scripts nonce-based; unsafe-eval not present."],
    ["UR-NFR-012", "Any analyst", "S", "Met",
     "Timestamps stored in UTC; analyst sees their preferred timezone in the UI.",
     "Multi-shift / multi-region SOC",
     "DB timestamps are UTC; per-user TZ preference renders display-side; logs always UTC."],
    ["UR-NFR-013", "Any analyst; SOC Manager", "S", "Met",
     "The user sees in-app notifications (case assignment, SLA breach approaching, playbook approval requested).",
     "Workflow attention-routing",
     "/notifications surface displays unread items; UI badge shows count; mark-read clears."],
    ["UR-TI-001", "Threat Intel Analyst", "M", "Met",
     "The TI analyst views a curated threat landscape briefing for the current period without manually assembling it.",
     "Daily TI cadence",
     "/threat-landscape renders the briefing; Generate Briefing produces editable exportable text (v0.27.0)."],
    ["UR-TI-002", "Threat Intel Analyst", "M", "Met",
     "The TI analyst opens an actor profile and sees aliases, motivations, sector targets, techniques, IOC sparkline, recent reports.",
     "Actor-driven workflow",
     "Actor profile page includes aliases, motivations, sectors, techniques + ATT&CK click-through, IOC sparkline (v0.27.0)."],
    ["UR-TI-003", "Threat Intel Analyst", "S", "Met",
     "The TI analyst sees the most recently observed IOCs across all watched feeds in a single live view.",
     "Operational TI parity",
     "Live IOC feed surface on /threat-intel shows latest IOCs with type, confidence, last-seen."],
    ["UR-TI-004", "Threat Intel Analyst; Detection Engineer", "M", "Met",
     "The TI analyst is alerted when a watched actor gains a technique not covered by the customer's current TIDE rules.",
     "Coverage drift detection",
     "threat_watch_gap_service raises alerts; visible in /threat-intel; cross-references /cyab/attack-heatmap."],
    ["UR-OP-001", "Operator / SRE", "M", "Met",
     "The operator deploys a new ION instance from documented Docker Compose / image artefacts with no out-of-band steps.",
     "Operations rigour",
     "docs/DEPLOYMENT.md end-to-end procedure works against a clean environment; smoke check passes."],
    ["UR-OP-002", "Operator / SRE", "M", "Met",
     "The operator backs up and restores ION's state per documented procedure within the agreed RTO.",
     "Business continuity",
     "DR drill from _mod_iteap.md S5 passes: Postgres backup restored, image redeployed, smoke check green, <= 1 hour wall-clock."],
    ["UR-OP-003", "Operator / SRE", "S", "Met",
     "The operator is alerted when Postgres queries cross a slow-query threshold so capacity issues are caught early.",
     "Operational early-warning",
     "Settings has slow_query_threshold_ms; queries above it emit ECS-shaped log row; suggested SIEM detection in _mod_log_shipping_spec.md."],
    ["UR-OP-004", "Operator / SRE", "S", "Met",
     "The operator is alerted before Postgres connection pool exhaustion, not at the moment of failure.",
     "Operational early-warning",
     "Pool size, overflow, in-use exposed in /health or /admin/health-detail; suggested customer-side alarm at 80% utilisation."],
    ["UR-AI-001", "Any analyst", "S", "Met",
     "The analyst asks Bob open-ended analytical questions and receives an answer grounded in ION's data.",
     "Analyst ergonomics",
     "/ai-chat accepts NL questions; routes to Ollama; responses cite ION data sources."],
    ["UR-AI-002", "Any analyst", "S", "Met",
     "The analyst describes a query in plain English and Bob produces a valid Elasticsearch query preview to review and execute.",
     "Reduce query-syntax friction",
     "NL-to-ES surface accepts NL; emits Elasticsearch query JSON; analyst confirms before execution."],
    ["UR-AI-003", "L2/L3 Analyst; SOC Manager", "C", "Met",
     "The analyst generates draft documents (incident report, exec brief, IR runbook section) by prompting Bob; draft editable before save.",
     "Reduce report-writing burden",
     "AI document generation accepts template + context prompt; produces draft; analyst edits and saves."],
    ["UR-NET-001", "Detection Engineer; L2/L3 Analyst", "S", "Met",
     "The DE / analyst sees the customer's network assets and their topology to contextualise alerts.",
     "Investigation context",
     "/network-assets lists assets; /topology renders the graph."],
    ["UR-NET-002", "Detection Engineer; Operator", "M", "Met",
     "The DE is alerted to silent log sources (ingest stalled / volume drop / missing fields).",
     "Avoid coverage holes from silent failures",
     "/log-source-health surfaces per-source ingest status, volume trend, silent-source flags."],
    ["UR-KM-001", "Any analyst", "S", "Met",
     "Analysts capture and retrieve persistent notes (per case, per host, per playbook step) without leaving ION.",
     "Tribal-knowledge capture",
     "/notes supports CRUD with folders + tags + search; notes attachable to cases / observables."],
    ["UR-KM-002", "SOC Manager; Analyst", "S", "Met",
     "The SOC team stores reusable templates (notification text, IR runbook, post-incident review) inside ION for consistency.",
     "Consistency in reporting",
     "/templates + /documents support markdown editing, versioning, template-fill at use-time."],
    ["UR-EM-001", "Detection Engineer; L3 Analyst", "C", "Met",
     "The DE browses an adversary-emulation plan library (CALDERA-style) to plan a purple-team exercise.",
     "Purple-team readiness",
     "/emulation lists plans with steps tied to ATT&CK techniques."],
    ["UR-EM-002", "Detection Engineer", "C", "Met",
     "The DE runs an emulation plan and tracks per-step outcomes (was the technique detected? if not, why?).",
     "Purple-team-to-tuning feedback loop",
     "Per-plan execution recorded; per-step pass/fail tracked; tuning proposals filed from failed step."],
    ["UR-CA-001", "Detection Engineer", "C", "Met",
     "The DE deploys canary tokens (honeydocs, credentials, DNS) to high-value assets for high-confidence breach detection.",
     "Early-warning detection",
     "/canaries supports CRUD; deployment metadata captured; integration with email/DNS/cred token types."],
    ["UR-CA-002", "L1 Analyst (consumer); Detection Engineer (producer)", "C", "Met",
     "A tripped canary token produces a high-priority alert + case with immediate-attention SLAs.",
     "High-fidelity-trigger workflow",
     "Canary trip creates an alert with severity: critical and pre-populated case context; SOC playbook auto-suggested."],
    ["UR-API-001", "Admin; Customer integrations team", "S", "Met",
     "ION emits outbound webhooks on configurable events so the customer's wider ITSM / messaging stack can react.",
     "Cross-tool workflow",
     "Webhook configuration in /integrations; HMAC-signed payload; retry on transient failure; delivery log."],
]


# ─────────────────────────────────────────────────────────────────────
# 2. TRACEABILITY.csv  —  51-row RTM
# ─────────────────────────────────────────────────────────────────────
RTM_HEADER = ["UR", "SR(s)", "HLD ref", "LLD ref", "Use Case(s)", "Gap(s)", "Test(s)", "Status"]
RTM_ROWS = [
    ["UR-L1-001", "SR-ALERT-002", "S6.3", "S10.1", "UC-L1-01", "GAP-01",
     "test_alert_queue_order.py", "Met"],
    ["UR-L1-002", "SR-ALERT-003", "S6.3", "S10.1", "UC-L1-01", "GAP-01",
     "test_alert_row_fields.py", "Met"],
    ["UR-L1-003", "SR-AI-001; SR-AI-002", "S7.5", "S7.1; S7.2", "UC-L1-01", "GAP-02; GAP-03",
     "test_bob_template_match.py; test_bob_output_contract.py", "Met"],
    ["UR-L1-004", "SR-AI-003", "S7.5", "S7.1", "UC-L1-01", "GAP-16",
     "test_bob_confidence_band.py", "Met"],
    ["UR-L1-005", "SR-CASE-001", "S4", "S5", "UC-L1-01", "GAP-01",
     "test_bulk_close.py", "Met"],
    ["UR-L1-006", "SR-CASE-001; SR-CASE-002", "S4", "S5; S6.2", "UC-L1-02", "GAP-01",
     "test_case_create_from_alerts.py; test_case_grouper.py", "Met"],
    ["UR-L1-007", "SR-OPS-002", "S4.2", "S10.1", "UC-L1-03", "GAP-12",
     "test_shift_handover.py", "Met"],
    ["UR-L2-001", "SR-CASE-003", "S4", "S10.1", "UC-L2-01", "GAP-04; GAP-06",
     "test_case_landing_page.py", "Met"],
    ["UR-L2-002", "SR-PIN-001; SR-PIN-002", "S7.3", "S3.3; S10.4", "UC-L2-01", "GAP-04",
     "test_workbench_pin_lifecycle.py", "Met"],
    ["UR-L2-003", "SR-LEDGER-001; SR-LEDGER-002", "S7.3", "S9.2", "UC-AD-04", "GAP-04; GAP-17",
     "test_ledger_chain.py; test_ledger_tamper_detection.py", "Met"],
    ["UR-L2-004", "SR-SIM-001; SR-SIM-002; SR-SIM-003", "S4.2", "S10.5", "UC-L2-01", "GAP-06",
     "test_case_similarity.py; test_case_embedding_backfill.py", "Met"],
    ["UR-L2-005", "SR-CASE-003", "S4.2", "S10.1", "UC-L2-01", "GAP-19",
     "test_entity_timeline.py", "Met"],
    ["UR-L2-006", "SR-PCAP-001; SR-PCAP-002; SR-PCAP-003", "S4.2", "S10.2", "UC-L2-01", "GAP-07",
     "test_pcap_auto_analysis.py; test_pcap_ip_fallback.py", "Met"],
    ["UR-L2-007", "SR-CASE-004", "S4", "S10.1", "UC-L2-01", "GAP-04",
     "test_case_kanban.py", "Met"],
    ["UR-L3-001", "SR-FOR-001; SR-LEDGER-003", "S4.2", "S3.3; S10.4", "UC-L3-01", "GAP-05",
     "test_forensic_case_lifecycle.py; test_forensic_workbench.py", "Met"],
    ["UR-L3-002", "SR-FOR-002", "S4.2", "S3.1", "UC-L3-01", "GAP-05",
     "test_custody_log.py", "Met"],
    ["UR-L3-003", "SR-TI-001; SR-TI-002", "S4.2", "S10.1", "UC-L3-02", "GAP-08",
     "test_threat_intel_landscape.py; test_threat_watch_gap.py", "Met"],
    ["UR-L3-004", "SR-CASE-002", "S4.2", "S10.1", "UC-L3-03", "GAP-08",
     "test_attack_story.py", "Met"],
    ["UR-DE-001", "SR-DE-001", "S4.2", "S10.1", "UC-DE-01", "GAP-09",
     "test_engineering_analytics.py; test_ai_feedback_dual_write.py", "Met"],
    ["UR-DE-002", "SR-DE-002", "S4.2", "S10.1", "UC-DE-01", "GAP-09",
     "test_tuning_proposal_lifecycle.py", "Met"],
    ["UR-DE-003", "SR-DE-003", "S4.2", "S10.1", "UC-L3-02; UC-DE-02", "GAP-10",
     "test_attack_heatmap.py", "Met"],
    ["UR-DE-004", "SR-DE-004", "S4.2", "S10.1", "UC-DE-02", "GAP-11",
     "test_compliance_mapping.py", "Met"],
    ["UR-DE-005", "SR-AI-006", "S7.5", "S7.1", "UC-DE-03", "GAP-02; GAP-16",
     "test_alert_prompt_crud.py; test_confidence_threshold_override.py", "Met"],
    ["UR-DE-006", "SR-AI-007", "S7.5", "S7.3", "UC-DE-03", "GAP-16",
     "test_bob_eval_harness.py", "Met"],
    ["UR-SM-001", "SR-OPS-001", "S4.2", "S10.1", "UC-SM-01", "GAP-12",
     "test_briefing_aggregation.py", "Met"],
    ["UR-SM-002", "SR-OPS-003", "S4.2", "S10.1", "UC-SM-02", "GAP-13",
     "test_analyst_efficiency.py", "Met"],
    ["UR-SM-003", "SR-OPS-004; SR-TI-003", "S4.2", "S10.1", "UC-SM-03", "GAP-08",
     "test_executive_report_generator.py; test_threat_landscape_brief.py", "Met"],
    ["UR-SM-004", "SR-CASE-001", "S4", "S5", "UC-SM-01", "GAP-12",
     "test_sla_breach_log.py", "Met"],
    ["UR-SM-005", "SR-OPS-001", "S4.2", "S10.1", "UC-SM-01", "(general)",
     "test_maturity_scorecard.py", "Met"],
    ["UR-AD-001", "SR-ADMIN-001", "S9", "S12", "UC-AD-01", "GAP-19",
     "test_integration_config.py; test_integration_smoke_action.py", "Met"],
    ["UR-AD-002", "SR-RBAC-001; SR-ADMIN-002", "S7.2", "S8.3", "UC-AD-02", "GAP-19",
     "test_user_role_lifecycle.py; test_permission_grant.py", "Met"],
    ["UR-AD-003", "SR-AUTH-002", "S7.1", "S8.2", "UC-AD-02", "GAP-19",
     "test_oidc_rs256_only.py; test_oidc_hs256_refused.py", "Met"],
    ["UR-AD-004", "SR-ADMIN-003", "S7.2", "S12.1", "UC-AD-01", "(general)",
     "test_settings_runtime_mutation.py", "Met"],
    ["UR-AD-005", "SR-ADMIN-004; SR-NFR-AUDIT", "S7.3", "S9.1", "UC-AD-03; UC-CO-01", "GAP-17",
     "test_audit_log_filter.py; test_audit_log_export.py", "Met"],
    ["UR-AD-006", "SR-ADMIN-005; SR-LEDGER-002", "S7.3", "S9.2", "UC-AD-04", "GAP-17",
     "test_workbench_audit_verify.py", "Met"],
    ["UR-LR-001", "SR-CURR-001; SR-CURR-002", "S4.2", "S3.1", "UC-LR-01", "GAP-14",
     "test_curriculum_lifecycle.py (lab tests partial - 4 bugs queued v0.30.0)", "Partial"],
    ["UR-LR-002", "SR-CURR-001", "S4.2", "S3.1", "UC-LR-02", "GAP-14",
     "test_course_assignment.py", "Met"],
    ["UR-CO-001", "SR-DPO-001", "S6.7", "S12", "UC-CO-01", "GAP-17",
     "test_sar_query.py; DPIA App. A SQL", "Met"],
    ["UR-CO-002", "SR-DPO-002", "S6.7", "S12", "UC-CO-02", "GAP-17",
     "test_erasure_anonymise.py; DPIA App. B SQL", "Met"],
    ["UR-CO-003", "SR-LEDGER-002", "S7.3", "S9.2", "UC-AD-04", "GAP-04; GAP-17",
     "test_ledger_chain.py; test_ledger_tamper_detection.py", "Met"],
    ["UR-CO-004", "(NFR; cross-cutting)", "S6.6", "(cross-cutting)", "(all UCs)", "(general)",
     "_mod_wcag_audit.md tier-1+2 audit", "Partial"],
    ["UR-NFR-001", "SR-NFR-AIRGAP", "S6.8; S8.3", "S12.2", "(operator)", "GAP-15",
     "test_airgap_no_network_calls.py; image inspection", "Met"],
    ["UR-NFR-002", "(perf)", "S6.2", "(cross-cutting)", "(all UCs)", "(general)",
     "Empirical only; formal load-test planned v0.31.0+", "Partial"],
    ["UR-NFR-003", "SR-NFR-AUDIT", "S6.5; S7.3", "S9.1", "UC-AD-03", "GAP-17",
     "test_audit_log_every_mutation.py", "Met"],
    ["UR-NFR-004", "SR-NFR-LOG", "S7.4", "S11.2", "(SIEM team)", "GAP-19",
     "test_ecs_log_shape.py; _mod_log_shipping_spec.md", "Met"],
    ["UR-NFR-005", "SR-NFR-RTO; SR-NFR-RPO", "S6.1", "S12", "(operator)", "(general)",
     "_mod_iteap.md S5 DR drill", "Met"],
    ["UR-NFR-006", "SR-NFR-INTEG", "S9", "S11.2", "(all UCs)", "GAP-19",
     "test_integration_failure_modes.py (x7 per adapter)", "Met"],
    ["UR-NFR-007", "SR-NFR-SBOM", "S6.4", "S13.2", "(customer security)", "(general)",
     "Image-inspection step in _mod_iteap.md", "Met"],
    ["UR-NFR-008", "SR-NFR-SCA", "S6.4", "S13.2", "(customer security)", "(general)",
     ".github/workflows/test.yml", "Met"],
    ["UR-NFR-009", "(none yet)", "S11", "(n/a)", "(n/a)", "(general)",
     "Not implemented", "Planned"],
    ["UR-NFR-010", "SR-NFR-IMG", "S6.4", "S13", "(operator)", "(general)",
     "Docker Hub digest immutability", "Met"],
    # ── v1.1 additions ───────────────────────────────────────────────
    ["UR-L2-008", "SR-INV-MEM-001", "S4.2", "S10.1", "UC-L2-01", "GAP-04",
     "test_investigation_memory.py", "Met"],
    ["UR-L2-009", "SR-AI-CHAT-002", "S7.5", "S7", "UC-L2-01; UC-AI-01", "GAP-16",
     "test_ai_chat_case_scope.py", "Met"],
    ["UR-L3-005", "SR-KG-001", "S4.2", "S10.1", "UC-L3-02", "GAP-08",
     "test_knowledge_graph_nav.py", "Met"],
    ["UR-DE-007", "SR-D3FEND-001", "S4.2", "S10.1", "UC-DE-02", "GAP-10; GAP-11",
     "test_d3fend_mapping.py", "Met"],
    ["UR-DE-008", "SR-ATTACK-NAV-001", "S4.2", "S10.1", "UC-DE-02", "GAP-10",
     "test_attack_navigator_export.py", "Met"],
    ["UR-SM-006", "SR-DASH-001", "S4.2", "S10.1", "(cross-cutting)", "(general)",
     "test_dashboard_layout.py", "Met"],
    ["UR-AD-007", "SR-HEALTH-001", "S6.1; S7.4", "S11", "UC-OP-01; UC-OP-03", "(general)",
     "test_health_endpoint.py", "Met"],
    ["UR-NFR-011", "SR-CSP-001", "S6.4", "S11", "(cross-cutting)", "(general)",
     "test_csp_header.py", "Met"],
    ["UR-NFR-012", "SR-TZ-001", "S6.4", "S3", "(cross-cutting)", "(general)",
     "test_timezone_handling.py", "Met"],
    ["UR-NFR-013", "SR-NOTIF-001", "S4.2", "S10.1", "(cross-cutting)", "(general)",
     "test_notifications.py", "Met"],
    ["UR-TI-001", "SR-TI-LANDSCAPE-001", "S4.2", "S10.1", "UC-TI-01", "GAP-08",
     "test_threat_landscape_brief.py", "Met"],
    ["UR-TI-002", "SR-TI-ACTOR-001", "S4.2", "S10.1", "UC-TI-02", "GAP-08",
     "test_actor_profile.py; test_actor_ioc_sparkline.py", "Met"],
    ["UR-TI-003", "SR-TI-IOC-FEED-001", "S4.2", "S10.1", "UC-TI-02", "GAP-08",
     "test_live_ioc_feed.py", "Met"],
    ["UR-TI-004", "SR-TI-002", "S4.2", "S10.1", "UC-TI-02", "GAP-08; GAP-10",
     "test_threat_watch_gap.py", "Met"],
    ["UR-OP-001", "SR-OP-DEPLOY-001", "S8.1; S8.2; S8.3", "S12", "UC-OP-01", "(general)",
     "_mod_iteap.md S1 functional + deployment smoke", "Met"],
    ["UR-OP-002", "SR-OP-BACKUP-001; SR-NFR-RTO; SR-NFR-RPO", "S6.1", "S12", "UC-OP-02", "(general)",
     "_mod_iteap.md S5 DR drill", "Met"],
    ["UR-OP-003", "SR-OP-SLOWQ-001; SR-NFR-LOG", "S7.4", "S11.2", "UC-OP-03", "(general)",
     "test_slow_query_log_emit.py; _mod_log_shipping_spec.md", "Met"],
    ["UR-OP-004", "SR-OP-POOL-001; SR-HEALTH-001", "S7.4", "S11", "UC-OP-03", "(general)",
     "test_pool_metrics_exposed.py", "Met"],
    ["UR-AI-001", "SR-AI-CHAT-001", "S7.5", "S7", "UC-AI-01", "GAP-19",
     "test_ai_chat_grounded.py", "Met"],
    ["UR-AI-002", "SR-AI-CHAT-003", "S7.5", "S7", "UC-AI-02", "GAP-02",
     "test_nl_to_es.py", "Met"],
    ["UR-AI-003", "SR-AI-DOC-001", "S7.5", "S7", "UC-SM-03; UC-AI-01", "(general)",
     "test_ai_document_gen.py", "Met"],
    ["UR-NET-001", "SR-NET-CMDB-001", "S4.2", "S10.1", "UC-NET-01", "(general)",
     "test_network_asset_cmdb.py; test_topology_render.py", "Met"],
    ["UR-NET-002", "SR-NET-LOG-HEALTH-001", "S4.2", "S10.1", "UC-NET-01", "(general)",
     "test_log_source_health.py", "Met"],
    ["UR-KM-001", "SR-KM-NOTES-001", "S4.2", "S10.1", "(cross-cutting)", "(general)",
     "test_notes_crud.py", "Met"],
    ["UR-KM-002", "SR-KM-DOCS-001", "S4.2", "S10.1", "(cross-cutting)", "(general)",
     "test_templates_crud.py; test_documents_crud.py", "Met"],
    ["UR-EM-001", "SR-EM-PLAN-001", "S4.2", "S10.1", "UC-EM-01", "(general)",
     "test_emulation_plan_library.py", "Met"],
    ["UR-EM-002", "SR-EM-EXEC-001", "S4.2", "S10.1", "UC-EM-01", "GAP-10",
     "test_emulation_execution.py", "Met"],
    ["UR-CA-001", "SR-CA-DEPLOY-001", "S4.2", "S10.1", "UC-CA-01", "(general)",
     "test_canary_deploy.py", "Met"],
    ["UR-CA-002", "SR-CA-TRIP-001", "S4.2", "S10.1", "UC-CA-01", "(general)",
     "test_canary_trip_alert.py", "Met"],
    ["UR-API-001", "SR-API-WEBHOOK-001", "S9; S11.2", "S12", "UC-API-01", "GAP-19",
     "test_webhook_signed.py; test_webhook_retry.py", "Met"],
]


# ─────────────────────────────────────────────────────────────────────
# 3. TRACEABILITY_SR.csv  —  System Requirements catalogue
# ─────────────────────────────────────────────────────────────────────
SR_HEADER = ["SR ID", "Statement"]
SR_ROWS = [
    ["SR-AUTH-001", "Local password auth uses bcrypt and is rate-limited via slowapi"],
    ["SR-AUTH-002", "OIDC auth supports RS256 only; HS256 rejected at verification time"],
    ["SR-AUTH-003", "Sessions are server-side, cookie-bound, with Secure/HttpOnly/SameSite=Lax flags"],
    ["SR-RBAC-001", "7-tier role hierarchy with explicit Permission/RolePermission binding"],
    ["SR-RBAC-002", "Every endpoint enforces a permission via @permission_required(...)"],
    ["SR-RBAC-003", "Every service-layer mutation re-checks auth before commit (TOCTOU defence)"],
    ["SR-ALERT-001", "ES Security adapter pulls alerts on a 30-second schedule into ION's cache"],
    ["SR-ALERT-002", "/alerts displays alerts sorted by severity DESC, age ASC"],
    ["SR-ALERT-003", "Each alert row exposes severity, age, rule, technique, host/user, timestamp, status"],
    ["SR-AI-001", "Bob template selection uses a 5-tier matcher: rule_id -> regex -> technique -> tactic -> groups"],
    ["SR-AI-002", "Bob output validates against a Pydantic-bound schema (AlertPromptOutput); arbitrary text refused"],
    ["SR-AI-003", "Bob confidence is reported as 0-100 + low/medium/high band; low-confidence triggers UI circuit breaker"],
    ["SR-AI-004", "Bob never closes a case; CaseClosureReason selection is analyst-only"],
    ["SR-AI-005", "Bob outputs are joinable to audit_log via bob_verdict_id"],
    ["SR-AI-006", "confidence_threshold_override per template; admin-editable via /alert-prompts"],
    ["SR-AI-007", "Eval harness replays templates against historical alerts; reports P/R/F1; advisory-lock-blocked when a live investigation loop is active"],
    ["SR-CASE-001", "Cases are first-class entities (Investigation) with status / priority / closure_reason / assignee"],
    ["SR-CASE-002", "case_grouper_service correlates alerts by host/user/technique/timewindow into cases (every 5 min, advisory lock CGP)"],
    ["SR-CASE-003", "/cases/{id} renders linked alerts + observables + similar cases + entity timelines + workbench + attack story on initial load"],
    ["SR-CASE-004", "Case kanban view supports drag-to-update status"],
    ["SR-PIN-001", "Workbench pin operation accepts alert / observable / query / note / file pin types"],
    ["SR-PIN-002", "Every pin produces a CaseEvidencePin row + a CaseEvidenceLedger row in the same transaction"],
    ["SR-LEDGER-001", "CaseEvidenceLedger.event_hash = sha256(prev_hash + json(payload))"],
    ["SR-LEDGER-002", "Tamper detection walks the chain by insertion order; flags row-level breaks"],
    ["SR-LEDGER-003", "ForensicCase ledger uses distinct advisory-lock namespace FCWL"],
    ["SR-SIM-001", "Closed cases are embedded with nomic-embed-text via Ollama; stored in CaseEmbedding"],
    ["SR-SIM-002", "Similarity lookup uses pgvector + HNSW indexes"],
    ["SR-SIM-003", "Top-5 similar-cases panel appears on case detail page"],
    ["SR-PCAP-001", "Case-create triggers PCAP analysis for alerts with community_id OR source/destination IP + timestamp"],
    ["SR-PCAP-002", "Arkime adapter uses community_id preferred; IP+time fallback when community_id misses"],
    ["SR-PCAP-003", "PCAP heuristic analysis runs 12 detectors; findings post to case Workbench as pinned comment"],
    ["SR-FOR-001", "ForensicCase is parallel to AlertCase with own Workbench (advisory lock FCWL)"],
    ["SR-FOR-002", "Every EvidenceItem has a CustodyLogEntry audit chain"],
    ["SR-FOR-003", "Forensic playbooks are NIST SP 800-86 aligned"],
    ["SR-TI-001", "OpenCTI adapter provides threat landscape, actors, IOCs, reports"],
    ["SR-TI-002", "Threat Watch Gap raises alert when a watched actor gains a technique not covered by TIDE rules"],
    ["SR-TI-003", "Unified /threat-intel page replaces 3 prior pages (v0.27.0 consolidation)"],
    ["SR-DE-001", "/engineering/analytics ranks rules by FP rate x volume"],
    ["SR-DE-002", "/tuning-proposals supports full lifecycle: file -> review -> sync to TIDE -> close"],
    ["SR-DE-003", "/cyab/attack-heatmap renders bundled ATT&CK v15.1 (v0.22.0) with TIDE rule overlay"],
    ["SR-DE-004", "/compliance maps TIDE rules to NIST CSF, ISO 27001, ACSC E8, DefStan, and exports a coverage report"],
    ["SR-OPS-001", "/briefing aggregates: P1/P2 incidents, alert volume, noisy rules, SLA breaches, tuning queue"],
    ["SR-OPS-002", "/shift-handover pre-populates from shift state; persists for next shift's briefing"],
    ["SR-OPS-003", "/analyst-efficiency shows per-analyst metrics fairly (no surveillance signals)"],
    ["SR-OPS-004", "Executive briefing generator produces editable / exportable summary (v0.27.0)"],
    ["SR-ADMIN-001", "Each integration is configurable via /integrations + smoke Test action"],
    ["SR-ADMIN-002", "Users/roles/permissions managed via dedicated admin pages"],
    ["SR-ADMIN-003", "Settings table is runtime-mutable via /settings for non-secret operational parameters"],
    ["SR-ADMIN-004", "/audit-log supports filter + CSV export"],
    ["SR-ADMIN-005", "/workbench-audit recomputes sha256 chain and reports integrity"],
    ["SR-CURR-001", "/training exposes modules -> lessons -> quizzes; tracks per-user progress"],
    ["SR-CURR-002", "Lab system runs containerised exercises (v0.20.1; 4 known bugs queued for v0.30.0)"],
    ["SR-DPO-001", "SAR query returns every row referencing a named subject (SQL in DPIA Appendix A)"],
    ["SR-DPO-002", "Erasure query anonymises personal identifiers (SQL in DPIA Appendix B)"],
    ["SR-NFR-AIRGAP", "Image bundles ATT&CK + KEV snapshots; no live external feed dependency at runtime"],
    ["SR-NFR-LOG", "stdout JSON-lines ECS-compliant; one log entry per request and per state-mutating action"],
    ["SR-NFR-AUDIT", "Every 2xx state-mutating response generates an AuditLog row"],
    ["SR-NFR-RTO", "Postgres backup + image redeploy procedure documented; RTO <= 1h target"],
    ["SR-NFR-RPO", "Customer-side backup cadence <= 24h"],
    ["SR-NFR-INTEG", "Each adapter raises IntegrationUnavailable on exhaustion; surfaces show banner; core pages remain functional"],
    ["SR-NFR-SBOM", "SPDX-JSON SBOM bundled in image at /app/sbom.spdx.json"],
    ["SR-NFR-SCA", "pip-audit + bandit + ruff run in CI on every commit"],
    ["SR-NFR-IMG", "Docker Hub tags are digest-pinned; image not re-pushed under same tag"],
    # ── v1.1 additions ───────────────────────────────────────────────
    ["SR-INV-MEM-001", "Investigation memory persists analyst working notes per case across sessions"],
    ["SR-AI-CHAT-001", "/ai-chat surface routes NL queries to Ollama; conversation persisted per user"],
    ["SR-AI-CHAT-002", "Case-scoped AI chat panel constrains chat context to the current case"],
    ["SR-AI-CHAT-003", "NL-to-Elasticsearch converter emits query JSON preview before execution"],
    ["SR-AI-DOC-001", "AI document generation produces editable drafts from template + context prompt"],
    ["SR-KG-001", "Knowledge graph surface renders entity-relation graph with click-to-pivot"],
    ["SR-D3FEND-001", "D3FEND defensive technique map; bidirectional cross-reference with ATT&CK"],
    ["SR-ATTACK-NAV-001", "ATT&CK Navigator layer JSON export from /cyab/attack-heatmap"],
    ["SR-DASH-001", "Per-user dashboard layout; persists across sessions; drag-to-rearrange"],
    ["SR-HEALTH-001", "GET /health returns stable JSON schema documented in docs/RUNBOOK.md; non-2xx on degraded state"],
    ["SR-CSP-001", "Strict CSP middleware on every response; inline scripts nonce-based; no unsafe-eval"],
    ["SR-TZ-001", "DB timestamps in UTC; per-user TZ preference renders display-side; logs always UTC"],
    ["SR-NOTIF-001", "/notifications surface; in-app unread count badge; mark-read clears"],
    ["SR-TI-LANDSCAPE-001", "Threat landscape briefing generator produces editable exportable text (v0.27.0)"],
    ["SR-TI-ACTOR-001", "Actor profile page includes aliases, motivations, sectors, techniques + ATT&CK click-through, IOC sparkline (v0.27.0)"],
    ["SR-TI-IOC-FEED-001", "Live IOC feed surface with type, confidence, last-seen"],
    ["SR-OP-DEPLOY-001", "docs/DEPLOYMENT.md end-to-end deployment procedure; smoke check at completion"],
    ["SR-OP-BACKUP-001", "Postgres backup + restore procedure documented; meets RTO <= 1h"],
    ["SR-OP-SLOWQ-001", "slow_query_threshold_ms configurable; threshold-exceeding queries emit ECS log row"],
    ["SR-OP-POOL-001", "Pool size, overflow, in-use exposed on /health or /admin/health-detail"],
    ["SR-NET-CMDB-001", "/network-assets CMDB + /topology graph render"],
    ["SR-NET-LOG-HEALTH-001", "/log-source-health shows per-source ingest status, volume trend, silent flags"],
    ["SR-KM-NOTES-001", "/notes with folders + tags + search; attachable to cases / observables"],
    ["SR-KM-DOCS-001", "/templates + /documents with markdown editing, versioning, template-fill"],
    ["SR-EM-PLAN-001", "/emulation plan library with steps tied to ATT&CK techniques"],
    ["SR-EM-EXEC-001", "Emulation execution tracked per step (pass/fail); failed-step -> tuning proposal flow"],
    ["SR-CA-DEPLOY-001", "/canaries CRUD for honeydoc / credential / DNS tokens"],
    ["SR-CA-TRIP-001", "Canary trip auto-creates severity: critical alert with pre-populated context + playbook suggestion"],
    ["SR-API-WEBHOOK-001", "HMAC-signed outbound webhook on configurable events; retry on transient failure; delivery log"],
]


# ─────────────────────────────────────────────────────────────────────
# 4. USE_CASES.csv  —  one row per use case
# ─────────────────────────────────────────────────────────────────────
UC_HEADER = ["UC ID", "Title", "Persona", "Pre-conditions", "Post-conditions", "ION surfaces"]
UC_ROWS = [
    ["UC-L1-01", "Triage an alert", "L1 Analyst",
     "Alerts present in the Alert Queue",
     "Alert is closed or escalated; audit log row created; AIFeedback row created",
     "/alerts, alert detail modal, Bob verdict panel, Entity Timeline sidebar"],
    ["UC-L1-02", "Create a case from one or more alerts", "L1 Analyst",
     "One or more alerts open in the queue",
     "Case is open; alerts bound; Workbench seeded; background tasks running",
     "/alerts (bulk-ops), /cases/{id} (landing)"],
    ["UC-L1-03", "Hand over the shift", "L1 Analyst (ending shift)",
     "Open cases, recent alerts, ongoing tunings",
     "Handover persisted; accessible to incoming shift",
     "/shift-handover, /briefing"],
    ["UC-L2-01", "Investigate a case", "L2 Analyst",
     "Case open and assigned (or assignable)",
     "Case closed or escalated_to_l3; Workbench ledger has full pin history; audit logs complete",
     "/cases/{id} (full surface), Workbench tab, Similar Cases sidebar, Entity Timeline drawer"],
    ["UC-L2-02", "Escalate to L3 (deep-dive / forensics)", "L2 Analyst",
     "Case requires forensic depth (memory, full timeline, multi-host pivot)",
     "ForensicCase created and linked; AlertCase under_forensics_review",
     "/cases/{id}, /forensics/{forensic_id}"],
    ["UC-L3-01", "Run a forensic investigation", "L3 Analyst / Forensicator",
     "ForensicCase open and assigned",
     "ForensicCase closed; chain of custody intact and queryable; AlertCase notified",
     "/forensics/{id}, Workbench tab, Custody Log tab, Timeline tab"],
    ["UC-L3-02", "Hunt by hypothesis", "L3 Analyst / Threat Hunter",
     "Threat Intelligence indicating a hypothesis worth testing",
     "Hypothesis tested; coverage gaps documented; cases opened where warranted",
     "/threat-intel, /cyab/attack-heatmap, /discover, /cases"],
    ["UC-L3-03", "Build an attack story", "L3 Analyst",
     "Multiple correlated alerts",
     "Attack story persisted; reportable",
     "/attack-stories, case Workbench"],
    ["UC-DE-01", "Tune a noisy rule", "Detection Engineer",
     "AIFeedback shows a rule with high FP closure rate",
     "Rule updated in TIDE; tuning proposal closed; metrics track post-tuning effect",
     "/engineering/analytics, /tuning-proposals, /tide"],
    ["UC-DE-02", "Map TIDE rules to a compliance framework", "Detection Engineer",
     "TIDE rules synced; framework target identified",
     "Compliance posture report ready; gaps catalogued",
     "/compliance, /tide"],
    ["UC-DE-03", "Manage Bob's prompt templates", "Detection Engineer (security:settings)",
     "Bob enabled; templates exist or need creation",
     "Bob behaviour updated; eval harness re-runs in background",
     "/alert-prompts, /bob-eval"],
    ["UC-SM-01", "Daily standup briefing", "SOC Manager",
     "Shift just ended",
     "Daily action register updated; team aligned for the day",
     "/briefing, /daily-standup"],
    ["UC-SM-02", "Review analyst efficiency", "SOC Manager",
     ">= 1 sprint of activity recorded",
     "Coaching plan recorded; learning paths assigned where needed",
     "/analyst-efficiency, /courses"],
    ["UC-SM-03", "Generate an executive briefing", "SOC Manager",
     "Period of activity to summarise",
     "Executive briefing ready for leadership read-out",
     "/threat-landscape, /executive-report"],
    ["UC-AD-01", "Configure an integration", "Admin",
     "Integration endpoint reachable; credentials available",
     "Integration live; surfaces that consume it become active",
     "/integrations, /settings"],
    ["UC-AD-02", "Manage users + roles", "Admin",
     "RBAC schema seeded",
     "User can log in with the assigned permissions",
     "/users, /roles, /permissions"],
    ["UC-AD-03", "Review audit log", "Admin / Compliance",
     "audit:read permission",
     "Compliance has evidence; no data modified",
     "/audit-log"],
    ["UC-AD-04", "Tamper-evidence audit (Workbench)", "Admin / Compliance",
     "Workbench used; ledger rows exist",
     "Ledger integrity attested or tamper alarm raised",
     "/workbench-audit, CLI 'ion verify-ledger'"],
    ["UC-LR-01", "Complete a curriculum module", "Learner",
     "Course assigned (or self-enrolled)",
     "Curriculum progress tracked; certificate or badge if applicable",
     "/training, /courses, /guide, /guide/sim, /guide/range"],
    ["UC-LR-02", "Assign training to a team member", "SOC Manager",
     "Learner identified",
     "Assignment persisted; deadline tracked",
     "/courses, /dashboard"],
    ["UC-CO-01", "Respond to a SAR", "DPO / Admin",
     "SAR received from data subject",
     "SAR-ready data extracted; UK GDPR Art. 15 obligation met",
     "/admin/sar, DPIA Appendix A SQL"],
    ["UC-CO-02", "Process an Erasure request", "DPO / Admin",
     "Erasure validated as legal under UK GDPR Art. 17",
     "Personal identifiers removed; operational artefacts retained as anonymised",
     "/admin/erasure, DPIA Appendix B SQL"],
    # ── v1.1 additions ───────────────────────────────────────────────
    ["UC-TI-01", "Generate the daily threat briefing", "Threat Intel Analyst",
     "OpenCTI integration enabled; threat data current",
     "Daily briefing distributed; visible in /briefing next shift",
     "/threat-landscape, /executive-report"],
    ["UC-TI-02", "Actor deep-dive + coverage gap", "Threat Intel Analyst",
     "Actor of interest identified",
     "Coverage gap registered; tuning proposal filed if applicable",
     "/threat-intel, actor profile, /cyab/attack-heatmap, /tuning-proposals"],
    ["UC-OP-01", "Deploy a new ION instance", "Operator / SRE",
     "Customer infrastructure provisioned; secrets in customer secrets-management",
     "ION operational; monitoring picks up health; first login works",
     "/health, /login, docs/DEPLOYMENT.md"],
    ["UC-OP-02", "DR drill: restore from backup", "Operator / SRE",
     "Postgres backup <= 24h old; image artefact accessible",
     "Service restored; DR drill evidence captured for _mod_iteap.md S5",
     "/health, /cases, /workbench-audit"],
    ["UC-OP-03", "Investigate a slow-query alarm", "Operator / SRE",
     "Customer monitoring fired on slow-query log row",
     "Root cause documented; tuning applied; alarm cleared",
     "/admin/health-detail, /settings, SIEM trace"],
    ["UC-AI-01", "Ask Bob about ION's data", "Any analyst",
     "Ollama enabled; AI chat surface accessible",
     "Question answered with provenance; conversation persisted per user",
     "/ai-chat, case detail (chat panel)"],
    ["UC-AI-02", "Natural-language to Elasticsearch query", "Detection Engineer / L2/L3 Analyst",
     "ES Security adapter configured; Ollama enabled",
     "Query executed; saved-search optionally created",
     "AI-chat surface, /discover"],
    ["UC-NET-01", "Review log source health before tuning a noisy rule", "Detection Engineer",
     "Log Source Health page populated",
     "Root cause clarified; ticket filed against source not rule",
     "/log-source-health, /tuning-proposals"],
    ["UC-EM-01", "Run an emulation plan", "Detection Engineer",
     "Emulation plan selected; permission to run in customer environment",
     "Detection coverage measured; gaps tracked for closure",
     "/emulation, /tuning-proposals"],
    ["UC-CA-01", "Tripped canary token", "L1/L2 Analyst (consumer); DE (planner)",
     "Canary tokens deployed; tripped event captured",
     "Canary-trip handled with high-fidelity response",
     "/canaries, /cases/{id}, suggested playbook"],
    ["UC-API-01", "Forward case-create to customer ITSM", "Admin / Customer Integrations Team",
     "Webhook URL configured; HMAC secret set",
     "Customer ITSM has the ticket; delivery is auditable",
     "/integrations, /admin/webhook-log"],
]


# ─────────────────────────────────────────────────────────────────────
# 5. _mod_compliance_mapping.csv  —  RAG status across MOD requirements
# ─────────────────────────────────────────────────────────────────────
COMP_HEADER = ["Row", "MOD Requirement", "ION Position", "RAG", "Evidence", "Owner", "Action Required"]
COMP_ROWS = [
    ["1", "Application registered in DART/CAAT", "Submission body authored; STO to file",
     "Amber", "_mod_app_register_submission.md", "Customer STO", "File the submission via customer portal"],
    ["2", "SRO assigned", "Not yet assigned",
     "Amber", "Pre-Service-Transition gate", "Customer", "Assign SRO before go-live"],
    ["3", "STO assigned", "Not yet assigned",
     "Amber", "Service Transition brief authored", "Customer", "Assign STO; brief at handover"],
    ["4", "DBDA / DA-chair review", "Submission body authored; DA chair to review",
     "Amber", "_mod_architecture_governance.md", "Customer DA", "Convene Architecture Review Board"],
    ["5", "Integrated Test, Evaluation & Acceptance Plan (ITEAP)", "Authored",
     "Green", "_mod_iteap.md", "Maintainer + Customer", "Customer schedules ITHC + DR drill + BC drill"],
    ["6", "Independent Test of Hostile Conformance (ITHC)", "Recommended pre-go-live; not yet scheduled",
     "Amber", "_mod_iteap.md S4", "Customer", "Schedule with chosen ITHC supplier"],
    ["7", "DPIA (UK GDPR Art. 35)", "Authored; lawful basis Art. 6(1)(e); 11-row risk register",
     "Green", "_mod_dpia.md", "Maintainer + Customer DPO", "Customer DPO countersigns"],
    ["8", "Safety-Benign Software Questionnaire (DefStan 00-055 / JSP 935/936)", "Completed; verdict SIL-0 / DAL-E",
     "Green", "_mod_safety_questionnaire.md", "Maintainer + Customer SRO", "Re-assessment triggers documented"],
    ["9", "ISA (Independent Safety Auditor)", "Not required (Safety-Benign verdict)",
     "Green", "_mod_safety_questionnaire.md Q13", "n/a", "None"],
    ["10", "WCAG 2.2 AA accessibility audit", "Tier-1 + Tier-2 conformant; Tier-3/4 remediation plan",
     "Red", "_mod_wcag_audit.md", "Maintainer", "Ship tier-3 remediation v0.30.0, tier-4 v0.31.0"],
    ["11", "Through-Life Management Plan", "Authored",
     "Green", "_mod_through_life_plan.md", "Maintainer + Customer SDM", "SDM accepts at handover"],
    ["12", "Patching cadence + CVE SLA", "Tier 2 Standard support; SLAs documented",
     "Green", "_mod_through_life_plan.md S3", "Maintainer", "None"],
    ["13", "JSP 892 Exception Register", "Authored; zero open exceptions at v0.29.1",
     "Green", "_mod_exception_register.md", "Maintainer", "Maintain on each release"],
    ["14", "Log shipping to customer SIEM (ECS)", "Authored",
     "Green", "_mod_log_shipping_spec.md", "Customer SIEM team", "Configure pipeline at deployment"],
    ["15", "Tamper-evident audit trail", "Workbench ledger (sha256 chain)",
     "Green", "project_ion_workbench.md; CaseEvidenceLedger", "Maintainer", "None"],
    ["16", "RBAC + service-internal auth checks", "7-tier RBAC; endpoint + service defence-in-depth",
     "Green", "feedback_service_check_before_commit.md; docs/HLD.md AD-06", "Maintainer", "None"],
    ["17", "SBOM (SPDX-JSON) in image", "Bundled at /app/sbom.spdx.json",
     "Green", "syft 1.18.1 in CI", "Maintainer", "None"],
    ["18", "Supply-chain audit (pip-audit + bandit + ruff)", "CI on every commit",
     "Green", ".github/workflows/test.yml", "Maintainer", "None"],
    ["19", "Container image immutability", "Docker Hub digest-pinned",
     "Green", "Docker Hub tag policy", "Maintainer", "None"],
    ["20", "Container image signing (cosign / Sigstore)", "Not implemented",
     "Amber", "_mod_exception_register.md cand. EX-002", "Maintainer", "Tracked v0.31.0+; no exception filed"],
    ["21", "OIDC RS256-only auth", "HS256 explicitly refused at verification",
     "Green", "auth/oidc.py", "Maintainer", "None"],
    ["22", "Air-gap deployment", "Bundled ATT&CK + KEV; local Ollama; no live feeds",
     "Green", "feedback_ion_airgap_deployment.md; project_ion_kev_design.md", "Maintainer", "None"],
    ["23", "Customer-agnostic core + per-customer overlay docs", "_mod_*.md family local-only; public docs neutral",
     "Green", "reference_ion_sdlc.md; .gitignore", "Maintainer", "None"],
    ["24", "Design Passport", "Authored; gates open pending customer-side completion",
     "Green", "_mod_design_passport.md", "Maintainer + Customer SRO + DA chair", "Countersign at each gate"],
]


# ─────────────────────────────────────────────────────────────────────
# 6. _mod_exception_register.csv  —  zero open + template
# ─────────────────────────────────────────────────────────────────────
EX_HEADER = ["EX ID", "Filed", "Filed by", "MOD requirement", "Gap statement", "Residual likelihood", "Residual impact", "Risk rating", "Mitigation", "Hard expiry", "Maintainer signature", "STO signature", "SRO signature", "DA chair signature", "Status"]
EX_ROWS = [
    # No open exceptions at v0.29.1 — header-only file communicates "zero open"
    # Anticipated future candidates listed for visibility:
    ["EX-CAND-001", "(not filed)", "Maintainer (forward-looking)",
     "WCAG 2.2 AA on /topology + /architecture admin pages",
     "SVG-heavy infra diagrams lack alt-text and aren't keyboard-navigable",
     "Low", "Minor", "Green",
     "Pages are engineer-internal, admin-gated, non-public-facing; remediation plan sized L in _mod_wcag_audit.md",
     "v0.30.0", "", "", "", "",
     "Candidate (not filed - may be needed if remediation slips)"],
    ["EX-CAND-002", "(not expected)", "Maintainer (forward-looking)",
     "Container image signing (cosign / Sigstore)",
     "Image immutability via Docker Hub digest; no Sigstore signature",
     "Very low", "Minor", "Green",
     "Image-tag immutability via Docker Hub; SBOM in image; not a MOD must-have at this tier",
     "n/a", "", "", "", "",
     "Candidate (not expected to require filing)"],
    ["EX-CAND-003", "(already documented)", "Maintainer",
     "python-jose CVE-2024-23342",
     "python-jose retained pending PyJWT migration",
     "Very low", "Minor", "Green",
     "--ignore-vuln CVE-2024-23342 documented in CI workflow; PyJWT migration planned",
     "n/a", "", "", "", "",
     "Documented in pip-audit workflow; no separate filing needed"],
]


# ─────────────────────────────────────────────────────────────────────
# 7. _mod_wcag_findings.csv  —  tiered findings + remediation
# ─────────────────────────────────────────────────────────────────────
WCAG_HEADER = ["Finding ID", "Tier", "Page / Surface", "WCAG Criterion", "Severity", "Effort", "Target version", "Status", "Notes"]
WCAG_ROWS = [
    ["WCAG-T1-OK", "Tier-1 (high-frequency)", "/alerts, /cases, /forensics, /briefing", "Multiple AA criteria", "None", "n/a", "n/a", "Conformant",
     "Audit pass; semantic HTML; ARIA landmarks; keyboard nav verified"],
    ["WCAG-T2-001", "Tier-2", "/training, /courses lesson pages", "1.4.3 Contrast (Minimum)", "Minor", "S", "v0.30.0", "Planned",
     "Some long-form text uses muted body grey just under 4.5:1 ratio"],
    ["WCAG-T2-002", "Tier-2", "/threat-intel actor profile sparkline", "1.4.11 Non-text Contrast", "Minor", "S", "v0.30.0", "Planned",
     "Sparkline line colour below 3:1 against panel background"],
    ["WCAG-T2-003", "Tier-2", "/cyab/attack-heatmap", "1.3.1 Info & Relationships", "Minor", "M", "v0.30.0", "Planned",
     "Heatmap cells need ARIA labels with technique name + coverage state"],
    ["WCAG-T3-001", "Tier-3", "/integrations CRUD form", "3.3.2 Labels or Instructions", "Minor", "S", "v0.30.0", "Planned",
     "Some inline help text needs aria-describedby wiring"],
    ["WCAG-T3-002", "Tier-3", "/audit-log filter UI", "2.4.6 Headings and Labels", "Minor", "S", "v0.30.0", "Planned",
     "Filter section needs heading element above the filter row"],
    ["WCAG-T3-003", "Tier-3", "/users role-assignment table", "4.1.3 Status Messages", "Minor", "S", "v0.30.0", "Planned",
     "Async role-change confirmation needs aria-live region"],
    ["WCAG-T4-001", "Tier-4 (admin / SVG-heavy)", "/topology infra diagram", "1.1.1 Non-text Content", "Moderate", "L", "v0.31.0", "Planned",
     "SVG diagram needs alt-text + accessible alternative table representation"],
    ["WCAG-T4-002", "Tier-4 (admin / SVG-heavy)", "/architecture system diagram", "1.1.1 Non-text Content", "Moderate", "L", "v0.31.0", "Planned",
     "SVG diagram needs alt-text + accessible alternative; candidate for EX-CAND-001 if slips"],
    ["WCAG-T4-003", "Tier-4 (admin / SVG-heavy)", "/topology + /architecture", "2.1.1 Keyboard", "Moderate", "L", "v0.31.0", "Planned",
     "Diagram pan/zoom not currently keyboard-navigable"],
]


# ─────────────────────────────────────────────────────────────────────
# 8. _mod_dpia_risks.csv  —  11-row privacy risk register
# ─────────────────────────────────────────────────────────────────────
DPIA_HEADER = ["Risk ID", "Description", "Likelihood", "Impact", "Inherent Rating", "Mitigation", "Residual Likelihood", "Residual Impact", "Residual Rating", "Owner"]
DPIA_ROWS = [
    ["DPIA-R-01", "Unauthorised access to analyst PII in audit_log",
     "Low", "Moderate", "Amber",
     "RBAC gated; audit:read permission required; bcrypt + slowapi on auth",
     "Very low", "Moderate", "Green", "Customer DPO"],
    ["DPIA-R-02", "PII leakage via Bob LLM (prompt reads sensitive data)",
     "Low", "Moderate", "Amber",
     "Bob runs against local Ollama (no SaaS LLM); ION_PII_ANON_ENABLED toggle available; reasoning_text storage gated",
     "Very low", "Moderate", "Green", "Customer DPO"],
    ["DPIA-R-03", "Audit log retention exceeds legitimate purpose",
     "Medium", "Minor", "Amber",
     "Retention configurable; documented in _mod_dpia.md S4; customer policy applies",
     "Low", "Minor", "Green", "Customer DPO"],
    ["DPIA-R-04", "Subject Access Request not fulfillable",
     "Low", "Major", "Amber",
     "SAR SQL in DPIA Appendix A; /admin/sar UI; tested",
     "Very low", "Major", "Green", "Customer DPO"],
    ["DPIA-R-05", "Erasure request not actionable",
     "Low", "Major", "Amber",
     "Erasure SQL in DPIA Appendix B; /admin/erasure UI; tested",
     "Very low", "Major", "Green", "Customer DPO"],
    ["DPIA-R-06", "Cross-border data transfer (when customer ships logs to non-UK SIEM)",
     "Medium", "Moderate", "Amber",
     "ECS logs configurable; customer log-shipper decides destination; out of ION's control",
     "Medium", "Moderate", "Amber",
     "Customer DPO + SIEM team"],
    ["DPIA-R-07", "Backup retention not purged on erasure",
     "Medium", "Moderate", "Amber",
     "Customer-side backup policy; flagged in DPIA S5; recommendation: re-erase on next backup restore",
     "Low", "Moderate", "Green",
     "Customer ops"],
    ["DPIA-R-08", "Analyst notes contain incidental PII not subject to standard erasure",
     "Medium", "Minor", "Amber",
     "Notes are part of erasure query; documented",
     "Low", "Minor", "Green", "Customer DPO"],
    ["DPIA-R-09", "Tamper-evident ledger contains references to subjects",
     "Medium", "Minor", "Amber",
     "Ledger hashes payloads; payloads include subject references; erasure path anonymises payload while preserving chain integrity",
     "Low", "Minor", "Green", "Customer DPO"],
    ["DPIA-R-10", "Insider misuse of audit data",
     "Low", "Major", "Amber",
     "RBAC; audit_log records audit-log reads; quarterly access review",
     "Very low", "Major", "Green", "Customer ops"],
    ["DPIA-R-11", "Bob reasoning_text leakage if ION_BOB_STORE_REASONING enabled",
     "Low", "Moderate", "Amber",
     "Storage gated by env var; retained for DE review; same RBAC as audit_log",
     "Very low", "Moderate", "Green", "Customer DPO"],
]


# ─────────────────────────────────────────────────────────────────────
# 9. _mod_design_passport_risks.csv  —  consolidated cross-domain
# ─────────────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────────────
# 10. _mod_iar.csv  —  32-row Information Asset Register
# ─────────────────────────────────────────────────────────────────────
IAR_HEADER = ["Asset ID", "Asset", "Category", "Classification", "Storage", "Retention", "Lawful basis", "Owner", "Disposal"]
IAR_ROWS = [
    ["IAR-001", "User accounts", "PII (analyst metadata)", "OFFICIAL", "Postgres users table", "Lifetime of employment + 7 yrs", "Art 6(1)(b) contract + Art 6(1)(c) legal obligation", "Customer HR / IT", "/admin/erasure on leaver"],
    ["IAR-002", "Password hashes", "Auth secret", "OFFICIAL", "Postgres users.password_hash (bcrypt)", "While user active", "Art 6(1)(b)", "Customer IT", "Wiped at user deletion"],
    ["IAR-003", "Session cookies", "Auth state", "OFFICIAL", "Server memory (in-process)", "Until expiry / logout", "Art 6(1)(b)", "Customer IT", "Process restart wipes"],
    ["IAR-004", "Audit log rows", "Audit / governance", "OFFICIAL", "Postgres audit_log", "Indefinite in-DB; SIEM-side per customer policy", "Art 6(1)(c) + Art 6(1)(e)", "Customer SOC + Compliance", "SQL anonymisation per DPIA App B"],
    ["IAR-005", "Alert cache", "Operational metadata", "OFFICIAL", "Postgres alert_cache", "90 days rolling", "Art 6(1)(e)", "Customer SOC", "Rolling window expiry"],
    ["IAR-006", "Investigation cases", "SOC case data", "OFFICIAL", "Postgres investigations", "Indefinite", "Art 6(1)(e)", "Customer SOC", "Per customer policy"],
    ["IAR-007", "Case workbench pins", "Pinned evidence", "OFFICIAL", "Postgres case_evidence_pins + filesystem", "Indefinite", "Art 6(1)(e)", "Customer SOC", "Anonymise on erasure"],
    ["IAR-008", "Case evidence ledger", "Tamper-evident audit chain", "OFFICIAL", "Postgres case_evidence_ledger", "Indefinite (immutable)", "Art 6(1)(c)", "Customer Compliance", "Payload anonymisation only"],
    ["IAR-009", "Forensic cases", "Forensic case data", "OFFICIAL - SENSITIVE", "Postgres forensic_cases", "Per customer DFIR policy (7+ yrs)", "Art 6(1)(c) + 6(1)(e)", "Customer DFIR / Legal", "Per customer DFIR policy"],
    ["IAR-010", "Evidence items + custody log", "Forensic evidence + chain of custody", "OFFICIAL - SENSITIVE", "Postgres + filesystem (binaries)", "Per customer DFIR policy", "Art 6(1)(c)", "Customer DFIR / Legal", "Per customer DFIR policy"],
    ["IAR-011", "Observables (IOCs)", "Threat intelligence indicators", "OFFICIAL", "Postgres observables", "365 days; staleness flagged at 30", "Art 6(1)(e)", "Customer Threat Intel", "Rolling expiry"],
    ["IAR-012", "Bob verdicts", "AI analyst decision-support outputs", "OFFICIAL", "Postgres ai_feedback", "Indefinite (training quality)", "Art 6(1)(e)", "Customer Detection Engineering", "Anonymise on erasure"],
    ["IAR-013", "Bob reasoning text", "AI verdict explanation (gated)", "OFFICIAL", "Postgres ai_feedback.reasoning_text", "Indefinite when stored", "Art 6(1)(e)", "Customer DE", "Anonymise on erasure"],
    ["IAR-014", "Alert prompt templates", "Detection content", "OFFICIAL", "Postgres alert_prompt_templates", "Indefinite (versioned)", "Art 6(1)(e)", "Customer DE", "Version history retained; soft-delete"],
    ["IAR-015", "Bob eval data", "AI eval P/R/F1", "OFFICIAL", "Postgres bob_eval_* tables", "Indefinite", "Art 6(1)(e)", "Customer DE", "Per template lifecycle"],
    ["IAR-016", "Case embeddings (pgvector)", "ML embeddings", "OFFICIAL", "Postgres case_embeddings", "Same as parent case", "Art 6(1)(e)", "Customer SOC", "Cascade-delete with case"],
    ["IAR-017", "PCAP findings", "Network-capture analysis results", "OFFICIAL - SENSITIVE", "Postgres pcap_findings + filesystem", "Case lifetime", "Art 6(1)(c) + 6(1)(e)", "Customer SOC + Network team", "Cascade-delete with case"],
    ["IAR-018", "Playbook execution log", "SOC action attribution", "OFFICIAL", "Postgres playbook_action_logs", "Indefinite", "Art 6(1)(c)", "Customer SOC + Compliance", "Anonymise on erasure"],
    ["IAR-019", "Tuning proposals", "Detection-engineering proposals", "OFFICIAL", "Postgres tuning_proposals", "Indefinite (audit trail)", "Art 6(1)(e)", "Customer DE", "Soft-delete"],
    ["IAR-020", "Settings", "Per-deployment configuration", "OFFICIAL", "Postgres settings table", "Lifecycle of deployment", "Art 6(1)(b)", "Customer Admin", "Wiped on decommission"],
    ["IAR-021", "Integration credentials", "Auth secrets for upstream", "OFFICIAL - SECRET", "Customer secrets-management (NOT in Postgres)", "Per customer rotation policy", "Art 6(1)(b)", "Customer SecOps", "Per customer policy"],
    ["IAR-022", "Notes (analyst working notes)", "Free-text analyst notes", "OFFICIAL", "Postgres analyst_notes", "Indefinite", "Art 6(1)(e)", "Customer SOC", "Anonymise on erasure"],
    ["IAR-023", "Documents + templates", "Reference content", "OFFICIAL", "Postgres documents + templates", "Indefinite (versioned)", "Art 6(1)(e)", "Customer SOC", "Soft-delete"],
    ["IAR-024", "Knowledge-base embeddings", "ML embeddings of KB content", "OFFICIAL", "Postgres kb_document_embeddings", "Same as parent doc", "Art 6(1)(e)", "Customer SOC", "Cascade-delete"],
    ["IAR-025", "Network assets / CMDB", "Customer network topology", "OFFICIAL - SENSITIVE", "Postgres network_assets", "Lifecycle of deployment", "Art 6(1)(e)", "Customer Network", "Customer-controlled"],
    ["IAR-026", "Log source registry", "List of customer log sources", "OFFICIAL", "Postgres log_sources", "Lifecycle of deployment", "Art 6(1)(e)", "Customer SOC", "Customer-controlled"],
    ["IAR-027", "Course / Lesson progress", "Per-user learning progress", "OFFICIAL", "Postgres course_progress etc.", "Lifetime of user + 2 yrs", "Art 6(1)(b)", "Customer HR", "Anonymise on leaver"],
    ["IAR-028", "CyAB assessments", "Maturity-assessment data", "OFFICIAL", "Postgres cyab_* tables", "Indefinite (historical record)", "Art 6(1)(e)", "Customer SOC Manager", "Customer-controlled"],
    ["IAR-029", "Canary tokens", "High-fidelity-trip tokens", "OFFICIAL - SENSITIVE", "Postgres canaries", "Active + 30 days post-decommission", "Art 6(1)(e)", "Customer DE", "Soft-delete"],
    ["IAR-030", "Webhook delivery log", "Outbound webhook delivery records", "OFFICIAL", "Postgres webhook_delivery_log", "90 days rolling", "Art 6(1)(c)", "Customer Admin", "Rolling expiry"],
    ["IAR-031", "Threat-intel actor profiles (cached)", "OpenCTI-derived TI data", "OFFICIAL", "Postgres threat_intel_* cache tables", "30 days rolling refresh", "Art 6(1)(e)", "Customer Threat Intel", "Rolling refresh"],
    ["IAR-032", "Bundled ATT&CK + KEV snapshots", "Reference data", "OFFICIAL", "Filesystem data/attack/ data/kev/", "Per release version", "n/a (public reference data)", "Maintainer", "Replaced at each release"],
]


# ─────────────────────────────────────────────────────────────────────
# 11. _mod_ion_incident_response_triggers.csv  —  12 IR trigger scenarios
# ─────────────────────────────────────────────────────────────────────
IR_HEADER = ["Scenario ID", "Trigger", "Detection signal", "Default severity", "Per-trigger playbook section"]
IR_ROWS = [
    ["IR-S-01", "Authentication bypass detected", "Audit log shows non-attributed mutating actions; bypassed OIDC flow", "P1 Critical", "S5.1"],
    ["IR-S-02", "RBAC escalation detected", "Audit log shows action without corresponding permission", "P1 Critical", "S5.2"],
    ["IR-S-03", "Workbench ledger tamper", "Periodic ledger-chain verification fails (/workbench-audit)", "P2 High", "S5.3"],
    ["IR-S-04", "DB-direct write detected", "DB-side audit reconciliation finds row mutation without matching audit_log", "P2 High", "S5.4"],
    ["IR-S-05", "Supply-chain compromise (CVE in active dependency)", "pip-audit / CISA KEV / NVD alert on ION dependency", "P2 High", "S5.5"],
    ["IR-S-06", "Image tampering", "Docker Hub digest hash mismatch on customer's pulled image", "P2 High", "S5.6"],
    ["IR-S-07", "Ollama RCE / pivot", "Anomalous outbound network from Ollama; Bob output schema violations spike", "P2 High", "S5.7"],
    ["IR-S-08", "Massive data exfiltration", "Outbound traffic spike from ION; large query patterns in DB", "P1 Critical", "S5.8"],
    ["IR-S-09", "Bob prompt-injection campaign", "PI patterns in alert content; Bob confidence drop; circuit-breaker fires en masse", "P2 High (or P3)", "S5.9"],
    ["IR-S-10", "Integration credentials leaked", "Credential observed in public dump; integration-side anomaly", "P2 High", "S5.10"],
    ["IR-S-11", "Critical CVE in ION code", "CVE published or responsibly disclosed against ION", "P2 High", "S5.11"],
    ["IR-S-12", "Denial of service", "ION worker pool exhausted; Postgres pool exhausted; /health returning 5xx", "P2 High (or P3)", "S5.12"],
]


DPR_HEADER = ["Risk ID", "Risk", "Severity", "Owner", "Mitigation", "Source"]
DPR_ROWS = [
    ["R-ARCH-01", "Single-maintainer supply", "Medium", "Customer + Maintainer",
     "MIT license; comprehensive docs; SBOM in image", "docs/HLD.md S10"],
    ["R-ARCH-02", "Bob LLM availability", "Low", "Customer",
     "Bob fails open; cases unaffected", "docs/HLD.md S10"],
    ["R-ARCH-03", "Bundled ATT&CK staleness", "Low", "Maintainer",
     "Refreshed every release", "_mod_compliance_mapping.md"],
    ["R-SEC-01", "Image not signed (cosign)", "Low", "Maintainer",
     "Image-tag immutability via Docker Hub digest",
     "_mod_exception_register.md cand. EX-002"],
    ["R-SAFE-00", "(none - Safety-Benign verdict)", "n/a", "n/a", "n/a",
     "_mod_safety_questionnaire.md"],
    ["R-PRIV-01", "Operational misuse of audit data", "Very Low", "Customer DPO",
     "RBAC-gated audit_log; SAR procedure", "_mod_dpia.md S5"],
    ["R-A11Y-01", "Tier-3/4 WCAG remediation", "Low", "Maintainer",
     "Remediation plan v0.30.0-v0.31.0", "_mod_wcag_audit.md"],
    ["R-OPS-01", "Operator unfamiliarity at first deploy", "Low", "Customer STO",
     "Service Transition brief at handover", "_mod_service_transition.md"],
    ["R-OPS-02", "Lab fixture system bugs", "Low", "Maintainer",
     "Documented; queued v0.30.0", "_backlog_v0_27.md"],
]


# ─────────────────────────────────────────────────────────────────────
# main
# ─────────────────────────────────────────────────────────────────────
def main() -> int:
    targets = [
        (ROOT / "docs" / "USER_REQUIREMENTS.csv", URD_HEADER, URD_ROWS),
        (ROOT / "docs" / "TRACEABILITY.csv", RTM_HEADER, RTM_ROWS),
        (ROOT / "docs" / "TRACEABILITY_SR.csv", SR_HEADER, SR_ROWS),
        (ROOT / "docs" / "USE_CASES.csv", UC_HEADER, UC_ROWS),
        (ROOT / "_mod_compliance_mapping.csv", COMP_HEADER, COMP_ROWS),
        (ROOT / "_mod_exception_register.csv", EX_HEADER, EX_ROWS),
        (ROOT / "_mod_wcag_findings.csv", WCAG_HEADER, WCAG_ROWS),
        (ROOT / "_mod_dpia_risks.csv", DPIA_HEADER, DPIA_ROWS),
        (ROOT / "_mod_design_passport_risks.csv", DPR_HEADER, DPR_ROWS),
        (ROOT / "_mod_iar.csv", IAR_HEADER, IAR_ROWS),
        (ROOT / "_mod_ion_incident_response_triggers.csv", IR_HEADER, IR_ROWS),
    ]
    for path, header, rows in targets:
        write_csv(path, header, rows)
    print(f"\nbuilt {len(targets)} CSV file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
