"""Build the export/ directory — a categorised bundle ready for ZIP + send.

Layout:
    export/
    +-- 00_START_HERE.md
    +-- MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/
    |   +-- 00_start_here/             (manifest + parent indexes)
    |   +-- 01_governance/             (acceptance gates + transition)
    |   +-- 02_compliance/             (DPIA, IAR, safety, WCAG, logs)
    |   +-- 03_security/               (threat model, IR plan, ITHC template, ITEAP)
    |   +-- csv_editable/              (reviewer-editable CSVs)
    +-- PUBLIC_SHAREABLE/
        +-- 01_design/                 (HLD, LLD, ARCHITECTURE, API)
        +-- 02_requirements_and_use_cases/ (URD, RTM, UCs, GAPS)
        +-- 03_operations/             (DEPLOY, RUNBOOK, BACKUP, CONFIG, CAPACITY, VULN)
        +-- 04_security/               (CRYPTOGRAPHY, AI_OUTPUT_CONTRACT)
        +-- 05_briefs/                 (STACK_BRIEF, SOC_TEMPLATES, CyAB_SAL)
        +-- 06_process/                (DEVELOPMENT_LIFECYCLE)
        +-- 07_project/                (README, SETUP, STACK, CHANGELOG, SECURITY_ASSESSMENT)
        +-- csv_editable/              (URD, RTM, SR, UC)

Usage:
    python tools/pdf_build/build_export.py
    python tools/pdf_build/build_export.py --clean   # delete existing export/ first
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
EXPORT_DIR = ROOT / "export"

# Per-folder file list. Paths are relative to ROOT.
LAYOUT: dict[str, list[str]] = {
    # ── MOD-LOCAL (customer-internal) ──────────────────────────────────
    "MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/00_start_here": [
        "_mod_bundle_manifest.pdf",
        "_mod_compliance_mapping.pdf",
        "_mod_design_passport.pdf",
    ],
    "MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/01_governance": [
        "_mod_app_register_submission.pdf",
        "_mod_architecture_governance.pdf",
        "_mod_service_transition.pdf",
        "_mod_exception_register.pdf",
        "_mod_through_life_plan.pdf",
        "_mod_golive.pdf",
        "_mod_knowledge_transfer.pdf",
    ],
    "MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/02_compliance": [
        "_mod_dpia.pdf",
        "_mod_iar.pdf",
        "_mod_safety_questionnaire.pdf",
        "_mod_wcag_audit.pdf",
        "_mod_log_shipping_spec.pdf",
    ],
    "MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/03_security": [
        "_mod_threat_model.pdf",
        "_mod_ion_incident_response.pdf",
        "_mod_ithc_findings_template.pdf",
        "_mod_iteap.pdf",
    ],
    "MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/csv_editable": [
        "_mod_compliance_mapping.csv",
        "_mod_dpia_risks.csv",
        "_mod_exception_register.csv",
        "_mod_wcag_findings.csv",
        "_mod_design_passport_risks.csv",
        "_mod_iar.csv",
        "_mod_ion_incident_response_triggers.csv",
    ],
    # ── PUBLIC SHAREABLE ───────────────────────────────────────────────
    "PUBLIC_SHAREABLE/01_design": [
        "docs/HLD.pdf",
        "docs/LLD.pdf",
        "docs/ARCHITECTURE.pdf",
        "docs/API.pdf",
    ],
    "PUBLIC_SHAREABLE/02_requirements_and_use_cases": [
        "docs/USER_REQUIREMENTS.pdf",
        "docs/TRACEABILITY.pdf",
        "docs/USE_CASES.pdf",
        "docs/GAPS_FILLED.pdf",
    ],
    "PUBLIC_SHAREABLE/03_operations": [
        "docs/DEPLOYMENT.pdf",
        "docs/RUNBOOK.pdf",
        "docs/BACKUP_RESTORE.pdf",
        "docs/CONFIG_MGMT.pdf",
        "docs/CAPACITY.pdf",
        "docs/VULN_MGMT.pdf",
    ],
    "PUBLIC_SHAREABLE/04_security": [
        "docs/CRYPTOGRAPHY.pdf",
        "docs/AI_OUTPUT_CONTRACT.pdf",
    ],
    "PUBLIC_SHAREABLE/05_briefs": [
        "docs/ION_STACK_BRIEF.pdf",
        "docs/SOC_TEMPLATES.pdf",
        "docs/CyAB_SAL.pdf",
    ],
    "PUBLIC_SHAREABLE/06_process": [
        "docs/DEVELOPMENT_LIFECYCLE.pdf",
    ],
    "PUBLIC_SHAREABLE/07_project": [
        "README.pdf",
        "SETUP.pdf",
        "STACK.pdf",
        "CHANGELOG.pdf",
        "SECURITY_ASSESSMENT.pdf",
    ],
    "PUBLIC_SHAREABLE/csv_editable": [
        "docs/USER_REQUIREMENTS.csv",
        "docs/TRACEABILITY.csv",
        "docs/TRACEABILITY_SR.csv",
        "docs/USE_CASES.csv",
    ],
}


TOP_README = """# ION Documentation Export

Generated by `tools/pdf_build/build_export.py` from the in-repo markdown sources.

## Two top-level folders — match them to your distribution channel

### `MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/`
Compliance + governance artefacts authored as customer-internal overlays.
**Never publish these to a public channel.** They reference the customer's
specific compliance regime (MOD application policy, JSP framework, DefStan).

| Subfolder | Contents |
|---|---|
| `00_start_here/` | The bundle manifest + compliance mapping + design passport — read these first |
| `01_governance/` | Application register, architecture-governance submission, service transition, exception register, through-life plan, go-live plan, knowledge transfer |
| `02_compliance/` | DPIA, Information Asset Register, Safety-Benign questionnaire, WCAG audit, SIEM log-shipping spec |
| `03_security/` | Threat model, ION incident response plan, ITHC findings template, ITEAP |
| `csv_editable/` | Reviewer-editable working copies (Excel-ready) |

### `PUBLIC_SHAREABLE/`
Customer-agnostic engineering documentation. Safe to publish, share with
external integrators, link from public docs, include in vendor evaluations.

| Subfolder | Contents |
|---|---|
| `01_design/` | HLD, LLD, original architecture reference, API reference |
| `02_requirements_and_use_cases/` | User requirements (81 numbered URs), traceability matrix, use cases (33 UCs), gaps filled |
| `03_operations/` | Deployment, runbook, backup/restore, configuration management, capacity, vulnerability management |
| `04_security/` | Cryptographic inventory, AI output contract (Bob safety boundary) |
| `05_briefs/` | Stack brief (vs current customer state), SOC templates, CyAB SAL reference |
| `06_process/` | Secure-by-Design development lifecycle |
| `07_project/` | README, setup, stack reference, full changelog, per-release security assessment |
| `csv_editable/` | Reviewer-editable working copies (Excel-ready) |

## How to use

**To deliver to a customer for acceptance review:**
1. Verify the bundle manifest covers all the docs they need
2. Send `MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/` via the customer's encrypted channel
3. Send `PUBLIC_SHAREABLE/` via standard channel

**To regenerate this export folder:**
```
python tools/pdf_build/build_docs.py --add-mod-set   # rebuild all PDFs
python tools/pdf_build/build_csv.py                  # rebuild all CSVs
python tools/pdf_build/build_export.py --clean       # rebuild this folder
```

**To open the master index PDF first:**
`MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/00_start_here/_mod_bundle_manifest.pdf`

## Classification reminder

| Folder | Classification | Channel |
|---|---|---|
| `MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/` | OFFICIAL — MOD INTERNAL | Customer's encrypted channel ONLY |
| `PUBLIC_SHAREABLE/` | PUBLIC (or CUSTOMER FACING for ION_STACK_BRIEF) | Any standard channel |

The supplier's public GitHub repo holds the **markdown sources** for the
`PUBLIC_SHAREABLE/` set. The `MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY/` set is
explicitly excluded from the public repo via `.gitignore`.
"""


MOD_README = """# MOD-local compliance pack

**Classification: OFFICIAL — MOD INTERNAL**

Never publish to a public channel. Deliver only via the customer's encrypted
channel (per customer information-security policy).

## Read order

1. `00_start_here/_mod_bundle_manifest.pdf` — master inventory of every document
2. `00_start_here/_mod_compliance_mapping.pdf` — RAG status against MOD application
   policy requirements
3. `00_start_here/_mod_design_passport.pdf` — gate-by-gate acceptance artefact

Each subsequent folder covers a specific compliance dimension (governance,
compliance, security). The manifest cross-references every doc.

## Audience by folder

| Folder | Primary audience |
|---|---|
| `00_start_here/` | SRO, STO, DA chair (overview) |
| `01_governance/` | STO, SDM, DA chair, SRO |
| `02_compliance/` | DPO, accessibility owner, SIEM team |
| `03_security/` | Security lead, ITHC supplier, SOC manager |
| `csv_editable/` | Any reviewer marking up findings + signatures |
"""


PUBLIC_README = """# Public ION engineering documentation

**Classification: PUBLIC**

Safe to share externally. Customer-agnostic content. The markdown sources for
these docs are on the public GitHub repo (`ixion36-svg/ion`).

## Read order (depending on role)

| Role | Start with |
|---|---|
| Buyer / SOC leader | `05_briefs/ION_STACK_BRIEF.pdf` + `02_requirements_and_use_cases/GAPS_FILLED.pdf` |
| Architect | `01_design/HLD.pdf` + `01_design/LLD.pdf` |
| Integration engineer | `01_design/API.pdf` + `03_operations/DEPLOYMENT.pdf` |
| Customer DA reviewer | `01_design/HLD.pdf` + `02_requirements_and_use_cases/TRACEABILITY.pdf` |
| Customer security | `04_security/CRYPTOGRAPHY.pdf` + `07_project/SECURITY_ASSESSMENT.pdf` |
| Operator / SRE | `03_operations/RUNBOOK.pdf` + `03_operations/BACKUP_RESTORE.pdf` |
| Detection engineer | `04_security/AI_OUTPUT_CONTRACT.pdf` + `02_requirements_and_use_cases/USE_CASES.pdf` |
"""


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def copy_one(src: Path, dst_dir: Path) -> tuple[Path, bool]:
    """Copy src into dst_dir. Returns (dst_path, success)."""
    if not src.exists():
        return (dst_dir / src.name, False)
    dst_dir.mkdir(parents=True, exist_ok=True)
    dst = dst_dir / src.name
    shutil.copy2(src, dst)
    return (dst, True)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Build the export/ bundle.")
    parser.add_argument("--clean", action="store_true", help="Remove export/ before rebuild")
    args = parser.parse_args(argv)

    if args.clean and EXPORT_DIR.exists():
        print(f"[clean] removing {EXPORT_DIR}")
        shutil.rmtree(EXPORT_DIR)

    EXPORT_DIR.mkdir(parents=True, exist_ok=True)

    # Top-level READMEs
    write_text(EXPORT_DIR / "00_START_HERE.md", TOP_README)
    write_text(
        EXPORT_DIR / "MOD_LOCAL_DO_NOT_DISTRIBUTE_PUBLICLY" / "README.md",
        MOD_README,
    )
    write_text(EXPORT_DIR / "PUBLIC_SHAREABLE" / "README.md", PUBLIC_README)

    copied = 0
    missing: list[str] = []
    for subdir, files in LAYOUT.items():
        dst_dir = EXPORT_DIR / subdir
        for fname in files:
            src = ROOT / fname
            _, ok = copy_one(src, dst_dir)
            if ok:
                copied += 1
            else:
                missing.append(fname)

    print(f"[export] {copied} files copied into {EXPORT_DIR}")
    if missing:
        print(f"\n[export] WARNING: {len(missing)} missing source files:")
        for m in missing:
            print(f"  - {m}")
        print("\nRun: python tools/pdf_build/build_docs.py --add-mod-set")
        print("Run: python tools/pdf_build/build_csv.py")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
