"""Notification model for cross-system alerts (chat mentions, case assignments, etc.)."""

from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ion.models.base import Base


class Notification(Base):
    """A notification for a user — generated by chat mentions, case assignments, etc."""

    __tablename__ = "notifications"
    __table_args__ = (
        Index("ix_notifications_user_unread", "user_id", "is_read"),
        Index("ix_notifications_created", "created_at"),
        # Hot path: list endpoint orders by created_at DESC for a single user.
        # Composite index lets Postgres serve list+ordering in one index scan.
        Index("ix_notifications_user_created", "user_id", "created_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id"), nullable=False
    )
    source: Mapped[str] = mapped_column(
        String(32), nullable=False
    )  # 'chat_mention', 'chat_dm', 'case_assigned', 'gitlab_assigned', 'system'
    source_id: Mapped[Optional[str]] = mapped_column(
        String(128), nullable=True
    )  # ID of the source object (room_id, case_id, etc.)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    url: Mapped[Optional[str]] = mapped_column(String(512), nullable=True)
    is_read: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_toast_shown: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=func.now(), nullable=False
    )

    # Relationships
    user: Mapped["User"] = relationship("User", foreign_keys=[user_id])

    def __repr__(self) -> str:
        return f"<Notification(id={self.id}, user_id={self.user_id}, source='{self.source}')>"
